### ISSUE TITLE
Extend Application Navigator: Add shorthand for Table Dictionary 

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#1]
It would be really helpful to directly access the menu "Configure Table" via shorthand in the manner of "incident.list". I'm aware of "incident.config", but that gives everything except for the Column Configuration Page.

My suggestion: "incident.struct". And for opening in new Tab: "incident.STRUCT".

![image](https://user-images.githubusercontent.com/6060660/40954192-c13c172e-6883-11e8-916d-c9c096fa3753.png)

**Comment by meinzeugde** [comment]
Closed with #2

**Comment by arnoudkooi** [comment]
Thanks, ill get back next week I’m on holiday this week, no laptop ;)
