### ISSUE TITLE
Protect Name field from accidentally updating 

### ISSUE THREAD

**Issue by cmcdevitt** [arnoudkooi/ServiceNow-Utils#100]
When opening a Script in SN (Script Include, Business Rule, etc.) The focus tends to be on the Name field. During standard editing, I have accidentally updated this field, which I typically catch and fix. While testing out ScriptSync I did the same thing, but I did not notice it right away. When I saved the code I was working on in Visual Studio, the new name was applied to the Script Include. I did not see this error until several updates later.  
I want to propose a Check box in the Options Tab called something like "Protect Name Field". When checked, and you open a page with the "name" field, it sets the Name field to read-only so it can not be accidentally updated!

Sample code:
//Make readOnly
var table_name = g_form.getTableName();
var field_name = gel(table_name + '.name');
field_name.readOnly = true; //When unchecked, set this to false
field_name.blur();//When unchecked ignore this

**Comment by arnoudkooi** [comment]
The name field cannot be modified when editing a script via ScriptSync. There must have been a save from the form itself.
And I think setting the field to readonly will not improve the experience and may even be annoying/confusing...

Appreciate your suggestion, feel free to submit another one.

**Comment by cmcdevitt** [comment]
@arnoudkooi I guess I did not explain the issue very well. When I open a form in ServiceNow it will default to the Name field as the selected field. Then.... I accidentally type something into the field that overrated this script name AND I do not notice it. I then use ScriptSync and update my code, then I save it in VS. AND then the new code from ScriptSync PLUS my typo in the Name field are saved!  If you look at my sample code it prevents us, humans, from making that silly mistake.
