### ISSUE TITLE
Slashcommands not showing

### ISSUE THREAD

**Issue by rasppliances** [arnoudkooi/ServiceNow-Utils#101]
Hello,

I just started with a new company, and the computer they gave me is very locked down.  I don't have admin access, and can't access all folders on the hard drive.

When I open the Slashcommands tab of the extension, there are no Slashcommands present.  When I add one, it still doesn't show up in the list, and it just goes away.

Also, using CTRL-/ to open the Slashcommand menu doesn't work.  Nothing happens at all.  It's like Slashcommands are turned off.

I'm not sure if you'll be able to help fix this, as I know it's more of an issue with how locked down this computer is, but, "Help me, Obi Wan Kanobe, you're my only hope."

Thanks!

**Comment by arnoudkooi** [comment]
Looks like a policy issue, can you check with your IT dep or try another browser?

**Comment by rasppliances** [comment]
I'm 100% sure it's a policy issue, but I'm also 100% sure my IT isn't going to help. :(

Is it possible to change where the Slashcommands are stored?  Even if I have to edit a settings file or something.

Another thing I'm noticing is that the icon next to scripts fields is missing, so I can't open the script in Visual Studio Code.  Again, I'm sure that's a policy thing, but I've got less hope for that.

**Comment by arnoudkooi** [comment]
Looks like one of the policies is that an extension can not modify the page, so storing the slashcommands will not work.
You are not able to use oob commands like /me either right?

**Comment by arnoudkooi** [comment]
I'm afraid i can not influence this, let me know if you thinkotherwise
