### ISSUE TITLE
Cannot use View Data popout in firefox

### ISSUE THREAD

**Issue by ian-gallmeister** [arnoudkooi/ServiceNow-Utils#102]
The popout on firefox hasn't been showing any data. I get a #TABLE / SYS_ID row and an error one --
Label: Error
Name: Error
Type: undefined
Value: Record data not retrieved
Display Value: jsn.result is not defined

Update Set, Updates, and Nodes all pull up nothing too and ask if I'm an admin (I am), but I don't know if that's relevant.

If there's any sort of debug mode or logs I can grab, I'm happy to dig them up and attach them.

Thanks!

**Comment by arnoudkooi** [comment]
Works for me in FireFox, maybe a browser restart?

**Comment by ian-gallmeister** [comment]
I've tried that (and did it again, no dice)
But it gave me an idea - I started the browser with a new browser profile that didn't have the containers add on

It worked there

**Comment by arnoudkooi** [comment]
I'm able to replicate, only have issues finding how to debug background script in Firefox @wiiaboo any idea?

**Comment by wiiaboo** [comment]
I can't reproduce the issue, but I do know where you can use the Debugger on the background script:
`about:devtools-toolbox?id=email%40arnoudkooi.com&type=extension`

**Comment by arnoudkooi** [comment]
You did use the container addon and place the instance in a container?

**Comment by arnoudkooi** [comment]
I had a restart of my Mac today and now I'm not able to reproduce anymore..

**Comment by wiiaboo** [comment]
I think it might be because it's using the wrong container's cookies.
I also thought `X-UserToken=g_ck` might be used instead of having to use the correct cookies, but apparently it's not enough?

**Comment by wiiaboo** [comment]
This might be "fixed" by doing the `$.ajax()` in the containerized tab itself, instead of on `background.js`.

**Comment by arnoudkooi** [comment]
I tought I did fix this a while back by passing in cStoreId

**Comment by arnoudkooi** [comment]
Strange did I always leave that commented?

**Comment by ian-gallmeister** [comment]
I rebooted and tried again on an incident. Looking at `about:devtools-toolbox?id=email%40arnoudkooi.com&type=extension`, I see a failed request to /api/now/ui/meta/incident with return code 401.

Request headers includes an X-UserToken header and a Cookie header that sets `JSESSIONID=<numbers>; BIGipServerpool_<instance>=<other number>;`

I don't know if there's anything else in there that could help you

**Comment by arnoudkooi** [comment]
Still having this issue?

**Comment by lgnilssen** [comment]
I'm seeing the same issue as @ian-gallmeister described when running Firefox with temporary/multi-account containers enabled, and it works fine on a new Firefox profile with only SNUtils installed.

**Comment by arnoudkooi** [comment]
Cleaning up open issue, please comment if you have questions. Can reopen if needed..

**Comment by moritzrupp** [comment]
Hi @arnoudkooi ,

I'm having the same issue. I'm using Firefox with Multi-Account Container enabled. Then, SNUtils 6.1.4.7 doesn't show data in "View Data" or displays the node information or Table information, etc.

If I disable Multi-Account Container, it is working as expected.

Thanks for your support and best regards
Moritz

**Comment by Faeb35** [comment]
Same issue, creating a new Firefox profile fixed it.
