### ISSUE TITLE
Feature Request: Short cut to copy sys_id

### ISSUE THREAD

**Issue by dvp4** [arnoudkooi/ServiceNow-Utils#103]
Hello Arnoud,
Is there a short cut to copy the sys_id of the record?

Thank you!!

**Comment by arnoudkooi** [comment]
Looks like you can!
Use this as the URL in your custom command:

`javascript:copyToClipboard('$sysid')`

(Note that i was not aware of this, but tested based on your Issue :) )

**Comment by arnoudkooi** [comment]
Not sure if this is a bug or a feature. Thoughts?

**Comment by dvp4** [comment]
Thank you for the quick response. This is more a feature request i guess. Sorry, if I requested in the wrong place.

I have tried creating it as an custom command and is working after hitting "/" followed by command + Enter. After hitting enter it is copying the sys_id but redirecting to a page with value as "true".
this is working only in the nav_to.do page, is there a way to make it work for new tab windows.

Also, is there a way to use this command with Ctrl button, like how we save record using Ctrl + S

**Comment by arnoudkooi** [comment]
With bug or feature I actually meant if I should allow javascript in slashcommands, maybe others will chime in.
It does not redirect in my case. Assigning it to a shortcut is not possible at this point.

**Comment by dvp4** [comment]
Looks like issue is occuring in Mozilla but not in chrome.

**Comment by wiiaboo** [comment]
> Not sure if this is a bug or a feature. Thoughts?

User-submitted slashcommands result in URLs and are executed as such. It's the same as having a bookmark with `javascript:alert('stuff')` and opening it normally.

**Comment by arnoudkooi** [comment]
with the added recent added funtion, assigning `javascript:copyToClipboard('$sysid')` to the `/shortcut` command, you should be able to set a shortcut. Please confirm  if this works.
