### ISSUE TITLE
Show xml is broken

### ISSUE THREAD

**Issue by Belal-Salas** [arnoudkooi/ServiceNow-Utils#106]
I am using Firefox 88.0 when I use slash command /xml it opens a new tab with plain text (no xml) and this applies ServiceNow built in feature 'Show xml' both seems to be broken I tried to open ServiceNow in incognito windows -snutils is not activated- and 'Show xml' worked just fine.
attaching a screenshot, please let me know if you require more information.

![Screen Shot 2021-04-27 at 3 56 11 PM](https://user-images.githubusercontent.com/70879218/116305178-6bffc780-a771-11eb-88ab-05643c822c9d.png)

**Comment by wiiaboo** [comment]
Use /xmlsrc instead. It's a known issue in Firefox. It's caused by some other addon you have enabled that act on XML pages.

**Comment by Belal-Salas** [comment]
You saved my day @wiiaboo , it turned out that AdBlock is the plugin who break the xml view, it is working now.
Thanks a lot

**Comment by arnoudkooi** [comment]
Fyi: I did a fix in the manifest for FireFox that should fix the XML issue

**Comment by A3r0Sp1k3** [comment]
The exact same behaviour is also occuring when making an API call in Firefox.

**Comment by arnoudkooi** [comment]
Can you share a URL?

**Comment by A3r0Sp1k3** [comment]
An example would be https://dev107749.service-now.com/api/now/table/incident, or anything really that uses /api/now/table.

**Comment by arnoudkooi** [comment]
I'll apply the same fix to this URL pattern in the next release

**Comment by Jonn3y** [comment]
I have the same issue on the OnPrem Plugin.
