### ISSUE TITLE
Viewname helper vulnerable to XSS

### ISSUE THREAD

**Issue by EricMedina024** [arnoudkooi/ServiceNow-Utils#108]
The following code allows for an XSS on forms by using a specially crafted `sysparm_view` query parameter.
https://github.com/arnoudkooi/ServiceNow-Utils/blob/437f23db3a506fe0978e8fc62dd6215d695c330e/inject.js#L1562-L1564
For example, if you go to the following URL in your instance you will be presented with an injected JS alert.
https://yourinstance.service-now.com/incident.do?sysparm_view=%3Cimg%20src=%22fake.internal%22%20onerror=%22alert(1)%22%20width=%220%22%20height=%220%22/%3E
![image](https://user-images.githubusercontent.com/53099692/116733294-87f1ac00-a9b1-11eb-8527-cdcb15a84f97.png)

**Comment by arnoudkooi** [comment]
Thanks I'll DOMPurify this.

**Comment by EricMedina024** [comment]
No problem. It might make sense to use jQuery to do safely add text content instead. I don't typically use jQuery but did some testing and came up with this:
```
const viewElement = $('<i></i>');
viewElement.text('Viewname: ' + viewName);
jQuery('.section-content').first().prepend(viewElement);
```
which seems to add the view name safely as a text node (documentation is here: https://api.jquery.com/text/#text2)

**Comment by arnoudkooi** [comment]
I'm also slowly moving away from jQuery. Addressed in [this commit](https://github.com/arnoudkooi/ServiceNow-Utils/commit/0863bc2cfcace758e17b9552ea7ff70258c468e4 )
