### ISSUE TITLE
Issue saving HTML from Visual Code

### ISSUE THREAD

**Issue by MGOPW** [arnoudkooi/ServiceNow-Utils#111]
When I try to save a widget from Visual Studio, a `<script>` tag gets corrupt, causing issues in previewing the widget.

This is what the original code looks like:
``` 
<div> Test! 
<script> Test test! </script>
</div>
```

And this is what it will look like in the widget editor after saving from VS code:
```
<div> Test! 
&lt;script&gt; Test test! &lt;/script&gt;
</div>
```

Steps to replicate:
1. Open widget code in Visual Code using the save button
2. Make any change to the HTML widget code
3. Save
4. Refresh the widget page in ServiceNow, the script tag is now affected.

**Comment by arnoudkooi** [comment]
In your ServiceNow instance, set the following system property:
glide.rest.sanitize_request_input = false

Let me know if it works :)

**Comment by MGOPW** [comment]
Wow thank you so much for the quick response. That fixed it - I'm super sorry if i missed an obvious bit of documentation somewhere.

**Comment by arnoudkooi** [comment]
Great, no problem. Glad it works now!
