### ISSUE TITLE
Show Technical Names feature causes UI issues with CMDB query builder

### ISSUE THREAD

**Issue by milligna** [arnoudkooi/ServiceNow-Utils#112]
When show technical names feature is switched on, it looks like it causes a dropdown in the "Connection Properties" of query builder to not render properly.

To recreate: 
1. Enable "Show Technical Names"
2. navigate to CMDB Query Builer and create a new CMDB Query
3. Under CMDB Classes, Add Configuration Item to the canvas
4. under Non-CMDB Tables, Add Incident to the canvas
5. Connect the Configuration Items node to the Incident Node
6. under the "Connection Properties" panel, in the CI Reference Column section, observe that the "Use CI reference column" dropdown fails to render the options.
7. Inspect the html using browser devtools - observe that the angular "option" items are poplated with the correct "getClasses" items, but thery don't render on the page properly.

**Comment by arnoudkooi** [comment]
Thanks, this should be fixed in 5.0.1.7. Please try and let me know!

**Comment by arnoudkooi** [comment]
As confirmed on Twitter it was fixed. Thanks Kevin :)
