### ISSUE TITLE
Tables broken in Version 5.0.2.0 Auto Upgraded 2021-05-18 

### ISSUE THREAD

**Issue by gddk** [arnoudkooi/ServiceNow-Utils#113]
I use the tables search almost every day and stopped working today, noticed the version was auto upgraded today to 5.0.2.0, using Firefox 88.0.1 on MacOS 10.15.7

**Comment by arnoudkooi** [comment]
Do you have more details, did you restart the browser?

**Comment by gddk** [comment]
> Do you have more details, did you restart the browser?

Yes, I did restart browser, still no tables in any of the 3 ServiceNow envs I use.

**Comment by gddk** [comment]
Just tried with Chrome, same SN Utils version, 5.0.2.0, works fine with Chrome.  Broken in 88.0.1 (64-bit).

**Comment by gddk** [comment]
In Chrome, if I click the "Refresh" button in the Tables tab, the spinning animation comes on and the tables refresh in a second or two. In Firefox, no tables on the list, if I click "Refresh" nothing happens, no animation.

**Comment by arnoudkooi** [comment]
Thanks, I found the issue and published a fix in 5.0.2.1 (Published for FF only) 
It is approved so you should be able to update. Please let me know!

**Comment by gddk** [comment]
Thank you! I am pleasantly surprised at how fast you picked this up and fixed it. Wow, that was great. I must have caught your attention at the exact right time. Confirmed, it's working now.

**Comment by arnoudkooi** [comment]
Great, happy it's ok now. Thanks for raising the issue!
Pro tip: you can also search tables via [slashcommands](https://youtu.be/CqZ2xXLeeks?t=391)
