### ISSUE TITLE
Firefox: publish On Prem version

### ISSUE THREAD

**Issue by Chouffy** [arnoudkooi/ServiceNow-Utils#114]
Hi!

Thanks for this great tool.
Unfortunately, I would also like to use it on non *.service-now.com instances.
Would it be possible to publish an On Prem version of the addon to Firefox, just like with Chrome?

Thanks,
Chouffy

**Comment by arnoudkooi** [comment]
I did publish this, but it was pulled by Mozilla last year, because of the same codebase as the normal SN Utils one. I have resubmitted it with the request to reconsider this decision. I'll keep you posted.

**Comment by Chouffy** [comment]
If I can help you in this, let me know!

**Comment by arnoudkooi** [comment]
Unfortunately rejected again... Ik can share a xpi file if that would help..

>  Given that this add-on has similar code and functionality as SN Utils please consolidate them into one add-on

**Comment by Chouffy** [comment]
I'm sure you already though about this, but out of curiosity: why can't both addons be merged actually? It could be a whitelist inside the module that by default contain *.service-now.com domain?

Regarding the xpi, that would definitely help me and I would appreciate!
The only problem that I see is that it's not very future-proof 😕

**Comment by arnoudkooi** [comment]
I'll consider merging...

For now, I've copied the XPI to the following location. I'll add this to my publishing script so it stays current
https://arnoudkooi.com/snutils/onprem-firefox-snutils.xpi

**Comment by Chouffy** [comment]
Thanks a lot for sharing the XPI! Unfortunately, I need to use the "normal" Firefox release channel, which I just discovered doesn't allow unsigned XPI to be installed. [This behavior cannot be overridden for this channel.](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct)

I cannot install dev or nightly Firefox, so I will wait for the merge then.
Shall we close this issue or keep it open to track of the merging?

**Comment by arnoudkooi** [comment]
Cleaning up open issue, please comment if you have questions. Can reopen if needed..

**Comment by Chouffy** [comment]
@arnoudkooi well I would still love to use SN Utils on Firefox with On Prem ... but it seems this won't happen because of Mozilla policy. I'll stuck with Chrome 😥
