### ISSUE TITLE
Idea: 'Show Technical names on page load' be instance specific

### ISSUE THREAD

**Issue by gczutor** [arnoudkooi/ServiceNow-Utils#118]
I'm using this setting (turned on) for sub-production instances extensively but drives me crazy on PROD ones (for eg working with stories, incidents, etc). If there's a way to make this instance specific (similarly to the favicon overlay)?

**Comment by arnoudkooi** [comment]
Are you aware you can assign a browser shortcut to this function? I'm a bit afraid of making things too complex with per-instance settings

**Comment by gczutor** [comment]
Yes sure but it it more clicks than if it was automated. This is not a must, just an idea.

**Comment by Trampf** [comment]
I use "Alt + T" as a browser extension shortcut for technical names, which helped me a lot.

**Comment by gczutor** [comment]
> I use "Alt + T" as a browser extension shortcut for technical names, which helped me a lot.

Good hint, thanks. The original Cmd+<number> combinations don't work at all for Mac+Chrome as they have different meanings. Loads of other shortcuts I've tried to assign to it don't even get saved for some reason. But option+T or option+4 or such seem to work.
