### ISSUE TITLE
New Feature Request - Slashcommand SysID Searches

### ISSUE THREAD

**Issue by Qualous** [arnoudkooi/ServiceNow-Utils#120]
Please consider adding sys_id search functionality to the SlashCommands.

For example, today if this command is used `/br f78dc6038f00110036bf21ca47e79af8`
The resulting page is:
https://instance.service-now.com/sys_script_list.do?sysparm_query=nameLIKEf78dc6038f00110036bf21ca47e79af8

I'm hoping that the sysid can be detected using a simple regex and if matched, the resulting page can be:
https://instance.service-now.com/sys_script_list.do?sysparm_query=sys_id%3Df78dc6038f00110036bf21ca47e79af8
or
https://instance.service-now.com/sys_script_list.do?sysparm_query=nameLIKEf78dc6038f00110036bf21ca47e79af8%5EORsys_id%3Df78dc6038f00110036bf21ca47e79af8

**Comment by arnoudkooi** [comment]
Does the already available sys_id search not work for you?
available via:
`/sysid f78dc6038f00110036bf21ca47e79af8
`. 
or  

`/f78dc6038f00110036bf21ca47e79af8
`  

As well as direct via the classic navigator
![image](https://user-images.githubusercontent.com/840781/128031918-e402f041-2e50-4785-9dbf-cca954c4ea59.png)

**Comment by Qualous** [comment]
That'll do!  I was unaware of both options so thank you for the quick response!

**Comment by arnoudkooi** [comment]
great!
