### ISSUE TITLE
Empty link text in the clickToList function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#123]
**First example:**
1. Open an OOTB instance
2. Open any active (Short description must be editable) existing incident (with non-empty Short description)
3. Open the console and run: `g_form.getDisplayBox('short_description').value // see the correct returned value`
4. Delete one character from the Short description
5. Open the console and run: `g_form.getDisplayBox('short_description').value // see the wrong (empty string) returned value`
6. If the returned value is correct then try again - go to step 4
7. Hover the cursor over the Short description label and click _Ctrl+left mouse click_ and see the result: empty string was assigned to the _valDisp_ variable)

https://user-images.githubusercontent.com/26461232/131650903-ce3fce14-c89c-42cb-9ce2-8de53896e3a0.mp4

**Second example:**
1. Open an OOTB instance
2. Open any existing incident (with non-empty Short description)
3. Open the console and run: `g_form.getDisplayBox('short_description').value // see the correct returned value`
4. Hover the cursor over the Short description label and click _Ctrl+left mouse click_ and see the result: correct behaviour - field value was assigned to the _valDisp_ variable)
5. Hide the message
6. Open the console and run: `g_form.getDisplayBox('short_description').value // see the wrong (empty string) returned value`
7. If the returned value is correct then try again - go to step 4

https://user-images.githubusercontent.com/26461232/131650734-bed594d5-1133-4d3e-96e1-f99f5d2b0ec2.mp4

Looks like it's not safe to rely on the hidden element. Based on that behaviour I propose to change this line:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/f09130bc96a735045d94bd9dfa18e65fc744306a/inject.js#L1217
to:

`valDisp = g_form.getDisplayBox(elm) && g_form.getDisplayBox(elm).value || g_form.getValue(elm);`

This change keeps the old logic but also ensures that returned value of the _getValue_ will be used as a fallback value.

**Comment by arnoudkooi** [comment]
Looks solid, thx. I'll commit your PR

**Comment by ovarn** [comment]
Thanks!
