### ISSUE TITLE
Encoding issue in the clickToList function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#125]
_clickToList_ does not work as expected if the value is multiline text or contains special characters.

https://user-images.githubusercontent.com/26461232/131986198-141bb21e-75fa-4576-820a-6fd6fc3c7bc6.mp4

Root cause: some characters cannot be part of a URL and must be encoded.

**Comment by arnoudkooi** [comment]
Thanks, looks your a active user of this feature :)

**Comment by ovarn** [comment]
Ahaha, yes, it's one of my favorite feature.
