### ISSUE TITLE
Processing issue in the clickToList function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#128]
There are two issues in the _clickToList_. Both are related to the same part of the code.

**First:**

1. Open the incident form
2. Hover the cursor over the Short description label and click _Ctrl+left mouse click_
3. Hover the cursor over the Description label and click _Ctrl+left mouse click_
4. See that nothing happens since the '_description_' is a sub-string of the '_short_description_'
https://github.com/arnoudkooi/ServiceNow-Utils/blob/511e483feaff451b27d87208e0d977ca894ed096/inject.js#L1258

https://user-images.githubusercontent.com/26461232/132336526-b6bf58da-0545-4dfa-948e-facd10345d95.mp4

**Second:**
1. Open the incident form
2. Hover the cursor over the Category label and click _Ctrl+left mouse click_
3. Change the value of the Category to something else
4. Repeat the second step
5. See that nothing the link was not changed
P.S. If the changed value is an empty string it even adds the second sub condition to the query

https://user-images.githubusercontent.com/26461232/132336623-e6b41090-0265-4186-a929-6a914c321ea9.mp4

**Comment by arnoudkooi** [comment]
Thankx again!
