### ISSUE TITLE
Unescaped character in the clickToList function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#130]
The _clickToList_ does not work if the value contains a caret (^) character.

https://user-images.githubusercontent.com/26461232/132521446-170c9a74-f0f5-49a6-abe5-51e92f26287a.mp4

This is the last issue I found in that function :)

**Comment by arnoudkooi** [comment]
Merci!

**Comment by ovarn** [comment]
Thank you too for merges!

**Comment by arnoudkooi** [comment]
Now published in 5.2.1.0!

**Comment by ovarn** [comment]
Perfect :)
