### ISSUE TITLE
Idea: Ability to hide rows with empty fields in "View Data" list

### ISSUE THREAD

**Issue by iar42** [arnoudkooi/ServiceNow-Utils#132]
Just throwing this in as an idea / small feature request..

Not sure if it would make sense for more people but sometimes I'm looking at records via the "View Data" feature and would like to be able to show only fields that actually have data (hide all empty fields) to help me see at a glance what fields are actually in use on the specified record / record type.

Maybe something similar to the "Toggle Type" button but instead "Toggle empty fields" which would hide or show empty rows.

Sorting the list by Display Value column helps with skipping over empty lines but in turn makes it harder to find the fields as Labels and Name columns are no longer in order.

**Comment by arnoudkooi** [comment]
Adding this in the next release:
![image](https://user-images.githubusercontent.com/840781/140585909-99246d6c-e7dd-473b-9048-6faa792a3b62.png)

**Comment by arnoudkooi** [comment]
Please check, now published in version 5.2.5.5

**Comment by iar42** [comment]
Looks really good, this will definitely come in handy!  Thanks!
