### ISSUE TITLE
5.2.2.5 background script editor no longer has autocomplete

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#134]
When i tried out 5.2.2.0's BG editor it had autocomplete, but the latest update seems to have removed that, maybe the load times are too small? I can't see anything in the commit that suggests you removed it on purpose. Tested on chrome

From today: 
![image](https://user-images.githubusercontent.com/30616047/133526437-ced6739f-9cdd-4d9f-94c8-4ffe8557815c.png)

From a couple days ago:
![image](https://user-images.githubusercontent.com/30616047/133526565-a7a24e09-4ec3-4b58-b2fc-3a7a43bc414d.png)

**Comment by arnoudkooi** [comment]
I had removed a large .js (js/monaco/vs/language/typescript/tsWorker.js) file I thought was not needed.
The file was to large to parse when submitting the add-on to Mozilla for review.
Obviously this is needed for the autocomplete to work.

In the Chrome version I have added it back.
I have added an Issue to the Mozilla linter repo, hoping to find a solution for FireFox
https://github.com/mozilla/addons-linter/issues/3915

**Comment by VanWeapon** [comment]
Confirmed autocomplete is back, can probably close this off now

**Comment by arnoudkooi** [comment]
The issue in the [FireFox Linter repo](https://github.com/mozilla/addons-linter/issues/3915) is closed as won't fix.I'll see if I can find another way to make it work on FireFox, so leaving this open for now.

**Comment by arnoudkooi** [comment]
No fix for FireFox in the current way I deploy to FireFox I'm emptying the content of the tsWorker.js file. Happy to reopen of there is a better solution

**Comment by arnoudkooi** [comment]
Please try if it works now version 5.6.1.3 in FF.
I hope this is acceptable for the Mozilla Reviewers.

**Comment by arnoudkooi** [comment]
Idea to fix did not work :(

**Comment by arnoudkooi** [comment]
Can you try in 6.0.1.6 ?

**Comment by arnoudkooi** [comment]
In Backgroundscript at least it should work...

**Comment by arnoudkooi** [comment]
Linking to #437
