### ISSUE TITLE
Safari On Prem

### ISSUE THREAD

**Issue by RickSeiden** [arnoudkooi/ServiceNow-Utils#135]
Hello,

I know Safari doesn't have all the features that Chrome has, but I'm wondering about an On Prem instance.  I searched the issues for any information but couldn't find anything.  I'm sorry if this is a duplicate.

**Comment by arnoudkooi** [comment]
I can see if I can open-up this version up to work on every domain.
With Safari you need to grant access to every subdomain anyway, before it works..

(Bare with me a few weeks please)

**Comment by RickSeiden** [comment]
Thanks! I have to admit, though, that I primarily wanted this because there
was an issue with accessing this particular on prem instance with Chrome.
Turns out that there was an issue with the certificate, and some parts of
the instance were considered insecure, so Chrome blocked them.  I adjusted
the settings, and now Chrome works fine, so this isn't an issue for me
anymore.  If there's no other demand for it, you can scrap it.

Thanks for a great product!

**Comment by RickSeiden** [comment]
Along the lines of thanking you for a great product, I was looking for a donation/"buy me a coffee" link, but couldn't find one.

**Comment by jacebenson** [comment]
@RickSeiden he has this in the extension https://www.patreon.com/snutils
![image](https://user-images.githubusercontent.com/638764/135281093-6659cc0c-786b-43f0-a05e-76cb6f1cf181.png)

**Comment by RickSeiden** [comment]
Can't believe I missed that! Thanks.

**Comment by arnoudkooi** [comment]
Cleaning up open issue, please comment if you have questions. Can reopen if needed..

**Comment by RickSeiden** [comment]
The only comment is that there isn't an on Prem instance for Safari, but I don't need one anymore, so I'm good.
