### ISSUE TITLE
A few bugs in the searchSysIdTables function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#140]
1. The script does not search in some tables: _x_dev_case_ (contains "_v__"), _x_objects_task_ (contains "_ts__"), _u_cmdb_spa_app_ (contains "_pa__").
Root cause: the "contains" operator is used in the query since there is no "does not start with" operator in ServiceNow.
https://github.com/arnoudkooi/ServiceNow-Utils/blob/e6f838f7a4029ec95f40365591f68a570f93a2d4/inject.js#L2792
Proposal: check the table name in the while loop using the String.prototype.startsWith and skip undesired tables.

2. An error in the log after running the search: 

![2021-10-14 16_15_03-ServiceNow IT Service Management Suite - Development Environment](https://user-images.githubusercontent.com/26461232/137335465-a02720ee-2f89-4c4a-9b7e-631c93232df5.png)
Root cause: _cmdb_ire_partial_payloads_index_ table has no _sys_id_ field.
Proposal: exclude the table from the search.

3. Incorrect redirect.
Root cause: JS error in the OOTB before query Business rule "Multisourrce Load More Error Message" [4c3a4a960f2650109bf1552dc4767ec0].
> Evaluator: org.mozilla.javascript.EcmaError: "RP" is not defined.

Due to that error, the script (which we executed remotely) printed to the output. The printed text contains the specific text pattern that the tool used to find the result. This is the part of the response:
![2021-10-14 15_42_45-Knowledge Articles _ ServiceNow](https://user-images.githubusercontent.com/26461232/137336449-6a2f54c6-1dbf-4d81-9822-113068e72619.png)
Then the output incorrectly parsed with the regex:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/e6f838f7a4029ec95f40365591f68a570f93a2d4/inject.js#L2819
As a result:
![2021-10-14 15_45_53-Knowledge Articles _ ServiceNow](https://user-images.githubusercontent.com/26461232/137336989-61eee270-4f3d-4ac3-a7df-9fd8b1bf11bf.png)
It leads to wrong redirect:
![2021-10-14 15_46_12-ServiceNow](https://user-images.githubusercontent.com/26461232/137337067-408b2b1b-8b37-4d79-8f9a-7b69f73bb456.png)
Proposal: disable before query business rules before running the query (I don't see any potential issues because only admins have access to that feature). That change will also increase the correctness of the search.

**Comment by arnoudkooi** [comment]
Looks good, thanks.
( I'm thinking of placing the status in the popup, similar to the way it works with the /rnd command)
