### ISSUE TITLE
Feature request: show hidden variables

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#150]
I would like to have the same feature for showing hidden cat item variables the same way as it works for fields and sections.

**Comment by arnoudkooi** [comment]
Thanks again! Do you have a screenshot, can you post here? and maybe a Twitter handle?

**Comment by ovarn** [comment]
Do you mean a screenshot for a Twitter post?

**Comment by arnoudkooi** [comment]
Yes, where the unhide function is used...

**Comment by ovarn** [comment]
Select :)
![1](https://user-images.githubusercontent.com/26461232/141657893-ad5b6305-c432-47bd-9b53-6b9f8424db93.png)
![2](https://user-images.githubusercontent.com/26461232/141657894-a456968a-14fa-467b-9737-532a3a0de9af.png)

**Comment by arnoudkooi** [comment]
Thanks, this is on form after submit, not on Portal right?

**Comment by ovarn** [comment]
It's RITM form on the backend.

**Comment by arnoudkooi** [comment]
fyi: https://twitter.com/sn_utils/status/1459619471396589569

**Comment by ovarn** [comment]
Thanks!
