### ISSUE TITLE
slash command to open record history

### ISSUE THREAD

**Issue by mevops** [arnoudkooi/ServiceNow-Utils#152]
Hi @arnoudkooi,

I'd like to implement a slash command to open the Record History for the current record.

The UI path I'd be replicating would be (on a record you want to view the history of changes to): 
- Additional actions/Burger bar/Right click header
- Hover over "History"
- Click "List"

![image](https://user-images.githubusercontent.com/67866833/141816168-79f42042-606e-4e29-95a3-d0931bc21f48.png)

![image](https://user-images.githubusercontent.com/67866833/141816287-ab036eec-6a27-4ca2-bd41-0d3ddb3e36b5.png)

Is this a feature you'd be okay being added?

**Comment by arnoudkooi** [comment]
Looks like this can be done with a custom command `sys_history_set.do?sysparm_query=table=$table&id=$sysid` Any more demand to add this by other watchers?

**Comment by mevops** [comment]
Unfortunately in a domain separated or multi time zone/language instance and there can be multiple history sets for each record.

https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0744473
> A new history set is created for each possible combination of the following user profile factors:
> 
> Language
> Timezone
> Domain
> Date/Time Format
> If the date of the last update on the record and the last entry on the sys_history_set table differ then that will also trigger the creation of a new history set.

**Comment by arnoudkooi** [comment]
In Chrome `javascript:showHistoryList()` as URL should work, could you try?

**Comment by tezdog** [comment]
FWIW, javascript:showHistoryList() works for me in Firefox.  I've now added this as a custom command, thanks!

**Comment by mevops** [comment]
Hey Arnoud, this is essentially exactly what I hoping to use so it mirrors the OOTB UI path to get there.

The bit I'm not sure how to do yet is handle being able to open it into a new tab (ctrl + enter on command), that was the part I wasn't going to bother spending time on unless you liked the feature.

To my knowledge it will be a little tricky because `showHistoryList` works by submitting the UI Action "show_history", which is a hidden core UI Action I can't get any access to. I've not looked into a way to pop a UI Action submit to a new tab before

ps - really sorry for delay replying, I didn't get notified for some reason
