### ISSUE TITLE
GlideRecord script page confused on sys_ui_list record

### ISSUE THREAD

**Issue by gczutor** [arnoudkooi/ServiceNow-Utils#155]
GlideRecord script generating doesn't work when displaying a sys_ui_list record. It works with other tables but this one seems to cause some issue, see screenshot: 
![Screen Shot 2021-12-03 at 9 46 04](https://user-images.githubusercontent.com/83219558/144573418-7be12b7d-4f29-479e-b847-09efb433129d.png)

**Comment by arnoudkooi** [comment]
Problem is the table name ending in `_list` that assumes were dealing with a list.  I'll  have a look to find a fix

**Comment by gczutor** [comment]
Makes sense. However, `sys_ui_list` is an exception, so you may cover it in the code. There are a bunch of other tables ending with `_list`: `https://<instance>.service-now.com/sys_db_object_list.do?sysparm_query=nameENDSWITH_list`

**Comment by arnoudkooi** [comment]
Can you update to 5.2.7.7 and check if the fix solves the issue?

**Comment by gczutor** [comment]
Seems working, thanks for the quick fix 👍
