### ISSUE TITLE
Link to open in VS code stops working

### ISSUE THREAD

**Issue by pingje** [arnoudkooi/ServiceNow-Utils#158]
I mentioned this issue on Twitter, and thought I'd solved it by reinstalling, but it is continuing. When I click the disk icon next to a script field to open it in VS Code, nothing happens. However, if I open an existing script file from my script sync folder and update it, the updates flow back through from VS Code to the script tab in question.

Inspecting the disk icon (not sure if this is helpful but here you go) (Disabling dark reader doesn't change anything either, though it does show some extra lines in the screenshot)

![image](https://user-images.githubusercontent.com/14956817/145904673-c88f5aec-bed2-4cfa-9626-8d18ac6308a1.png)

I'm getting the following error when I open the dev console on the script helper tab:

![image](https://user-images.githubusercontent.com/14956817/145903404-0f3cb7ba-4a10-4bea-b17a-6eb17cd27eb8.png)

Reinstalling the extension in Chrome or Vivaldi seems to solve the issue temporarily, but not for long. I have also reinstalled the extension in VS Code and that did not resolve the issue or change the error. Here's the message at localhost:1977:

![image](https://user-images.githubusercontent.com/14956817/145903741-ddf5b34c-35d7-4e10-b0e3-6bdfdfc01909.png)

This is happening for me on two machines, one running Windows 10, and one running WIndows 11.
It is happening in Vivaldi, Chrome, and Firefox. 
I've reinstalled the extensions both in the browser and in VS Code. Just for Firefox, I tried disabling all extensions except for sn-utils and disabling all extensions in VS Code except sn-scriptsync, but that didn't resolve the issue either. ServiceNow is trusted with no blocking enabled. I've restarted my browser, closed and re-opened VS Code, and rebooted the machine.

Version info: 
SN: Quebec patch 7 hoftix 2b

Vivaldi 5.0.2497.28 (Stable channel) (64-bit)
Firefox 95.0
Chrome 96.0.4664.110 (Official Build) (64-bit)

VS Code 1.63.0 2021-12-07

**Comment by arnoudkooi** [comment]
From extension settings, can you open background page to check for console errors there? 
![image](https://user-images.githubusercontent.com/840781/145906297-dc2681f2-6467-48df-9cd1-be5561a3d284.png)

**Comment by pingje** [comment]
Here's what I see:
![image](https://user-images.githubusercontent.com/14956817/145907377-7bae7d7d-0a56-4416-838c-098ae04bf9ff.png)

**Comment by arnoudkooi** [comment]
strange, could you set a icon bg, or disable the setting?
![image](https://user-images.githubusercontent.com/840781/145907721-2e78b76b-df52-4172-be04-14412de7b019.png)

**Comment by pingje** [comment]
There's no error in the background page or ScriptSync Helper tab now, but still nothing happens when I click the disk icon.

**Comment by pingje** [comment]
I tried reinstalling, refreshing etc. again and I saw this error, not sure if it matters:
![image](https://user-images.githubusercontent.com/14956817/145913962-0aa352f8-9c3b-40e6-84f1-b6a3eb7876f3.png)

**Comment by arnoudkooi** [comment]
Would you be available at 11 AM PT for a quick call to troubleshoot?

**Comment by pingje** [comment]
Unfortunately no, but any time before that or after noon would work for me.

**Comment by arnoudkooi** [comment]
If you are available now, please join my room if you can...
https://servicenow.zoom.us/my/arnoudkooi

**Comment by pingje** [comment]
Apologies, I just saw this. I'm trying to join now, but I understand if you
need to do it another time.

**Comment by arnoudkooi** [comment]
Thanks for checking in to troubleshoot.
I just published version 5.2.9.2. Should be available now. Can you upgrade and check if it works?

**Comment by pingje** [comment]
I upgraded to 5.2.9.2 and the issue is resolved. Thanks for your time this morning, and the quick fix!
