### ISSUE TITLE
Idea (not bug)

### ISSUE THREAD

**Issue by jgr1ffin** [arnoudkooi/ServiceNow-Utils#159]
It would be cool if you made a slash command called something like "/createrecord" followed by a table name and query, so that a record is generated matching any query parameters. This would be a quick way of testing scripted conditions.

For example: /createrecord incident active=true^assignment_group=65ac4d97db8be2004aeef15aaf9619ac^assigned_toISEMPTY

Any field that isn't specified in the query would get the default value.

**Comment by arnoudkooi** [comment]
Would something like this work?

Command: `createrecord`
URL: $1?sys_id=-1&sysparm_query=$2
Hint: `Record template <tablename, encodedquery>`

This would pre-fill a form, Im a bit hesitant to actually create records...

**Comment by jgr1ffin** [comment]
Good point, and yes, I think that would be a good compromise! Probably need to test out how it handles additional query parameters like ORDERBY or ISEMPTY, I'm not sure if there needs to be any sort of transformation. That said, I wouldn't mind if it created the record in non-production, perhaps there could be a 3rd parameter flag for this action /createrecord <table> <query> <optional: make>(or whatever).

**Comment by arnoudkooi** [comment]
Please give the current suggestion a shot, as adding records bypasses any client script / UI policy.
