### ISSUE TITLE
Redirect Helper

### ISSUE THREAD

**Issue by JoeBusuttil** [arnoudkooi/ServiceNow-Utils#16]
Extension detects that you're being redirected and adds a link to the page to login.do

Are you happy to accept this feature into the extension?  I hope it's not too controversial.

**Comment by JoeBusuttil** [comment]
Would you mind providing the instance urls where it failed?

**Comment by arnoudkooi** [comment]
Not really specific to an instance. The message is injected on every page, regardless of the instance.

**Comment by arnoudkooi** [comment]
I'll look at your pull request later. Checking the code i don't fully understand the workflow, would you need to open the popup, in order for it to work?
Could you describe how it works from a user perspective?

**Comment by JoeBusuttil** [comment]
![pullrequest](https://user-images.githubusercontent.com/45052797/50130693-edf2a280-02d2-11e9-8479-beadf1fde315.png)
Here's a screenshot, it appears as a kind of notification at the top of the Popup. I did it this way because you said modifying it on page wasn't going to work in all cases.

**Comment by arnoudkooi** [comment]
I believe , this would only worked for internal instances that use signon.service-now.com Please Just hit me up if you want to discuss.
