### ISSUE TITLE
Processing issue in the snuCaptureFormClick function

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#160]
The snuCaptureFormClick function does not work if the value is equal to 'none'.

1. Open any record from this list:
https://<instance_name>.service-now.com/sys_dictionary_list.do?sysparm_query=reference_cascade_rule%3Dnone
2. Switch the view to Advanced
3. Find the "Reference cascade rule" field
4. Press Ctrl and click the left mouse button
5. See that nothing happens

**Comment by arnoudkooi** [comment]
Thanks, merged!
