### ISSUE TITLE
Idea: Replace all script fields with Monaco editor

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#165]
I like the background editor so much, I would like you to consider setting up the monaco editor for all script fields, (and even some others that arent, like, ui action condition field).

If this sounds like something you'd be interestedin let me know.

**Comment by arnoudkooi** [comment]
I'm ok with a PR if it's not too intrusive. We can check in on Slack to chat about it

**Comment by tezdog** [comment]
If implemented, please make this optional.  Not everyone likes the background editor :)
Thanks

**Comment by arnoudkooi** [comment]
What is the issue your experiencing with it?

**Comment by tezdog** [comment]
I don't mind it, but my colleague has problems viewing the light text on black background vs the dark text on light background.  I'm not sure if they had other concerns with it, I can ask when they return in 2 weeks.

**Comment by arnoudkooi** [comment]
Replacing is challenging, what do you think of this implementation @jacebenson ?

![codeeditor](https://user-images.githubusercontent.com/840781/159134826-50028935-d638-444f-93b1-34b61e8f7c30.gif)

**Comment by jacebenson** [comment]
It's neat, I'm not sure though.  I say push it out and lets see what folks think. :D  thanks @arnoudkooi

**Comment by VanWeapon** [comment]
Love the idea, but I also agree it should be an option to toggle
The main use case that comes to mind: When demoing my screen to people, i like to turn most of the obvious SN utils stuff off, like technical names, as it just makes people ask why their SN looks different to mine, and it derails the meeting.

**Comment by VanWeapon** [comment]
The other reason is that if #134 is still not fixed, then this will remove the small amount of autocomplete capability that there is in the native code editor for FF users

**Comment by designedbydave** [comment]
I really dig this new feature and including a text editor within the browser! However, I noticed that the theme field in Service Portal themes record does not display the VScode Sync icon no more. This issue is happening in v5.6.0.0. In FF running v5.5.1.4 the issue isn't there. 

I've attached two screenshots showing the issue. It was working prior to V5.6.0.0 in Chrome. 

![Screen Shot 2022-03-21 at 11 44 48 AM](https://user-images.githubusercontent.com/325398/159333542-c35bc7cf-8f90-4722-b673-2921dbd8c3f8.png)

![Screen Shot 2022-03-21 at 11 44 50 AM](https://user-images.githubusercontent.com/325398/159333539-a438c74a-e9c1-4f02-81fe-70c2019aa4b0.png)

**Comment by arnoudkooi** [comment]
@designedbydave, this should be fixed in the next relaese; 5.6.1.x
@VanWeapon You can disable this via settings; please try if autocomplete now works in FF
@jacebenson Have you tried? this is the best feasible I would say...

**Comment by jacebenson** [comment]
I'm trying it out now.

**Comment by jacebenson** [comment]
I really like it.

**Comment by designedbydave** [comment]
@arnoudkooi -- I forked the repo, modified the HTML markup slightly to remove the overflow scrolling issue. I also touched up the header a bit. 

![Screen Shot 2022-03-21 at 6 42 00 PM](https://user-images.githubusercontent.com/325398/159385348-3ea86602-99f3-4ba9-9b00-9bea3916792b.png)

**Comment by designedbydave** [comment]
@arnoudkooi  - Opened a pull request #190 to fix the overflow issue and adjusted the layout slightly. I also added a class giving the option to pin the header to the footer instead if folks prefer that option. Just don't know how to build it out as a option yet...

**Comment by VanWeapon** [comment]
In background scripts in FF autocomplete works again, however some issues i noticed with this feature:

I'm on FF dev edition and get a blank white page with some console errors when trying to open the monaco editor
![image](https://user-images.githubusercontent.com/30616047/159407048-bcd2e50d-1d4f-45bb-9a8b-55511f92b493.png)
```log
Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/editor/editor.main.js”. [codeeditor.html:1:1](moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/codeeditor.html)
Loading "vs/editor/editor.main" failed [loader.js:6:4413](moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js)
Error: [object Event]
    E moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:6
    _createLoadError moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:8
    _onLoadError moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:8
    c moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:8
    c moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:8
    triggerErrorback moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:6
    load moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:6
    c moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js:6
[loader.js:6:4462](moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js)
Here are the modules that depend on it: [loader.js:6:4479](moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js)
Array [ "===anonymous1===" ]
[loader.js:6:4536](moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js)
Content Security Policy: The page’s settings blocked the loading of a resource at https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/editor/editor.main.js (“default-src”). moz-extension:6:11994
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://0b4173dd-a655-4324-ae39-5ff36c7ce735/js/monaco/vs/loader.js
Source Map URL: ../../min-maps/vs/loader.js.map
```



When on Chrome it works, but i noticed that Client scripts are using Server Side autocomplete rules, and the favicon doesnt load

![image](https://user-images.githubusercontent.com/30616047/159407356-41a61dd3-f0e4-4b34-a8bf-786c74e755de.png)

**Comment by arnoudkooi** [comment]
@designedbydave Thanks, looks good!
@VanWeapon  I reverted it for the code-editor, need to look for a different workaround. 
Maybe we should track the autocomplete for server scripts only in a different issue. When Introducing this for background script, it would only need serverside autocomplete.

**Comment by designedbydave** [comment]
@arnoudkooi Decided to update the editor a bit, use some of the viewport real estate. Haven't figured why the favicon is broken. 
![Screen Shot 2022-03-23 at 9 47 49 PM](https://user-images.githubusercontent.com/325398/159838285-bf281ae0-59ed-4316-81f7-15f35ffce74e.png)

**Comment by designedbydave** [comment]
Fixed broken favicon, console was through some xss policies. So I added a function in the codeeditor.js to grab the favicon and convert it to a blob. 

![Screen Shot 2022-03-23 at 10 14 13 PM](https://user-images.githubusercontent.com/325398/159840875-c05bd1c5-015b-4246-88c5-74d86af7a966.png)

**Comment by arnoudkooi** [comment]
Thanks, looks good. Im travelling today but will accept tomorrow (traveling today).
Did you check with the light theme as well?
Are you on FF, with the favicon issue? 
I copied the updateRecord function, going forward I would like to use the fetch API rather then XMLHttpRequest

**Comment by designedbydave** [comment]
I’ll have a look tonight. I’ll make some adjustments before you accept the merge.

**Comment by designedbydave** [comment]
Made some changes:
- Added an additional property to allow auto resizing of the code editor / browser window
- Updates the CSS to accommodate resize
- Switch favicon function to a fetch, and convert the response to a blob ( I had issues in Chrome loading the Favicon). 

I checked the light theme, it looks good. I wasn't able to test this in FF, I wasn't able to load the unpacked extension for some reason. 

Pull Request #193 

![Screen Shot 2022-03-24 at 7 57 42 AM](https://user-images.githubusercontent.com/325398/159932273-285b9d0a-0f44-4831-b141-56e42e04b425.png)

**Comment by arnoudkooi** [comment]
Thanks Dave and Jace, Will close this one now
