### ISSUE TITLE
Typos found

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#166]
Hey, Phil Swann told me about some typos, and instead of fixing them I'm logging this issue.

[They are on https://github.com/arnoudkooi/ServiceNow-Utils/blob/1fe696223e37c1beee418c62d38faed9487ddfcf/codesearch.js#L399](https://github.com/arnoudkooi/ServiceNow-Utils/blob/master/codesearch.js)

Consider is not spelt right, and same with prefilled.

**Comment by arnoudkooi** [comment]
Thx, will fix :)
