### ISSUE TITLE
Chrome context menus execute twice

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#171]
1. Open any form with the filter navigator on the left side
2. Right click -> SN Utils -> Tools -> Show technical names (/tn)
3. See that the technical names appeared and then immediately disappeared

It happens only when the form is inside the frame. And apparently it happens (twice execution) with all commands.

I tried to add missing `else` on the line number 9, but it did not help:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/768e7ca3dac953bd8b2c100817e0c927f2e15449/content_script_all_frames.js#L6-L10

Any idea why it runs twice?

**Comment by arnoudkooi** [comment]
Maybe triggers from the frame as well as UI16 navigator. Does it happen when the right click is done from the UI16 navigator?

**Comment by ovarn** [comment]
You are right. When I changed:
`method: "runFunction",`
to:
`method: "runFunctionChild",`
for Show technical names (/tn) it started to work. Do you expect any bad consequences after such change?

**Comment by arnoudkooi** [comment]
Ill have a check and adjust

**Comment by ovarn** [comment]
Thanks! What about the missing `else`? Should we add it there?
https://github.com/arnoudkooi/ServiceNow-Utils/blob/5bcb3a3a818f2f095d08d7e969aacf9c2804aaf6/content_script_all_frames.js#L6-L9
Same way as you have it here:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/5bcb3a3a818f2f095d08d7e969aacf9c2804aaf6/background.js#L63-L66

**Comment by arnoudkooi** [comment]
Yes, adding it for the next update. Thanks!

**Comment by ovarn** [comment]
Can I do that? :)

**Comment by arnoudkooi** [comment]
Ok, Why not

**Comment by arnoudkooi** [comment]
Thank you!
