### ISSUE TITLE
Users can remove items from read-only list

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#177]
The current implementation does not work with ACL and dictionary read-only checkbox:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/a5a16b119c77a113143071d729e7ff257374000f/inject.js#L1240
![2022-02-20 15_11_54-Created 2022-02-20 06_01_45 _ List test _ ServiceNow](https://user-images.githubusercontent.com/26461232/154846860-abdb0776-2860-40d2-8de1-bbf056a98940.png)

**Comment by arnoudkooi** [comment]
thanks, good research :)
