### ISSUE TITLE
Possible bug on Vivaldi: Addon unable to read the page / ScriptSyncer may not select a folder

### ISSUE THREAD

**Issue by heroje** [arnoudkooi/ServiceNow-Utils#18]
On opening the ScriptSyncer addon via vivaldi://apps, and clicking on the Folder '...' link to choose a new location for the files, nothing occurs.
Going into developer mode under vivaldi://extensions and inspecting index.html for ScriptSyncer shows up with the following errors in the Console:
[gfmcfepahcbpafgckmomdopifchjbdcg-1543406178741.log.txt](https://github.com/arnoudkooi/ServiceNow-Utils/files/2624367/gfmcfepahcbpafgckmomdopifchjbdcg-1543406178741.log.txt)

As Vivaldi is based on Chromium I thought perhaps the issue is simple - maybe app permissions or differently named functions, but I'm not able to debug it yet.
Version should be the newest: 2.1.1337.51 (Stable channel) (64-bit)

It seems that the ServiceNow Utils addon itself cannot read the page either, maybe it's connected? Logs for its background page as follows:
[jgaodbdddndbaijmcljdbglhpdhnjobg-1543406322579.log.txt](https://github.com/arnoudkooi/ServiceNow-Utils/files/2624378/jgaodbdddndbaijmcljdbglhpdhnjobg-1543406322579.log.txt)

Let me know if I can provide any other details or if I've perhaps missed something.
Thank you for your work!

**Comment by arnoudkooi** [comment]
Lets keep the discussion in the other issue #17
