### ISSUE TITLE
Idea: double-click to show Technical Names to be a configurable option

### ISSUE THREAD

**Issue by dgcst** [arnoudkooi/ServiceNow-Utils#180]
This really isn't a big deal, but I'd really enjoy if the double-click to show Technical Names could be enabled or disabled, for example with a checkbox in the Settings.

**Comment by dgcst** [comment]
There is the setting "Show Technical names on page load". What I think would help is to have a setting like "Show Technical names on double-click", giving the person the ability enable or disable it at will.

**Comment by arnoudkooi** [comment]
What is the problem being solved? I think it is not really obtrusive as it is and don't want too many settings

**Comment by dgcst** [comment]
Not a big problem, it's more a "nice-to-have", so absolutely your call.
