### ISSUE TITLE
Printscreen to attachment in Agent Workspace

### ISSUE THREAD

**Issue by Stajgi** [arnoudkooi/ServiceNow-Utils#182]
Hi @arnoudkooi,
I'd like to ask for the possibility to insert printscreen from the clipboard directly to the Alert records attachment without the need to save the printscreen to a picture file and attach it from there. The aim here is that the daily work is more efficient.
I know it is partially working on alerts in the backend but in the Agent workspace, it is not. When I paste it to work notes in Agent Workspace nothing will happen.

Is there way to extend this possibility for worknotes in Agent Workspace?
We would really appreciate that.

Functionality desired to work as follows:
- a screenshot is taken and copied to the clipboard Shift+WIN+S
- switch to Operator Workspace, navigate to individual Alert
- insert the image object to the Alert worknotes via Ctrl+C, it would appear in the attachments

Official support of ServiceNow couldn't help us with that as the official way to add image is to save it, and then add as an attachment, which is very time consuming.
Thank you for any input on this topic.

**Comment by arnoudkooi** [comment]
The paste shortcut is ctrl-v.
This should work. can you try?
I do look at improving this function in workspace, but the basics should work.

**Comment by Stajgi** [comment]
Sorry, it's typo. Of course Ctrl+V.
But not working. Tried different browsers as well but no success.

**Comment by arnoudkooi** [comment]
what is the url?

**Comment by Stajgi** [comment]
For example:
https://<instancename>.service-now.com/now/workspace/agent/record/em_alert/b0e2655ddb42cdd05b015309f4961975/params/selected-tab-index/1

Are there any restrictions or properties ( settings, scripts ) which could prevent this function?
We found out that sometimes it works on new personal developer instance. But sometimes not.

**Comment by arnoudkooi** [comment]
For me it works, the activity stream updates immediate, the attachments tab needs a refresh
Do you have a console error or activity?

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/840781/156758730-d4dd1598-4b29-4328-b15e-365f057326a4.png">

**Comment by Stajgi** [comment]
Well, on personal instance it works perfectly and it is added immediately (no refresh needed).
On instance we need it, it was tested yesterday also with technicians from ServiceNow. For one it worked but he needed to refresh screen and it's been attached and appeared in Activity. For second tech it didn't work at all. We had similar issue last week. That's why we asked SN tech first and now we tried to ask you directly. 
For now it works. Refresh is needed after paste, but works. So sorry for bothering you. We will test ti again for some period. If we identify some issue, I'll try to contact you with update.
Thank you for your time and for your help here. We really had this issue yesterday again and it's been tested same way as today. If you have any idea what can play role here. Why it is different in personal instance and instance we need to use it. Why it doesn't work in soma cases?

**Comment by arnoudkooi** [comment]
No idea... ill leave it open a few dates if you have an update
