### ISSUE TITLE
Ability to Open Scheduled Job in VS Code Missing

### ISSUE THREAD

**Issue by V1tamnT** [arnoudkooi/ServiceNow-Utils#189]
After the SNUtils update today (I assume it was today), I no longer have the ability to open a scheduled job script in VS Code. Business Rules still appear to work, as well as Script Includes, and UI Actions (this is all I've tested).

I don't see any updates for the sn-scriptsync VS Code extension.

Instance is Rome Patch 7.

**Comment by arnoudkooi** [comment]
Thanks, shoudl be fixed again in the next release. Removed a bit to much code...

**Comment by V1tamnT** [comment]
Awesome. Do you have an ETA on the release? It's probably a nod to the work you've done, but it's actually become extremely difficult for me and my workflow to have to edit code in the SN editor. I'm literally less efficient without this.

Great work here....and sorry for posting this issue in the wrong repo. I was looking for sn-sciptsync changes and just forgot to switch back.

**Comment by arnoudkooi** [comment]
Haha, great to hear to be honest. 
I'll let you know when available. In the meantime a workaround would be to excute below code in console or Javascript Executor:
`snuPostToScriptSync('script')` (replace `script` with the fieldname)

**Comment by arnoudkooi** [comment]
Should now be fixed if you have 5.6.0.0

**Comment by V1tamnT** [comment]
I can confirm this is fixed. Thanks for the quick turnaround!
