### ISSUE TITLE
Questions surrounding your "Interactive Filter OR Condition" work

### ISSUE THREAD

**Issue by baxte1nj** [arnoudkooi/ServiceNow-Utils#19]
[InteractiveORFilterWorkaround.txt](https://github.com/arnoudkooi/ServiceNow-Utils/files/2640595/InteractiveORFilterWorkaround.txt)

I have recently come across your video highlighting your workaround for utilizing an "OR" search using Interactive filters here: https://www.youtube.com/watch?v=rgxuR1nlOJU

I was wondering if you would be able to elaborate on the rest of what is needed for the configuration, I am trying to replicate this to use in a report to show assets that are either "assigned to" or "reserved for" a specific user. 

I have attached my modified version of your script in an attempt to fit this use case. If you have time, any help would be greatly appreciated.

**Comment by arnoudkooi** [comment]
Hi, when I have time Ill look into this, as this is not related to the extension, Ill close this issue

**Comment by baxte1nj** [comment]
Sounds good, thank you for the response I wasn't where best to log this question
