### ISSUE TITLE
Switch application (\sa) does not work when Next Experience UI is active

### ISSUE THREAD

**Issue by shayanlinux** [arnoudkooi/ServiceNow-Utils#191]
When Next Experience UI is enabled (`glide.ui.polaris.experience = true`) the Switch Application (`\sa`) does not work. The page reloads but the current application is kept.

**Comment by arnoudkooi** [comment]
Confirmed, I will look (further) into it

**Comment by arnoudkooi** [comment]
Removed `X-WantSessionNotificationMessages` request header and changed to use fetch API.
Will update issue when new version is published

**Comment by arnoudkooi** [comment]
The update is now published. Please check if it works as expected now?

**Comment by shayanlinux** [comment]
> The update is now published. Please check if it works as expected now?

Thank you. I have tested with SN Utils 5.6.2.3 and a couple of instances but it still does not switch the application (but the page reloads). How can I debug or provide more information?

**Comment by arnoudkooi** [comment]
Strange, but indeed...
Im comparing the calls to `/api/now/ui/concoursepicker/application` in browser console and they are nearly identical (/sa vs native application switching)

Will look further...

**Comment by arnoudkooi** [comment]
That seemed to do it @ovarn, thx. Will notify when this is published (may take a few days)

**Comment by arnoudkooi** [comment]
Fix is now published, version 5.6.3.0

**Comment by arnoudkooi** [comment]
Closing, should work ok again. If not, please let me know!
