### ISSUE TITLE
Slashcommand viewing a Database View does not allow Preview (Inline Search)

### ISSUE THREAD

**Issue by bjamn** [arnoudkooi/ServiceNow-Utils#194]
Hi Arnoud,

I am absolutely in love with this tool. I am equally in awe of your programming skills. I make use of sn-utils every single day.
That said, if I create a Slashcommand  that references a Database View, though the command will produce the correct result on the content area, the preview (dropdown within the sn-utils window) does not happen.

If I am doing something wrong, please feel free to scold me. 

Below is the type of command I am having trouble with:
`u_catalog_variable_list.do?sysparm_query=ritm_cat_item.nameLIKEIndividual Phone^options_item_option_new.question_textLIKE$1^options_valueLIKE$2^ORDERBYritm_number`
![image](https://user-images.githubusercontent.com/57905/159946667-48f98551-8add-44bc-bc60-91754ac2df46.png)

![image](https://user-images.githubusercontent.com/57905/159947005-a14f4b28-c6cc-4c56-bcc0-f8e5710d6e97.png)
This works beautifully with results in the content frame. But I cannot figure out what I am doing wrong for the preview.

Thanks,
Ben

**Comment by arnoudkooi** [comment]
Could it be your missing the table prefixes in your encoded query? 
(and it looks like you have an extra space in your example. )

Can you set it up with an OOB DB View like Incident SLA and share the details here, so that I can replicate?

**Comment by arnoudkooi** [comment]
Besides, please check the browser console, to check for an error

**Comment by bjamn** [comment]
The space shouldn't matter. When I hit enter, you can see that the result came through in the list.
I believe this problem is due to the use of $1 and $2. When I modify the command to use only $0, it returns preview results with no problem.

This is the example using $1 and $2 to return preview results for the Incident SLA database view:
`incident_sla_list.do?sysparm_query=taskslatable_stage=$1^inc_active=true^taskslatable_sla.nameLIKE$2`

**Did NOT return results on preview.**
![image](https://user-images.githubusercontent.com/57905/160288469-fea9e5ba-440e-483f-80f5-0d7e980086a9.png)

**Did return results in list view.**
![image](https://user-images.githubusercontent.com/57905/160288544-9ef28291-e508-4390-8070-aba3e4bf3915.png)

**Now with just $0 in the slashcommand**
`incident_sla_list.do?sysparm_query=taskslatable_stage=completed^inc_active=true^taskslatable_sla.nameLIKE$0`

**Preview works**
![image](https://user-images.githubusercontent.com/57905/160288684-a4848cea-8e61-44ad-afdb-59372657831f.png)

**And list view works**
![image](https://user-images.githubusercontent.com/57905/160288713-b432ad84-d8ab-4a2a-9839-f00d12778388.png)


I really think there is an error in processing the preview when $1 and $2 are used. Or, preview only works when $0 is used.

Thanks,
Ben

**Comment by bjamn** [comment]
> 

database views use the prefix that has been assigned. Like ritm_<field name>, where ritm is the prefix defined for the table.

**Comment by arnoudkooi** [comment]
It was indeed related to the usage of >= $1.
This should be fixed in 5.6.2.3 that is now waiting approval in the Chrome Webstore

**Comment by arnoudkooi** [comment]
The update is now published, can you try?

**Comment by bjamn** [comment]
Works great now. Thanks.
