### ISSUE TITLE
Saving script in Monaco editor

### ISSUE THREAD

**Issue by cnavr** [arnoudkooi/ServiceNow-Utils#195]
New feature, open any ServiseNow script in Monaco editor (which is great :-)), saves the script even with syntax error.
Can you prevent saving such a script (as it is in Servicenow UI)?
Thanks
Ctirad

**Comment by arnoudkooi** [comment]
Could it be your missing the table prefixes in your encoded query?

**Comment by arnoudkooi** [comment]
In cases like this, it would break the workflow, so I'm not sure...

<img width="524" alt="image" src="https://user-images.githubusercontent.com/840781/160065664-0e014a45-8e22-4bd7-9519-2ef0675a159c.png">

**Comment by arnoudkooi** [comment]
I have added a confirm in 5.6.2.3.
This shows a confirm to proceed when the editor has errors.
Besides a confirm to close tab when closing tab when editor dirty is added.

**Comment by arnoudkooi** [comment]
The updates are now published

**Comment by cnavr** [comment]
Hi Arnoud,
I am in FixScript. In line 7 I add a bracket.
In SNOW UI it does not allow me to save it.
[image: image.png]
But when I use Monaco editor, it will save it
[image: image.png]
[image: image.png]

This should not happen
Ctirad

**Comment by arnoudkooi** [comment]
It's better to post on GitHub, rather than replying to email, to prevent extra trail and images are not added.

What is new compared to the old conversation we had about this?
