### ISSUE TITLE
Issue: Monaco editor saving to wrong field on record when multiple editors are open.

### ISSUE THREAD

**Issue by designedbydave** [arnoudkooi/ServiceNow-Utils#197]
While working on a service portal widget, if I open multiple Monaco script editors, it will save over the last opened script field. 

Steps to replicate:
1. Go into a Service Portal Widget record
2. Open Monaco editor for **client controller**, and then open **server script**.
3. Go to Monaco editor with **client controller** code and then _save_.
4. Go back to _record_, and refresh. **Client controller** saved over the **server script**

**Comment by arnoudkooi** [comment]
The data object should be set after the hasloaded check, this is now fixed.

btw:
After the favicon changes, it did not work when [favicon overlays](https://www.youtube.com/watch?v=tm8-63yKmtY&t=2s&ab_channel=ArnoudKooi) are enabled. I allowed image sources from the instance in the manifest file CSP, removing the need to fetch them.

**Comment by arnoudkooi** [comment]
The updated version, including your fixes are now published, please check if it all works!

**Comment by designedbydave** [comment]
@arnoudkooi Everything looks fantastic and working! Saving in scripts in monaco are now getting pushed to the correct field! Thanks so much! Happy to contribute again!
