### ISSUE TITLE
Extend Application Navigator: Autocomplete for technical table names

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#2]
When typing in the Application Navigator and pressing e.g. Ctrl+Space, a Typeahead should appear, suggesting all the available table names. Those could be used from the cached List used in the Tables Menu of ServiceNow Utils.

![image](https://user-images.githubusercontent.com/6060660/40954486-1705ac50-6885-11e8-8497-5811523869ed.png)

**Comment by meinzeugde** [comment]
I actually implemented the basic functionality. There are some bugs i will remove during this week and test a bit more.

![image](https://user-images.githubusercontent.com/6060660/40998289-a98d2396-6907-11e8-8075-9e550ac9ff25.png)

If i finished the implementation, i'll do a pull request.

I did not access the internal local storage. Instead i trigger a REST Call everytime Ctrl+Space is pressed. This Rest Call then is limited to 100 records for now and really only retrieves the technical names, so a load time is basically not present. But also here i need to test different instances.

**Comment by arnoudkooi** [comment]
I actually have a suggestion, instead of shortcut:
Typing when search input has focus:
/ activates your startswith implementation
* activates contains search
. Directly starts the other suffix list, no shortcut
\ disables the typeahead

**Comment by meinzeugde** [comment]
I already tried out the "contains" search. The problem is i need to switch to another Typeahead implementation. This one from Twitter uses Bloodhound for data preparation. Unfortunately Bloodhound misses such "contains" search atm. 

As for the hotkey combination...i wanted to have ctrl+space to not load data anytime someone types. But with more effort some smart recognition could be implemented to automatize this. 

I'd suggest you enjoy your vacation and after that maybe we can do some scoping ;)

**Comment by meinzeugde** [comment]
I'm currently experimenting with other Typeaheads that allow more search patterns. Unfortunately i will not be able to make any progress within the next week/weekend. Please be a bit patient on this...

**Comment by arnoudkooi** [comment]
On mac this appears nit to be worling, Ill look into it

**Comment by meinzeugde** [comment]
OK thanks. I'm a Windows guy ;) So couldn't really test it on Mac.

**Comment by arnoudkooi** [comment]
I have split scripts into inject.js and inject_parent.js
Besides triggering is now via / and . switches to extenion mode.
This needs improvement so is now in beta, and released to the extension.

**Comment by meinzeugde** [comment]
@arnoudkooi 

I tested your changes...

# 1
I did not really see the sense in splitting the inject. I would prefer the old way with only one inject.js. Or is there something i overlooked here?

# 2
Personally i don't like the new behaviour:
* It slows me down when having to press a key to switch, that is not accessible with my left hand
* Autocompletion for me was always like Ctrl+Space (i'm not sure how it is on Mac)
* Besides switching to table mode, the default mode works nonetheless. 

The only advantage i see, it enables the help text in the input field, but maybe we can also make a tooltip or something. But when really working with this, we need to somehow suppress the standard SNOW filtering. Maybe even have the tables shown instead:

![image](https://user-images.githubusercontent.com/6060660/41652224-c207ad20-7482-11e8-9b50-c9d51cfb173e.png)

But i guess that would be not Upgrade-safe, nor easy to implement.

# 3 
Also there are differences between Mac and Windows Keycodes:
* / becomes #
* \ becomes ^
That might also be the reason why the Ctrl+Space didn't work for you, since i did simply not add the Cmd key (i guess it's event.metaKey)

We would need to have a differentation between standardized Mac and multilingual Windows keyboards, so that the keys are the same for all languages. Could you think of a way on how to  do this?

# 4 
Also there is a bug, when switching between default and table mode...it does not reload. This would be an issue i can fix. 

# 5
Let's find an agreement on how to access. Maybe we can also have both solutions ;)

**Comment by meinzeugde** [comment]
Hello,

i had a testing session with a MAC user recently. I can now understand, why you don't like CMD+Space, because it's a hotkey for the global search (is it Alfred?).

On the other hand, the CTRL Key maps to the "OPTIONS" key, which is also kind of unhandy.

I guess i will combine both approaches. I'll start working on it during this week, hopefully i find the time to implement and test properly...

**Comment by shark711** [comment]
This is pretty cool except for the fact that this always pops up, and sometimes when I type the . (DOT) it ignores it, thus if type something like sys_user.list, it ends up typing sys_userlist, and force of habit i press enter, and nothing happens. It seems this only happens every second time I try it, the first time the DOT get's printed out in the navigator.

**Comment by arnoudkooi** [comment]
I'm a bit hesitant to inject new scripts. If you would like, reach out, would be good if we could integrate your features, closing this for now.
