### ISSUE TITLE
Feature Request: enable plugin on custom URLs

### ISSUE THREAD

**Issue by cnavr** [arnoudkooi/ServiceNow-Utils#20]
Hi, 
the plugin is great and I would love to use it also on different ServiceNow URLs than xxxxx.service-now.com. Some ServiceNow instances can have custom URL.
How is it possible to make it work there too?
Thanks
Ctirad

**Comment by arnoudkooi** [comment]
Please search the Chrome store for **SNU OnPrem**

**Comment by cnavr** [comment]
Perfect, thanks a lot.

**Comment by jamiecarpentier** [comment]
Is the SNU OnPrem no longer available?

**Comment by arnoudkooi** [comment]
Here it is: https://chrome.google.com/webstore/detail/sn-utils-onprem/lfabkiipmidkmhplochgpbaeekjjfbch

**Comment by jamiecarpentier** [comment]
Thank you so much. I appreciate the link!
