### ISSUE TITLE
Ctrl+/ and / no longer open slashcommands on FF

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#202]
Seems to be an issue with 5.6.3.0, was working fine before this update. 
No issues with chrome, tested on PDI and work instance
Was also unable to set a custom keyboard shortcut for slash commands, the field would just go blank after clicking update
Using Firefox Dev edition version 99.0b8 
Also tried Firefox stable 98.0.2 and had the same issue

**Comment by arnoudkooi** [comment]
Could you update to 5.6.3.1. 
This is a fix to restore the function in FF. need to look deeper for future manifest v3 compatibility
