### ISSUE TITLE
Support for custom domain names

### ISSUE THREAD

**Issue by peace2000** [arnoudkooi/ServiceNow-Utils#203]
Hi, I'm using ServiceNOW at my work. This addon has some interesting sounding features, but the issue is that I cannot use this because the domain name we are using for our SN is custom made and it doesn't have words `service-now.com` or `servicenowservices.com` as a part of it's name. So any option that would allow me to add custom domain names where this addon would activate, would be great.

**Comment by arnoudkooi** [comment]
I had a few similar Issue's so added a remark to thr readme.
Please use the [OnPrem](https://chrome.google.com/webstore/detail/sn-utils-onprem/lfabkiipmidkmhplochgpbaeekjjfbch) version

**Comment by peace2000** [comment]
Hi, thanks!

I was going to ask whether a Firefox-based version would be released or "on prem" and "non-on prem" versions could be merged but it seems they have been asked before as well:

https://github.com/arnoudkooi/ServiceNow-Utils/issues/114

I think merging would be a good idea :)

**Comment by arnoudkooi** [comment]
This is something I May look at as part of the Manifest v3 migration.
