### ISSUE TITLE
unable to add new slash commands

### ISSUE THREAD

**Issue by cnavr** [arnoudkooi/ServiceNow-Utils#204]
Hi Arnoud,
I have many my own custom slashcommands and I experienced (already several times) that I am not able to add new ones.
Sometimes when I delete some unnecessary ones, I am able to add a new one. However, this does not work always.
Finally, I decided to ask you for help. Is there any limitation for the number of custom slashcommands?
Any suggestion?
After pressing "Save" button it will appear as a new slash command in the window , but it will not be saved.
![image](https://user-images.githubusercontent.com/19973589/162743892-04031eaa-ccbb-4d65-a53e-30456c63795f.png)

Thanks
Ctirad

**Comment by arnoudkooi** [comment]
It seems you may be right... Slashcommands use the [sync storage](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) I see each entry is limited to 8192 bytes.
I'll see if I can make a change so that it uses local storage when it exceeds this limitation

**Comment by cnavr** [comment]
This sounds good to me :-)
Hopefully, it will be possible.
Thanks
Ctirad

**Comment by arnoudkooi** [comment]
Please try and test, version 5.6.3.8 (start with a backup to be sure).
It should auto switch to local storage. Note that in that case slashcommands will not sync between browser when logging in to your google account.

**Comment by cnavr** [comment]
Hi Arnoud,
it behaves strangely.
I backed up my 111slash commands but I am not able to restore it.
I copy it from my backed up file to "Slash Commands" window in Settings
tab, but it disappears when I go to Slashcommands tab and back.

[image: image.png]

regards
Ctirad

**Comment by cnavr** [comment]
Yes,
it works perfectly.
Thanks Arnoud
Ctirad
