### ISSUE TITLE
Wrong property name

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#205]
Missing letter _l_ in the _location_ property:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/45aac91a40600f7b0621947b50a8d34e18ce6ae5/content_script_parent.js#L111

**Comment by arnoudkooi** [comment]
Thank you 👌, you checked the commit?

**Comment by ovarn** [comment]
Yes, sometimes I go through the new commits.
