### ISSUE TITLE
traverse script's history like githistory.xyz 

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#209]
I'm not sure how this would be possible but I'm here revewing a script include looking at a tiny code comparer servicenow gives me and I want a whole page compare where I can see the differences much clearer. 

I don't know the best way to solve this but it would be really cool if the extension could w/a slash command or preferably a button let me see the changes over its versions in a better UI

Here's an exampe of how githistory.xyz(source<https://github.com/pomber/git-history>) shows this(use left arrow and right to navigate)
https://githistory.xyz/jacebenson/jace.pro/blob/master/.eleventy.js

Here's how github presents it.  
![image](https://user-images.githubusercontent.com/638764/163604193-886a4931-31ec-40a9-87ce-af819905238c.png)

I know there's ways to do this in vs code, but it would awesome if I could just do it faster and easier with sn-utils.

**Comment by arnoudkooi** [comment]
Isnt [this](https://twitter.com/sn_utils/status/1487116211104239617) sorta what you mean?

**Comment by jacebenson** [comment]
Amazing.
