### ISSUE TITLE
Helper tab in Chrome will no longer display

### ISSUE THREAD

**Issue by kdorking** [arnoudkooi/ServiceNow-Utils#211]
Hi,
yesterday SN Utils was working fine, shutdown my MacBook at the end of the day, restarted today and the Helper tab will not display. 

I have uninstalled and re-installed Chrome extension, now running 5.6.3.8 and still the Helper tab does not display.

Accessing http://localhost:1978/ shows Upgrade required.  Any ideas on why it would have suddenly stopped?

**Comment by arnoudkooi** [comment]
Please try the new version and let me know. [upgrade info](https://twitter.com/sn_utils/status/1142888825011789827)

**Comment by kdorking** [comment]
Thanks, that worked.


Keith

On Apr 18, 2022, at 6:45 AM, arnoudkooi ***@***.******@***.***>> wrote:



Please try the new version and let me know. upgrade info<https://urldefense.com/v3/__https://twitter.com/sn_utils/status/1142888825011789827__;!!BhdT!ll5zIfwjMgx4qevTEqF6GSAtq77BN8hvW-NJF3hapTvzX5J4D3JMwFwdGIkY3zJRDbQ0-GZq2Q0Sy370gdcZhTo$>
