### ISSUE TITLE
No context menu in chrome.

### ISSUE THREAD

**Issue by gawlow** [arnoudkooi/ServiceNow-Utils#216]
Just today the menu on the right click has disappeared.
Is there a new way to enable it?
![image](https://user-images.githubusercontent.com/40031413/165265581-d9fe80a2-6632-4558-a225-55d97fae81c9.png)

**Comment by arnoudkooi** [comment]
Maybe restart the browser, or reinstall if that does not work?

**Comment by gawlow** [comment]
I have updated the extension to version 6.0 and the bug has been fixed for me and my friend also.
