### ISSUE TITLE
vscode background not working

### ISSUE THREAD

**Issue by Huesdon** [arnoudkooi/ServiceNow-Utils#217]
Since the update, just the good ol' white window from before. sadge.

**Comment by arnoudkooi** [comment]
Are you on the OnPrem version
Can you check if you have granted your instance access?
<img width="659" alt="image" src="https://user-images.githubusercontent.com/840781/165358005-ac0ea3c4-8d8b-4a60-ab1b-c329209c9352.png">

**Comment by Huesdon** [comment]
I am on Prem actually. I tried the three 'can read' options, no joy.

**Comment by arnoudkooi** [comment]
Can you join my zoom to to check? https://servicenow.zoom.us/my/arnoudkooi

**Comment by shaydin** [comment]
I'm also experiencing this issue directly after the update. I'm also using OnPrem and have tried setting the site data access to All Sites as well as on just the instance URL with no change.

**Comment by arnoudkooi** [comment]
Thanks, waiting for the fix to be published!
I was hoping it would be faster now that it has switched to Manifest v3, but so far it is not.
Will post an update once it is available.

**Comment by arnoudkooi** [comment]
Version 6.0.0.1 is now available, please upgrade and try

**Comment by shaydin** [comment]
On 6.0.0.1 it appears to be working as expected again. Thank you so much!

**Comment by arnoudkooi** [comment]
Great!

**Comment by Huesdon** [comment]
confirmed working.
