### ISSUE TITLE
[Feature Request]Insert and Stay keyboard shortcut

### ISSUE THREAD

**Issue by Zmud1** [arnoudkooi/ServiceNow-Utils#218]
Hi,
I literally cannot imagine working in SN without the ctrl+s form save. It saves me thousand of hours and unneccesary table usage from moving mouse.
Can something similar be implemented for the Insert and Stay action?
Best regards,
Zmud

**Comment by arnoudkooi** [comment]
Added a fix, which will be part of the next update. 
I'm on a mac, always using the CMD key.
I will update the issue when next update is available.

**Comment by Zmud1** [comment]
I find it incredible that you respond so fast.
Big thanks, can't wait for the update.

**Comment by arnoudkooi** [comment]
@Zmud1 Can you check if it works now? Version 6.0.1.5

**Comment by arnoudkooi** [comment]
Assuming it does..

**Comment by Zmud1** [comment]
@arnoudkooi 
I am very sorry for late response, the message got lost in my mailbox.

Unfortunately doesn't work as expected, at least not for UI Policy Actions. It doesn't copy the referenced UI Policy. Please, see screenshot.
![image](https://user-images.githubusercontent.com/43832632/166687124-e62a660f-22ec-4a2b-885a-28e585197a0d.png)

**Comment by ovarn** [comment]
I will provide PR with a fix in a few minutes.

**Comment by arnoudkooi** [comment]
I get `Unable to find UI Action with name 'undefined' on table 'sys_user'` when doing a insert on a new record. I think Ill revert the last change

**Comment by ovarn** [comment]
Seems like the a record has no `sysverb_insert_and_stay` UI action
![image](https://user-images.githubusercontent.com/26461232/167006162-9e33cf9c-a5ae-4b53-9b40-3b30c067b385.png)

**Comment by ovarn** [comment]
I think this change can solve the issue:
![image](https://user-images.githubusercontent.com/26461232/167009496-0969a5e0-0c45-47cd-8a5a-747d8fd13855.png)

**Comment by arnoudkooi** [comment]
I'm afraid again an issue [Twitter](https://twitter.com/kimxx_xx/status/1523573592360820736)

**Comment by ovarn** [comment]
I have tested quebec, rome and sandiego (polaris) in Chrome and Firefox. Maybe old version?

**Comment by arnoudkooi** [comment]
Latest fixes are now published. Hope the issues are solved.
