### ISSUE TITLE
Shortcut to activate the extension seems not to work

### ISSUE THREAD

**Issue by robertoalvarezalonso** [arnoudkooi/ServiceNow-Utils#219]
It was working fine until a few days ago.

I've tried with two different computers (Mac) and changed the shortcut in case it was used by another extension, but it didn't work either.

**Comment by arnoudkooi** [comment]
Do you mean opening the popup window?

**Comment by robertoalvarezalonso** [comment]
Yeah, exactly that.

![image](https://user-images.githubusercontent.com/81647176/165999944-e625cf82-9370-4440-87e3-9ed0b30308e7.png)

**Comment by arnoudkooi** [comment]
Thanks, this was related to the Manifestv3 upgrade. I will include this in the next update if that is ok. I'll update once published.

**Comment by robertoalvarezalonso** [comment]
Really thanks to you for the great work you are doing with SN Utils!

**Comment by arnoudkooi** [comment]
Also ready to test

**Comment by robertoalvarezalonso** [comment]
Tested and working! Thanks a lot
