### ISSUE TITLE
VS Code sync with Background Script not working

### ISSUE THREAD

**Issue by robertoalvarezalonso** [arnoudkooi/ServiceNow-Utils#220]
As you can see here the sync in VS Code with Background Script doesn't work.

![Apr-29-2022 20-39-26](https://user-images.githubusercontent.com/81647176/166006511-5eb2d481-4756-4897-a711-80c07d98275a.gif)

**Comment by arnoudkooi** [comment]
This needs change, due to the manifest v3 changes.
Are you using it a lot? considering to remove it

**Comment by robertoalvarezalonso** [comment]
I'm kind of a big user of this functionality, especially with [your newest addition](https://twitter.com/sn_utils/status/1505268494929174528), but I can live without it :)

**Comment by arnoudkooi** [comment]
I believe it should work, also try the other BG script improvements.
(Think this would have deserved a bigger version bump ;) )

**Comment by arnoudkooi** [comment]
Version 6.0.1.6 is pending approval, on-prem may take even longer as the previous is still waiting for approval. Firefox is available.

**Comment by arnoudkooi** [comment]
This is now published, please test!

**Comment by robertoalvarezalonso** [comment]
Tested and working, great job!
