### ISSUE TITLE
Automatically showing user data doesn't work when in full UI

### ISSUE THREAD

**Issue by robertoalvarezalonso** [arnoudkooi/ServiceNow-Utils#221]
![Apr-29-2022 21-10-53](https://user-images.githubusercontent.com/81647176/166023884-2288995f-7f57-44ce-bd78-2c6d57cb668b.gif)

**Comment by arnoudkooi** [comment]
Will also be in the next update, thanks, and thanks for the Chrome Webstore review!

**Comment by robertoalvarezalonso** [comment]
Thank you very much Arnoud, not only a great tool but also great support!

**Comment by robertoalvarezalonso** [comment]
Thank you very much Arnoud, not only a great tool but also great support!

**Comment by arnoudkooi** [comment]
Can you check on version 6.0.1.6?

**Comment by robertoalvarezalonso** [comment]
Tested and working perfectly!
