### ISSUE TITLE
Saving form by using Ctrl+S no longer works for Cases (sn_customerservice_case)

### ISSUE THREAD

**Issue by Kolymorph** [arnoudkooi/ServiceNow-Utils#229]
When trying to save a Case record, an error message is shown "Unable to find UI Action with name 'undefined' on table 'sn_customerservice_case'". Tried on 3 different customer instances so it should not be related to customization.

**Comment by ovarn** [comment]
@arnoudkooi We can try to revert changes or mix both approaches
![image](https://user-images.githubusercontent.com/26461232/167402649-6e3d3f95-0c25-494b-a0a0-3f0220ded529.png)

**Comment by arnoudkooi** [comment]
Ok, please do a PR

**Comment by arnoudkooi** [comment]
The new fix is now in the approval queue. Hope this is the final one!

**Comment by arnoudkooi** [comment]
Latest fixes are now published. Hope the issues are solved.
