### ISSUE TITLE
Safari needs newer version / An unsupported manifest_version was specified.

### ISSUE THREAD

**Issue by CritchCode** [arnoudkooi/ServiceNow-Utils#233]
Just updated to v6.0.1.6 via Mac App Store but it was auto-disabled saying it needs a newer version of Safari. I'm running macOS Monterey 12.2.1 and Safari 15.3 (17612.4.9.1.8). When I look at preferences > extensions it says "An unsupported manifest_version was specified." help??

![image](https://user-images.githubusercontent.com/55980966/168071895-10a1738d-4779-49d0-abed-ac683156fa0c.png)

**Comment by CritchCode** [comment]
Ahhhhh sadly not! I had hoped that you were able to maintain support for a couple of recent versions not just the bleeding edge one. I believe I can only get the Safari 15.4 update, if I also update to macOS Monterey 12.3.1.

I'm choosing to hold back on auto updates for a couple months because there's a [well publicised Dropbox incompatibility](https://help.dropbox.com/installs-integrations/desktop/macos-12-monterey-support) with macOS 12.3 which will prevent me from opening my online files directly from inside apps.

As an aside, I noticed that "Apple isn’t forcing the controversial change from Manifest V3" [source](https://www.xda-developers.com/safari-15-4/). I don't suppose there is an option to retain the logic for both with a switch based on version? I can't imagine I'm the only Safari user who isn't able to stay current. There are plenty of MacBooks out there still running Big Sur and Catalina with older Safari versions.

**Comment by CritchCode** [comment]
As an aside, if these are the new norms for compatibility from 6.0.1.6 onwards, you might want to update this to prevent auto updates...

![image](https://user-images.githubusercontent.com/55980966/168129708-b6190033-263d-463d-832b-be918818aed2.png)

Thanks as always for all your hard work

**Comment by CritchCode** [comment]
I'm just looking for a way to rollback to the previous extension version now. If it hadn't offered me the update, I'd still be blissfully ignorant! 😂

**Comment by arnoudkooi** [comment]
Is this an option? https://browserhow.com/how-to-update-safari-without-upgrading-macos/

**Comment by arnoudkooi** [comment]
Please let me know if the Safari only update works. Otherwise, I'll release an update based on v2 again.

**Comment by CritchCode** [comment]
Thanks for coming back to me so quickly Arnoud, especially as you’ve been so busy delivering sessions at K22.

I found that article earlier before coming back to you but sadly I tried the steps and Apple haven’t released Safari 15.4 as a separate download. I tried via both system update and App Store. No joy I’m afraid.

**Comment by arnoudkooi** [comment]
Can you try to upgrade to 6.0.28 to see if it works?

**Comment by CritchCode** [comment]
Hey man. Thanks for sorting something out so quickly. I’m away with family for a long weekend without a laptop. I’ll check as soon as I’m back on Tuesday and let you know

**Comment by CritchCode** [comment]
Confirmed. Version 6.0.28 has resolved the issue for me on Safari 15.3. Thanks so much for sorting it so quickly
