### ISSUE TITLE
CTRL+S does not update duration fields

### ISSUE THREAD

**Issue by JanRuza** [arnoudkooi/ServiceNow-Utils#235]
Hello,
We encountered an issue with saving the "Estimation" type field. If we saved using CTRL+S and we still had focus on the field we were updating, the latest value did not get changed. If you click outside of the field to get focus away, it got saved correctly, but the edited duration field with active focus does not save the last update of the focused field.
In my opinion, a workaround would be to add an action for unfocusing the fields and making the normal action. I also think such a functionality could be used for example in pop up/pop in action, in which you often have to loose focus from field for it to work using keyboard shortcut. I realize it might be better to also add settings to turn this feature on/off, because in case of some shortcuts (e. g. "/") the user might have issues with using it in text fields, but I don't think "CTRL+S" would face such an issue.
Thank you for looking into this, we had some issues with incorrect saves of Workloa estimation in cases.
Kind regards,
Jan Růža (GuideVision)

**Comment by arnoudkooi** [comment]
Lately, there were some CTRL-S issues. Is this on the latest release 6.0.2.8?
What is an OOB table where I can reproduce?

**Comment by JanRuza** [comment]
Hi,
I searched my PDI and I found this field OOTB displayed in "sysrule_escalate_interval" table form. It is working the same way I described from our custom "Duration" fields in our instance, so you can reproduce it there.
Yes, I'm running the latest version 6.0.2.8.

**Comment by arnoudkooi** [comment]
I'll add a blur for the CTRL-S function. 
For the pop function, you can assign a dedicated shortcut in extension settings, see my recent cheatsheet.

**Comment by arnoudkooi** [comment]
@JanRuza the update CTRL S update is now published, please check if it works now

**Comment by JanRuza** [comment]
Hi Arnaud,

Thank you, I tested your fix on version 6.0.4.3 and it works great.

I was communicating with a colleague, who has a Mac and Safari browser and he didn't get the new update from app store on MacOS.
Could you please check the versions for other browsers? For Google Chrome it works great.

Thank you!


Jan Růža

Junior ServiceNow Technical Consultant at GuideVision - an Infosys company

–––––––––––––––––––––––––––––––––––––––––––-–––––––––––––––––––––––––––––––



A: Türkova 2319/5b 149 00 Prague 4, Czech Republic

W: www.guidevision.eu<http://www.guidevision.eu>



[cid:3198c2a8-9aca-4fac-a6d4-b3b7d7a46126]



This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to

whom they are addressed. If you have received this email in error, please notify the system manager. This message

contains confidential information and is intended only for the individual named. If you are not the named addressee, you

should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received

this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that

disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

________________________________
Od: arnoudkooi ***@***.***>
Odesláno: úterý 24. května 2022 12:54
Komu: arnoudkooi/ServiceNow-Utils ***@***.***>
Kopie: Jan Růža ***@***.***>; Mention ***@***.***>
Předmět: Re: [arnoudkooi/ServiceNow-Utils] CTRL+S does not update duration fields (Issue #235)


Closed #235<https://github.com/arnoudkooi/ServiceNow-Utils/issues/235> as completed.
