### ISSUE TITLE
Feature request - Switch Application & Update set simultaneously from a recent history list

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#236]
Working with Workspaces in San Diego has made it more tedious than ever to be constantly switching scopes and update sets in order to keep the updates in the right place. 

E.g. right now i'm having to constantly switch back and forth between SOW - Core, SOW - Incident, SOW - Request, and Global plugins each with their own update sets in them. 

It would be neat if, similar to the `/sa` command, there was something that brought up a recent history list of update sets across scopes, and selecting one would automatically switch me to that scope and update set at the same time

**Comment by arnoudkooi** [comment]
The /sa switches to the last used updateset of the scope you switch to. Does that not cover your use-case?

**Comment by arnoudkooi** [comment]
Happy to discuss ideas further, closing this for now
