### ISSUE TITLE
Watch Field removes related lists such as Approvers form the form

### ISSUE THREAD

**Issue by mikeymikens** [arnoudkooi/ServiceNow-Utils#237]
I was trying to watch what was changing the RITM stage field, but when I watch this, the approvers and other related lists go away. I often cannot right-click again after starting the watch.

**Comment by arnoudkooi** [comment]
Can you give steps to reproduce, not sure what you mean.
btw: watch field is a platform function, not SN Utils

**Comment by mikeymikens** [comment]
No worries then. I thought that was SN Utils. It might have something to do with the ritm stage field itself.

Mike Glaessgen
Pennsylvania Branch IT Operations Manager
(610) 366-9140 x8814<tel:+16103669140,8814>
________________________________
From: arnoudkooi ***@***.***>
Sent: Friday, May 20, 2022 10:23:05 PM
To: arnoudkooi/ServiceNow-Utils ***@***.***>
Cc: Mike Glaessgen ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [arnoudkooi/ServiceNow-Utils] Watch Field removes related lists such as Approvers form the form (Issue #237)


Can you give steps to reproduce, not sure what you mean.
btw: watch field is a platform function, not SN Utils

**Comment by arnoudkooi** [comment]
Ok, no problem!
