### ISSUE TITLE
Feature request - Support for on-prem instances in Firefox Add-On

### ISSUE THREAD

**Issue by jjrde** [arnoudkooi/ServiceNow-Utils#238]
Hi Arnoud - love your addon.
It just so happens that we're hosted on prem and use firefox. If there is already a way to use the firefox extension on prem i'm sorry for opening an issue, but i couldn't find any info on that.

**Comment by arnoudkooi** [comment]
The FF OnPrem version was pulled by FireFox because they did not allow 2 extensions with the same codebase.
I plan to merge the versions when optional host permissions become available in manifest files, but dont have a timeline for that :(

**Comment by jjrde** [comment]
So what i'm getting is that right now you'd have to either leave it to *.servicenow or enable the addon for any and all websites?

Alternatively until they allow 2 extensions / host permissions in manifest files you could link the direct Add-On-Download on github / your homepage.

**Comment by arnoudkooi** [comment]
[Here is the direct download.
](https://github.com/arnoudkooi/snippets/raw/master/onprem-firefox-snutils.xpi)
Note FF has some restrictions on running unsigned add on, so hope it helps

**Comment by jjrde** [comment]
Thanks for the effort, that works flawlessly.
