### ISSUE TITLE
Slash command unresponsive on "Update Personalized list"

### ISSUE THREAD

**Issue by Zorakie** [arnoudkooi/ServiceNow-Utils#239]
Hello,
I would like to bring up one bug I have found. Not critical, but it brings some minor inconvenience when you need that specific feature.

This bug is related to slash commands triggered while Personalize list modal is open.

Behavior:
When you open Personalize list by cog/gear icon and then start typing /, which opens the Slash commands window, sometimes, it bugs out in a way that you cannot write anything else (you type, nothing is written to the slash command console). It also won't react to any clicking to the slash command window, including the red close dot. You need to close the modal and then the slash command window becomes responsive again.

Surprisingly, it won't happen on all lists. For example, for me, e.g. when triggered on Data Source table, it works just fine, but when I do this on the Scheduled jobs table, it bugs out.

Page refresh won't fix the issue.
No SNUtils-related errors/warnings in the browser console.

Browser: Firefox 101.0b8 (64 bits)
SNUtils version: SN Utils 5.2.6.0

Thank you!

**Comment by arnoudkooi** [comment]
I have seen this myself, I see no way to get on top of the modal, anyone else got a suggestion?

**Comment by arnoudkooi** [comment]
Afraid this is a can't fix at the moment...
