### ISSUE TITLE
new option to point the snutils websocket to a new url/port

### ISSUE THREAD

**Issue by gu-does-git** [arnoudkooi/ServiceNow-Utils#240]
Hi Arnoud, could you please add a new option in the settings of snUtils to select an URL/IP to connect instead of always defaulting to wss://127.0.0.1:1978 and wss://127.0.0.1:1977? 
I think the ports aren't a problem, but the URL/IP could be a lifesaver because some of us can't use the same PC to edit code in, if we could do it on different PCS or even do it in a VM environment would be cool.

> im also planning into porting the sn-scriptsync to vim! ([neovim to be specific XD](https://github.com/gu-does-git/vim-sn-scriptsync)) so watch my repo! :D

**Comment by arnoudkooi** [comment]
This would require changing the manifest file leading to an additional permission prompt for every user.
also from a security perspective, I don't want to open this up.
