### ISSUE TITLE
Feature Request: Option to change ScriptSync Port

### ISSUE THREAD

**Issue by gu-does-git** [arnoudkooi/ServiceNow-Utils#241]
Hello,
I need a way to change the ports which as specified in scriptsync.js through scriptsync.html because it's confliting with some services that I have running on my machine :/
On the same note, it's possible to add a way to change the IP/URL aswell? I'm thought about using the snUtils in a laptop and the vscode extension on my PC, so I can use multiple windows/PCs.

I don't think you would have to edit the manifest.json since the changes are in the scriptsync.js and the scriptsync.html respectively, but I don't know for certain.
Also, I don't think you open a security breach by leaving this options since we can freely modify the JS on the console already and only the people that need this would be using it :+1:

**Comment by arnoudkooi** [comment]
During the webstore approval process, I had questions about this from the reviewers. This is what was agreed. 
I'm not going to change this with the risk of getting it revoked.
