### ISSUE TITLE
Duplication in update set list 

### ISSUE THREAD

**Issue by crysallis** [arnoudkooi/ServiceNow-Utils#242]
![image](https://user-images.githubusercontent.com/906727/171503436-ee1c9c82-0e0b-475f-9818-646ee861d71c.png)
See attached image for an example.  I guess the highlighted one is just my current one and the other one is the one found.  When generally looking at the list, this doesn't seem bad... but since updates can have the same name, it would be cool, if this was called out as a duplicate or not listed.  I often look here to see if I've already created an update set for something

**Comment by arnoudkooi** [comment]
Makes sense not to duplicate it. Will be part of the next update. I'll let you know when it becomes available.

**Comment by arnoudkooi** [comment]
Fix is published. Please check
