### ISSUE TITLE
Slashcommands: Using /-r on a list will open a new tab with malformed query

### ISSUE THREAD

**Issue by nicolaiwork** [arnoudkooi/ServiceNow-Utils#243]
When on a list (sys_user) and doing /-r it will open a new tab with the URL <instance_url>/$random.sys_user, it will also load the correct random record in the initial tab. 

https://user-images.githubusercontent.com/23095600/171817850-4fc9e9cb-bb28-4347-b057-93b992880d12.mov

**Comment by arnoudkooi** [comment]
Thank you, just fixed it. I will leave a message when the update is available.

**Comment by arnoudkooi** [comment]
Fix just published, please try...
