### ISSUE TITLE
Slashcommands: /uis search is not finding all results

### ISSUE THREAD

**Issue by nicolaiwork** [arnoudkooi/ServiceNow-Utils#244]
When using the right arrow search in /uis it doesn't show some of the records that I can see are in the table. 

![Screenshot 2022-06-03 at 13 43 58](https://user-images.githubusercontent.com/23095600/171847461-0608600f-a1b8-4c35-88be-7265e5d51273.png)

Edit: I can see that the query is looking for the script_name and not the name property. 
https://github.com/arnoudkooi/ServiceNow-Utils/blob/970fd81f04cdf38498b8d185d7362c3f9d2872c4/inject.js#L263

**Comment by arnoudkooi** [comment]
Thanks, will update this.
You are aware you can create/overwrite your own?

**Comment by nicolaiwork** [comment]
Thank you. 
Yes, I love it!

**Comment by arnoudkooi** [comment]
Fix just published...
