### ISSUE TITLE
Custom shortcut for slashcommands popup not working properly

### ISSUE THREAD

**Issue by matogolf** [arnoudkooi/ServiceNow-Utils#245]
Hi there,

I have similar issue as described in #219 . I am using 6.0.4.9 version on Win11 and Chrome 102.0.5005.63.

I was using custom shortcuts and looks like shortcut for slashcommands popup is not working.

Default shortcut CTRL+/ is working absolutely fine. Also my custom shortcut to show technical names CTRL+Q is fine too.
The issue is with my custom shortcut to show slashcommands popup ALT+Q. This is not working on first try. I have to press it like 2-5 times and only then I can see popup. I tried to switch shortcuts (ALT+Q for tech. names | CTRL+Q show popup) but it was behaving in the same way. Technical names were shown on first try but popup was showing after multiple presses.

The fun part: when popup is shown after multiple tries, once it's closed and then called again, it's shown right on the first try. But when I open another tab or when I am redirected to other instance page etc. it's not working on first try. Quite strange.

For now I have to use CTRL+/ as a workaround but I would like to use one hand instead of two hands on keyboard when triggering popup... you know. 

Thanks for this great extension! Can't imagine working without SN Utils.
-Martin

**Comment by arnoudkooi** [comment]
Are you in a specific UI or just a classic form?

**Comment by matogolf** [comment]
Classic UI16.

**Comment by matogolf** [comment]
I just realized that sometimes even shortcut to show tech. names is also not working on first try on Service Portal.

**Comment by arnoudkooi** [comment]
Not sure how to troubleshoot this. Do you have steps to reproduce? 
Sometimes there is interference with other extensions ie vimium

**Comment by matogolf** [comment]
Yeah it's not very reproducible. I will try to remove/deactivate other extensions and/or look for other browser based changes to fix it. Let's see. I will let you know.

**Comment by arnoudkooi** [comment]
Please check if the fix in 6.0.5.0 works once available. Will update when published

**Comment by matogolf** [comment]
It looks like fixed. Now it's always on first try. So I think we can close this issue. Thanks a lot!

**Comment by arnoudkooi** [comment]
Yes, the update got published this morning. Thanks!
