### ISSUE TITLE
Ghost Browser

### ISSUE THREAD

**Issue by authoratai** [arnoudkooi/ServiceNow-Utils#247]
As a SN consultant, I use [Ghost Browser](https://ghostbrowser.com/) & SN Utils daily.  Lately, as updates have been release for both of Ghost & SN Utils, I have been having issues using SN Utils.  Ghost is similar to Google Chrome but has some very important distinctions that make my life much easier (workspaces & per tab cookie sessions).  I have opened a few support cases with Ghost & they've tried to help me but I'm wondering if you could take a look at Ghost & see if there was something you could do to make SN Utils more compatible with it?

**Comment by authoratai** [comment]
I believe the only issues currently are:

1.	Right-click context menu is missing.
2.	/pop  does not work - all other slash commands are working (or, at least most of them are – I haven’t tested everything)

 

Previously, I’ve experienced these issues (all in the past 2 months):

*	Extension would not load at all
*	None of the slash commands would work
*	Right-click context menu was visible but clicking did not have any affect
*	Many slash commands would not work while others would 
*	Double-click would not expose technical names

 

Any help would be greatly appreciated!

**Comment by arnoudkooi** [comment]
I'm not able to debug the service worker, clicking the link does not open developer tools.
It looks like the Manifest v3 support is not fully in place.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/840781/174366721-314060d8-b925-4412-91a4-280dec83666d.png">


I'm not able to look into it before this is fixed (using the Mac M1 version)

**Comment by authoratai** [comment]
Just realized that:

/code is also not working 

 

From: ***@***.*** ***@***.***> 
Sent: Friday, June 17, 2022 2:31 PM
To: 'arnoudkooi/ServiceNow-Utils' ***@***.***>; 'arnoudkooi/ServiceNow-Utils' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [arnoudkooi/ServiceNow-Utils] Ghost Browser (Issue #247)

 

I believe the only issues currently are:

1.	Right-click context menu is missing.
2.	/pop  does not work - all other slash commands are working (or, at least most of them are – I haven’t tested everything)

 

Previously, I’ve experienced these issues (all in the past 2 months):

*	Extension would not load at all
*	None of the slash commands would work
*	Right-click context menu was visible but clicking did not have any affect
*	Many slash commands would not work while others would 
*	Double-click would not expose technical names

 

Any help would be greatly appreciated!

**Comment by authoratai** [comment]
Ghost Browser has the “Disable Service Workers” setting enabled by default.  
You should be able to turn the setting off.

**Comment by arnoudkooi** [comment]
Looks like enabling Service Workers is the fix your looking for! 
You may also need to restart or reinstall SN Utils to activate the context menus

**Comment by authoratai** [comment]
Thank you so much!

I enabled Service Workers then uninstalled/reinstalled the extension & all is good. 
Have a great weekend!

**Comment by arnoudkooi** [comment]
Perfect!
