### ISSUE TITLE
Double-click to show technical names and true/false variables

### ISSUE THREAD

**Issue by tdeniston** [arnoudkooi/ServiceNow-Utils#249]
The technical names of true/false variables do not appear when double-clicking on a sc_req_item or sc_task form. This might also be the case for other tables that have a variable formatter, but I don't have an example to test with. Here's an example. Note the checkbox does not show a technical name but the date variable below it does: 

<img width="325" alt="image" src="https://user-images.githubusercontent.com/15730875/175940920-55b3c684-0def-460f-b041-237f1ccdd637.png">

**Comment by arnoudkooi** [comment]
Thanks, Think you meant the checkbox variable. This is now fixed.
Will take a few days before it is published, I'll update when available.

**Comment by arnoudkooi** [comment]
The fix is now published. Please check if it works as expected now.

**Comment by tdeniston** [comment]
Looks good! Thanks!

**Comment by arnoudkooi** [comment]
Cool
