### ISSUE TITLE
Get pop-up window with a 1

### ISSUE THREAD

**Issue by CoyoteRay** [arnoudkooi/ServiceNow-Utils#25]
When I select the gear icon I get a pop-up window with a "1" and a yellow triangle.  I am using FireFox.  Reinstalling does not address this issue.   Please help.

**Comment by arnoudkooi** [comment]
Could you post a screenshot?

**Comment by CoyoteRay** [comment]
Screenshot as requested. 

![capture](https://user-images.githubusercontent.com/36230486/52164570-2864a300-26b9-11e9-8059-0a96fe43804f.PNG)

**Comment by arnoudkooi** [comment]
I've removed a debug line in the code. Can you make sure you get version 3.2.1.0 and try again?

**Comment by CoyoteRay** [comment]
Beautiful, works like a charm.  Thank you for the fast fix and great service.

**Comment by arnoudkooi** [comment]
great, thanks for raising the issue and the feedback!
