### ISSUE TITLE
Current extension no longer working in Microsoft Edge

### ISSUE THREAD

**Issue by af7v** [arnoudkooi/ServiceNow-Utils#250]
I am running version 6.0.4.3 of the SN Utils extension from the Microsoft Store. 
This is no longer presenting any data in: 
Microsoft Edge
Version 103.0.1264.37 (Official build) (64-bit)

I have also tried to update the version to 6.0.5.0 from the Chrome Web Store.
![image](https://user-images.githubusercontent.com/68793625/175954146-7f033619-0971-430b-a49c-199678ff33a0.png)

**Comment by arnoudkooi** [comment]
I am not able to replicate, have you tried a reinstall and restart of the browser?

**Comment by arnoudkooi** [comment]
Did you do any of the testing?

**Comment by arnoudkooi** [comment]
Assume its fixed.

**Comment by af7v** [comment]
My apologies, it has been a super chaotic day. I was finally able to test
this afternoon and got the extension working again.
