### ISSUE TITLE
Pop-in / Pop-out doesn't always work

### ISSUE THREAD

**Issue by peace2000** [arnoudkooi/ServiceNow-Utils#253]
![image](https://user-images.githubusercontent.com/17256841/176599729-040de974-de60-41b3-8f01-9a370fa9d7d7.png)

Sometimes that function opens me a blank page with this url: moz-extension://d575e82f-c6bc-4ad8-8fa3-1121dce4a0e9/_generated_background_page.html

I'm running Firefox on-prem, version 5.1.2.3
Firefox is 91.10.0esr (64-bit)

Any ideas about this?

Also, shortcut command Ctrl+2 to popin/popout doesn't work properly, as it always switches to tab number 2 (I have multiple tabs open).

And when I changed shortcut from Ctrl+2 to Ctrl+Y, nothing happens at all when I press Ctrl+Y.

**Comment by arnoudkooi** [comment]
1. Unfortunately Firefox revoked the on-prem version, you are using a very old one.
2. Did you check the browser shortcuts ?
<img width="999" alt="image" src="https://user-images.githubusercontent.com/840781/176609550-1c0ec234-1aa4-4d80-80a1-4fd140920870.png">

**Comment by peace2000** [comment]
Hi, I download newer version of on-prem (v. 6.0.4.3) but now the issue is that it doesn't activate at all for my SN-page. I wonder if 91.10.0esr is compatible with SN Util (v. 6.0.4.3)?..

Yes, I did use extension shortcut page.

**Comment by arnoudkooi** [comment]
Not sure what you mean with 91.10.0esr I uploaded the version in the snippets repo to the current one.

**Comment by peace2000** [comment]
Hi, I meant the version of Firefox.

**Comment by arnoudkooi** [comment]
Maybe try setting the shortcut via extension settings, as shown in my previous shortcut.
And are you able to get on current version of FF?

**Comment by arnoudkooi** [comment]
Any update, As your using an old version of FF Im not sure how to proceed...

**Comment by peace2000** [comment]
Hi, I'll check this on monday.

**Comment by peace2000** [comment]
Updated to the latest esr-version but still doesn't work. I've set popin/popput to activate when I press CTRL + Y (as in the picture) but nothing happens.

**Comment by arnoudkooi** [comment]
It looks like FF does not allow overwriting oob shortcuts. Could you try for example CTRL-SHIFT-Y?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/840781/177171246-71b78fce-3bc8-433e-8b8b-381d320c52d1.png">

**Comment by peace2000** [comment]
It doesn't allow to use CTRL+SHIFT+Y, it just reverts it back to CTRL+Y.

I don't get that red warning at all when I change shortcuts.

**Comment by arnoudkooi** [comment]
Are you managing it via extension shortcuts?
<img width="976" alt="image" src="https://user-images.githubusercontent.com/840781/177272823-1de55789-22c5-4801-84b5-f638932450b4.png">

@wiiaboo I think the options page is no longer needed and I could remove it?

Note that since yesterday the [FF OnPrem is published again](https://addons.mozilla.org/addon/sn-utils-onprem/)

**Comment by wiiaboo** [comment]
> @wiiaboo I think the options page is no longer needed and I could remove it?

@arnoudkooi sure.

**Comment by peace2000** [comment]
> Are you managing it via extension shortcuts? <img alt="image" width="976" src="https://user-images.githubusercontent.com/840781/177272823-1de55789-22c5-4801-84b5-f638932450b4.png">
> 
> @wiiaboo I think the options page is no longer needed and I could remove it?
> 
> Note that since yesterday the [FF OnPrem is published again](https://addons.mozilla.org/addon/sn-utils-onprem/)

Yes, I'm managing through extension shortcuts.

Will Mozilla this time accept Onprem version on their addons store for good or is there a risk of getting removed from there again?

**Comment by peace2000** [comment]
Ok it seems that I used different shorcut page. I used "Preferences" tab to be correct.

I now found the correct extension shortcut page... ctrl + shift + y works.

**Comment by peace2000** [comment]
@arnoudkooi Thanks! Btw do you think that Mozilla allowed Onprem-version for good this time? Is there a risk of it getting removed again?

**Comment by arnoudkooi** [comment]
I hope, but not sure, It may be rejected again...
(this would not affect current installs)

**Comment by peace2000** [comment]
Ok, don't forget to link to to your home page: https://www.arnoudkooi.com/ :)
