### ISSUE TITLE
[Feature request] Setting to prepend /nav_to.do?uri= to the front of all url based slashcommands 

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#255]
Would like the option to have all built-in and custom slashcommands that use a relative url system, e.g. `/ua` > `/sys_ui_action_list.do` which changes the command to be `/nav_to.do?uri=sys_ui_action_list.do` etc. 

I find myself often using ctrl+enter on slashcommands to force open in a new tab. When doing this for any kind of list or form command, it will remove the navigation wrapper. So I often find myself doing the command, then using `/pop` to give myself the nav bar back, which means i have to sit through 2 full form or list loads. 

Or maybe this is done with a flag like `-f` which loads the list with filter only.

**Comment by arnoudkooi** [comment]
I personally prefer the current way.
In the next update a switch will be available -pi (stands for Pop In)
This will open a new tab, in the full UI.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/840781/176639290-7041fce8-d0e0-418d-b1cf-54f76623411c.png">

**Comment by arnoudkooi** [comment]
This is now published, please check..

**Comment by VanWeapon** [comment]
Yep this works, cheers

**Comment by arnoudkooi** [comment]
Good!
