### ISSUE TITLE
On-prem version affects service-now.com

### ISSUE THREAD

**Issue by gawlow** [arnoudkooi/ServiceNow-Utils#256]
Hi,
I had to install on-prem version together with a normal one. That cause issue on normal SN instances as shown below:
![image](https://user-images.githubusercontent.com/40031413/177282344-f02d8f81-4c3b-45e0-8daa-90ffde741b4e.png)

It adds additional buttons under the filter for tables.

I love all the UI elements from SN util and I wouldn't want to disable them all. Is there a way to fix it and still use two versions of SN Util?

**Comment by arnoudkooi** [comment]
I recommend, either only using the OnPrem, or disable the on-prem version by default and only allowing on specific domains
See this tweet.

https://twitter.com/sn_utils/status/1518987232564154369

**Comment by gawlow** [comment]
Thank you! That worked great.
