### ISSUE TITLE
Disable Show technical names by double-click?

### ISSUE THREAD

**Issue by peace2000** [arnoudkooi/ServiceNow-Utils#257]
Hi, could you consider disabling the showing of technical names by double-click? I find it very easy to make technical names to appear addicentally. Could the showing technical names by double-click be an option in the settings that's disabled by default? 

(Just like "Show technical names on page load" is.)

**Comment by arnoudkooi** [comment]
Doubleclick again to hide...
I don't want to overwhelm users with a ton of settings

**Comment by VanWeapon** [comment]
I double-click to highlight text for copying because it causes your cursor to highlight full words, so I would also prefer an option to turn it off and use `/tn` or a hotkey instead

**Comment by VanWeapon** [comment]
Yeah, if the cursor is outside the input when the mouse button is released it seems to trigger it
https://gyazo.com/93547c5f0480e78e03142790b1a9273e

**Comment by arnoudkooi** [comment]
That gif makes me dizzy ;)
I don't understand your description and am not able to replicate it...

**Comment by VanWeapon** [comment]
double-click and drag on text inside of a string field, then release the left mouse button while the cursor is outside of the input field, and you will trigger the technical names to show.

**Comment by arnoudkooi** [comment]
I see. But it also selects other words in the input when doing that.
How would you use this in your daily workflow?

**Comment by arnoudkooi** [comment]
That's not implemented as stated in [this tweet](https://twitter.com/sn_utils/status/1483887675098734602) when announced, I may look to add that.

**Comment by peace2000** [comment]
> That's not implemented as stated in [this tweet](https://twitter.com/sn_utils/status/1483887675098734602) when announced, I may look to add that.

I don't understand. Technical names in boxes appear if SN Utils is activated and I double-click the whitespace.

**Comment by peace2000** [comment]
All right, thank you for your time. I'll come back to this if I find an instance where it's too easy to accidentally double-click them visible.

**Comment by peace2000** [comment]
Sorry to come back to this, but I still think that accidental doubleclicking is still too common. When I handle tickets I sometimes want to copy texts in form fields by doubleclicking it (to highlight it) and then clicking "copy". I sometimes miss the target when in a hurry, and I accidentally doubleclick empty space and technical names appear then.

I recommended this addon to several my colleagues. One of them asked me about "strange texts" that randomly appear on tickets (he referred to technical names). He also accidentally doubleclicks spaces often, and technical names appear to him by accident as well.

We are both so-called "process-users". I think that technical names is something that SN-Admins might want to see, but for process-users I think that they are not important.

@arnoudkooi

**Comment by peace2000** [comment]
In case someone is reading this and thinking this same, it's possible to disable showing of technical names by doubleclick by using this rule in uBlock Origin browser extension:

`yourdomainhere.com##+js(aeld, dblclick, sc_editor_label)`

**Comment by abhishikkarmakr** [comment]
can anyone please help 
I want to know how what is the short cut through slash commands for knowing the technical names?
