### ISSUE TITLE
Unable to get sysid from service portal page

### ISSUE THREAD

**Issue by Bruce915** [arnoudkooi/ServiceNow-Utils#258]
Hello, I have created a slash command that will pull the sysid from service portal page and use it to redirect to another page using that sysid. However, I have found that $sysid is always empty when used against a service portal page but works fine on a non-portal page. Is there a way to fix this?

Source URL: 
https://tenant.service-now.com/sp?id=sc_cat_item&sys_id=fd9ec3351b7b49d004fd32a24e4bcbb6

Slash command:
command: ri -- get list of requested items for the catalog item
URL: sc_req_item_list.do?sysparm_query=cat_item=$sysid^ORDERBYDESCopened_at

When I invoke the slash command the resultant URL looks like below and you can see that $sysid is not expanded.
https://tenant.service-now.com/sc_req_item_list.do?sysparm_query=cat_item=$sysid^ORDERBYDESCopened_at

If I invoke the command on a non-SP page like below, the slash command works fine.
https://tenant.service-now.com/sc_cat_item.do?sys_id=fd9ec3351b7b49d004fd32a24e4bcbb6

Thanks! Bruce...

**Comment by arnoudkooi** [comment]
Good point!
I will create an update that (tries to) resolve table name and sys_id on portal and workspace for slashcommands. 
I'll update when available!

**Comment by arnoudkooi** [comment]
can you check version  6.0.7.1?

**Comment by arnoudkooi** [comment]
Have you checked? Assuming it works now...

**Comment by Bruce915** [comment]
HI @arnoudkooi , I tested using the Chrome extension (Edge store was not updated yet) and was able to retrieve the $sysid for a service portal and non-service portal page! Thanks so much for the change! This really helps with my workflows.

Bruce...

**Comment by arnoudkooi** [comment]
Good, yes, the Edge approval, unfortunately, takes a week on average. 
You could consider running the Chrome Store version one on Edge or be patient :)
