### ISSUE TITLE
Update set hover-over spelling

### ISSUE THREAD

**Issue by wilsmi** [arnoudkooi/ServiceNow-Utils#26]
When hovering over the _Set current update set_ button in the **Update Set tab** there is a typo on the hover-over.

<img width="796" alt="screen shot 2019-02-05 at 10 26 28 am" src="https://user-images.githubusercontent.com/884828/52283580-bac2ac00-2930-11e9-8c17-f00fd00a1e25.png">

**Comment by arnoudkooi** [comment]
Thanks, updated it, will be changed in the next update.
