### ISSUE TITLE
Next UI Update set/application picker with domain separation

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#260]
This is a very minor thing, but with dom sep enabled, and having the Next UI update set picker setting turned on you get 3 labels for Domain, Application and Update set, and clicking on them brings up the picker for you to switch. 
I've found that sometimes the Update Set label doesn't render as a button, and the domain and application buttons are off by 1, so clicking on the Domain label will open the application switcher, and clicking the application label will open the update set switcher. (ref screenshot)

This happens intermittently, I can replicate it by opening a fresh tab to the instance homepage after closing all other SN tabs, but if I use the picker to change domain or scope, then the page will refresh and all 3 buttons appear to work fine for that tab. Sometimes opening new tabs from here works fine, and sometimes only 2 buttons work. 

![image](https://user-images.githubusercontent.com/30616047/178171881-111c2cfd-029b-4b52-9097-387901ef1202.png)

**Comment by tdeniston** [comment]
The same thing happens if an encryption context is assigned to the admin user.

**Comment by arnoudkooi** [comment]
> The same thing happens if an encryption context is assigned to the admin user.

What do you mean?

**Comment by tdeniston** [comment]
> 

If the user has an encryption context, it shows up below the Update Set picker: 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/15730875/178536814-c0de6bf4-91fd-4bbd-9247-9e395d98fede.png">

Clicking the Update Set link will display the Application Scope, clicking the Encryption Context will display the Update Set picker. Here's a screenshot where I have selected the Encryption Context link, but it's displaying the Update Set picker: 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/15730875/178537571-45fd34a1-5588-4534-9654-e688161319af.png">

**Comment by arnoudkooi** [comment]
ok, didnt know that was a thing, is there a selection menu, just like ie. updatesets for the crypto module?

**Comment by arnoudkooi** [comment]
@VanWeapon  This should be fixed in the update 6.0.7.3.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/840781/178851644-40f9bf5d-4ca9-4efe-b5a2-3d849c497dd1.png">

@tdeniston Can you share more details, does Crypto context have a similar menu?

**Comment by arnoudkooi** [comment]
The chrome version is now published. Also includes a change to show the icon instead of a narrow search field

**Comment by tdeniston** [comment]
> 

Here's a video of it happening (with v. 6.0.7.3)

https://user-images.githubusercontent.com/15730875/179021921-1eb0d4d5-9d13-4ad2-9966-2d6f20e146e9.mov

**Comment by arnoudkooi** [comment]
Thanks @tdeniston, could you run this in console, and share the results:
```
querySelectorShadowDom.querySelectorAllDeep('sn-drilldown-list').forEach(c => console.log(c.className))
```

Should be somthing like:
```
application can-animate
update-set can-animate
crypto can-animate
```

@VanWeapon Did you try?

**Comment by tdeniston** [comment]
> Thanks @tdeniston, could you run this in console, and share the results:
> 
> ```
> querySelectorShadowDom.querySelectorAllDeep('sn-drilldown-list').forEach(c => console.log(c.className))
> ```
> 
> Should be somthing like:
> 
> ```
> application can-animate
> update-set can-animate
> crypto can-animate
> ```
> 
> @VanWeapon Did you try?

I got an error:
VM4483:1 Uncaught ReferenceError: querySelectorShadowDom is not defined
    at <anonymous>:1:1

**Comment by tdeniston** [comment]
Once I clicked one of the menus and then ran it, I received this: 

application can-animate
update-set can-animate
encryption-contexts can-animate

**Comment by VanWeapon** [comment]
Yep my issue seems fixed now, cheers

**Comment by arnoudkooi** [comment]
@tdeniston Please check once version 6.0.8.0 is available to you if that fixes the issue

**Comment by arnoudkooi** [comment]
Chrome version is now published

**Comment by adamnewhall** [comment]
FYI- we've just done the early release testing preview upgrade to Utah- and the 'crypto module' line is showing up again for us.  can't remember for sure- but I think I had it before under Tokyo and maybe it went away when I updated to latest version of the extension?  now i'm on 6.3.4.6
![image](https://user-images.githubusercontent.com/73758443/213296411-8dc8eea3-3787-4df0-b204-c125a4aaae8a.png)

**Comment by arnoudkooi** [comment]
I was not aware it didnt work. Al good for now?

**Comment by adamnewhall** [comment]
other than the picker showing for the crypto line- i haven't found anything
else in the utility that's not functioning normally. i'll let you know as
we play with Utah- RTP doesn't give us any release notes or documentation
to know what's changed, at least not yet. :-)
Love the tool- couldn't live without it now!
