### ISSUE TITLE
Suggestion: One-click retrieve Update Set

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#261]
Hi Arnoud,

We had a brief discussion regarding this at the Hague ServiceNow Knowledge 22 and I think also on twitter.

Can we have a one command retrieve? Currently it's a 3 step process where we open Update Sources > Instance > Retrieve Update Sets. Something like /retrieve (from) <dev> will save time? Basically, the retrieve process should start once we hit enter on the slash command.

**Comment by arnoudkooi** [comment]
Hope this helps

**Comment by vedang444** [comment]
Hey Arnoud,
I already have a command for it. But sometimes it takes time for the page to load delepnding on speed / how many update sets are in the list.
It would help if we can **initiate the retrieve** with one command.
