### ISSUE TITLE
Option to turn off encryption for attachments

### ISSUE THREAD

**Issue by Reaver01** [arnoudkooi/ServiceNow-Utils#262]
Since the latest version with the addition of timestamps on images, it seems that if you have an encryption context it will always encrypt the images. The ability to change default behavior to not encrypt would be ideal.

**Comment by arnoudkooi** [comment]
I'm not sure if the recent change is related. It's just a different filename...
I don't have an instance with encryption at hand. How would you normally control this?

**Comment by Reaver01** [comment]
After further investigation this seems to be an issue with my instance. Closing. I was going to send a screenshot of the encryption selection for attachments and it's just missing and the instance is randomly deciding when to encrypt attachments or not.
