### ISSUE TITLE
Feature suggestion: add new links to widget context menu

### ISSUE THREAD

**Issue by gu-does-git** [arnoudkooi/ServiceNow-Utils#264]
Hi Arnoud, as a Service Portal developer that has been using your extension for a couple of years I've always missed having the option of opening the widget in the VS Code extension without opening the widget editor, so I think it would help a lot of other developers and in my opinion it's quite simple actually.

My feature suggestion is that you add a new link to the start of the context menu that appears when we CTRL+CLICK the widget in the portal page:
<img width="452" alt="Screen Shot 2022-07-14 at 11 17 51" src="https://user-images.githubusercontent.com/42705462/179005199-3166f2d9-4893-435b-b31d-7e8967e0b1b1.png">

**Comment by arnoudkooi** [comment]
The problem is that I am sending the angular object that is available in the widget editor to VS Code. 
That object is rather complex and not available from the portal page itself...

**Comment by gu-does-git** [comment]
As a suggestion: You could add an link that opens the widget editor, clicks the "Open in VS Code" button and then closes the tab since you need the widget editor page info ;)

**Comment by gu-does-git** [comment]
To id when to do this, you could pass something like a URL Parameter i think

**Comment by arnoudkooi** [comment]
I would've been open if it could be done without the widget editor. This seems too niche, with little time benefit. Appreciate the idea though!
