### ISSUE TITLE
Widget Sync Issue (With FIX)

### ISSUE THREAD

**Issue by lewiswill** [arnoudkooi/ServiceNow-Utils#27]
I have found that if a widget contains the '.' within the name, the extension is unable to push any changes to the instance as the function doing so will error out. I am unsure if this is an issue with the extension on VSC or simply a platform limitation.

Thanks!

**Comment by arnoudkooi** [comment]
is this still an issue?

**Comment by arnoudkooi** [comment]
Believe this is fixed, otherwise let me know.
