### ISSUE TITLE
Show XML is broken on OnPrem (Firefox)

### ISSUE THREAD

**Issue by Jonn3y** [arnoudkooi/ServiceNow-Utils#276]
Plugin Version: latest (6.0.8.0)
Firefox Version: 91.5.1esr (64-Bit) (I dont have rights to update to a newer version)
Installed from: https://addons.mozilla.org/de/firefox/addon/sn-utils-onprem/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search 

Issue: /xml and "Show XML" are broken. They do not show the XML Tags anymore and formatting is broken.
Exactly like in Issue #106 

I unzipped the xpi. Seems like the Manifest file does not contain any excluded domains.

**Comment by arnoudkooi** [comment]
It does have the exclude matches in manifest.json, so not sure what is going on, I'll check.
As a workaround, you can try slashcommand `/xmlsrc`

**Comment by Jonn3y** [comment]
Mine looks like this:
`
{
  "name": "SN Utils OnPrem",
  "short_name": "SN Utils Onprem",
  "description": "ServiceNow Productivity tools. (Personal work, not affiliated to ServiceNow)",
  "author": "Arnoud Kooi / arnoudkooi.com",
  "version": "6.0.8.0",
  "permissions": [
    "activeTab",
    "*://*/*",
    "contextualIdentities",
    "tabs",
    "storage",
    "menus",
    "cookies"
  ],
  "icons": {
    "16": "images/icon16.png",
    "32": "images/icon32.png",
    "48": "images/icon48.png",
    "128": "images/icon128.png"
  },
  "background": {
    "scripts": [
      "js/purify.min.js",
      "js/jquery.min.js",
      "background.js"
    ],
    "persistent": true
  },
  "content_scripts": [
    {
      "matches": [
        "*://*/*"
      ],
      "js": [
        "js/purify.min.js",
        "js/jquery.min.js",
        "js/Tinycon.js",
        "content_script_parent.js",
        "content_script_all_frames.js"
      ],
      "all_frames": true
    }
  ],
  "commands": {
    "_execute_page_action": {
      "suggested_key": {
        "default": "Ctrl+1",
        "mac": "Command+1"
      },
      "description": "Activate Extension"
    },
    "pop": {
      "suggested_key": {
        "default": "Ctrl+2",
        "mac": "Command+2"
      },
      "description": "Pop-In / Pop-Out"
    },
    "show-technical-names": {
      "suggested_key": {
        "default": "Ctrl+3",
        "mac": "Command+3"
      },
      "description": "Show Technical Names"
    },
    "slashcommand-shortcut": {
      "suggested_key": {
        "default": "Ctrl+4",
        "mac": "Command+4"
      },
      "description": "Run /shortcut slashcommand"
    },
    "slashcommand": {
      "description": "Open slashcommand popup"
    }
  },
  "page_action": {
    "default_title": "SN Utils",
    "default_popup": "popup.html",
    "default_icon": {
      "16": "images/icon16.png",
      "32": "images/icon32.png",
      "48": "images/icon48.png",
      "128": "images/icon128.png"
    },
    "show_matches": [
      "*://*/*"
    ]
  },
  "web_accessible_resources": [
    "js/purify.min.js",
    "inject.js",
    "inject_next.js",
    "inject_parent.js",
    "css/*",
    "js/*"
  ],
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "snutilsonprem@arnoudkooi.com"
    }
  }
}
`

**Comment by arnoudkooi** [comment]
I was looking at the wrong file. Version 6.1.0.4 should now be available. Can you check?

**Comment by Jonn3y** [comment]
Works fine. Thank you very much! :)
