### ISSUE TITLE
SN Utils onprem blocks display of Azure DevOps sprint board

### ISSUE THREAD

**Issue by maciejduk** [arnoudkooi/ServiceNow-Utils#278]
Hi,

I am using `Firefox 103.0 (64-bit)` and `SN Utils Onprem 6.1.0.4`

When I open azure devops portal and navigate to Sprint board, this is what I expect to see:
![image](https://user-images.githubusercontent.com/97241456/182151191-d749353c-dc9e-4424-9f75-572cbf882c78.png)

What I see instead is blank page:
![image](https://user-images.githubusercontent.com/97241456/182151287-d915acc9-71b5-4848-92ea-2041b5763d0f.png)

It is sufficient for me to just disable the extensions for the webpage to start working again.

Is there something in the config that I need to amend for this to stop affecting websites other than "ServiceNow" ones?

**Comment by arnoudkooi** [comment]
Chrome has a [feature for that](https://twitter.com/sn_utils/status/1248870425549049857), it seems Firefox has not.
@wiiaboo Any trick you know?

**Comment by wiiaboo** [comment]
Nothing yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1497075

There is a way to instead "optionally" allow all URLs and then ask for individual permission for specific URLs dynamically, but I've not used it anywhere yet:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request

**Comment by arnoudkooi** [comment]
Thanks @wiiaboo 
As a quick fix, I excluded the azure domain in manifest.json. in v 6.1.0.6. Need to look for a better solution.
Do you see a console error coming from inject.js @maciejduk ?

**Comment by maciejduk** [comment]
I no longer have the issue since you've updated the manifest.json. 
I checked the console but can't find anything relevant. I get plenty of warnings but I think they are unrelated?

![image](https://user-images.githubusercontent.com/97241456/182571106-94507dc3-789e-4ff9-9242-402475232bdf.png)

**Comment by arnoudkooi** [comment]
Seem unrelated indeed.
I'll close it for now. 
Feel free to report other sites, if issues occur.
