### ISSUE TITLE
Issue with the popup user_name search function in Chrome (6.1.1.0)

### ISSUE THREAD

**Issue by Markakozza** [arnoudkooi/ServiceNow-Utils#279]
Hello,

Recently my collegues and I have started to experience a bug with the popup search option for users (user_name).
This issue is only present for Chrome (6.1.1.0) and not for Edge (6.1.0.5)

When searching for a user_name, regardless of my input, my own user appears with my own user details.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/111118703/184325370-4664cef3-6160-4557-9bd4-a7eb7453620b.png">

**Comment by arnoudkooi** [comment]
Confirmed. I'll fix this in the next update. I will let you know when available.

**Comment by arnoudkooi** [comment]
Can you confirm it works again?

**Comment by Markakozza** [comment]
I can confirm that it is now working as intended in chrome (6.1.1.0). Thanks!
