### ISSUE TITLE
Mobile Frame Switch

### ISSUE THREAD

**Issue by crysallis** [arnoudkooi/ServiceNow-Utils#28]
Very much like you the frame popup/popout... it would be cool if we could get a mobile pop in and out

add $m.do to switch to mobile view
```
http://instance.service-now.com/$m.do
```
add ?sysparm_device=doctype to switch back
```
http://instance.service-now.com/?sysparm_device=doctype
```

**Comment by arnoudkooi** [comment]
I think native mobile is the way forward, so closing this one.
