### ISSUE TITLE
/app slashcommand is broken

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#284]
Steps to reproduce:
1. Open the shashcommand popup
2. Type `/app global`
3. Click Enter
4. See the broken filter
![image](https://user-images.githubusercontent.com/26461232/185115655-97fcaf10-dd62-4a55-ba7c-111dba3fbd70.png)

**Comment by arnoudkooi** [comment]
How did that one sneak in 🤔. Thanks for fixing!
