### ISSUE TITLE
Added new slash command and suddenly all slash commands stopped working (not triggering on "/")

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#287]
Hi,

I'm not saying the slash-command had anything to do with it not working, but that's just the order of events.
I added the command on Chrome and suddenly I can't use slash commands anymore. Just for the sake of it I removed the command but it's still not working.

I logged on using my other Laptop (which has Chrome synced) and it was working for sometime, but then stopped working there as well.

So far it's still working with Firefox, where I haven't made any more changes.

Would love any help. After years of using slash commands, suddenly feeling very handicapped.

Thanks.
All the basic settings are enabled.
![image](https://user-images.githubusercontent.com/6163219/185408722-c10ebd1b-2047-4cfe-a708-7c9b1ee7624f.png)

**Comment by wiresgit** [comment]
I have the same Issue.
Dev Tools showing following JavaScript Error:
`Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at snuSettingsAdded (inject.js:1301:36)
    at <anonymous>:1:3164
    at HTMLDocument.<anonymous> (inject.js:4332:53)`

Hope this helps

**Comment by arnoudkooi** [comment]
Could one of you check in console the value of `snusettings.slashsswitches`

**Comment by wiresgit** [comment]
Hi Arnoud,

the value seems to be empty.

**Comment by arnoudkooi** [comment]
I have found the issue. Expect the Chrome update in one or two days.

**As a temporary fix you can set the value of the _Advanced custom switches_ field to `{}`**
The field is found in the settings tab, double-click it before editing.
After setting it, refresh the browser to take effect.

Sorry for the inconvenience and let me know if it works!

<img width="422" alt="image" src="https://user-images.githubusercontent.com/840781/185430019-ceea6011-444e-41a0-9e18-4154003c7f69.png">

**Comment by vedang444** [comment]
Hey Arnoud,

Thanks for the workaround. Working well now.

**Comment by RickSeiden** [comment]
Hello,

The workaround that you gave is only available to pro users.  Do you have anything that will work for the free users?

**Comment by wiresgit** [comment]
You can become a pro user the moment you double tap the field 😉

**Comment by RickSeiden** [comment]
Thanks, wiregit.  I see "pro" on a free product and just go for the "paid" meaning of "pro"!  And thanks arnoudkooi for everything!

**Comment by arnoudkooi** [comment]
In this case, it was referring to folks who know what they are doing. ;)

<img width="504" alt="image" src="https://user-images.githubusercontent.com/840781/185618095-ab773a84-a111-47fb-bf33-79f4978e8848.png">

Thanks for clarifying @wiresgit I was confused at first :)
I hope the update will be published later today, will update once available.

**Comment by arnoudkooi** [comment]
The update is now published. It should keep working when removing the `{}` from the field.
If someone can confirm, I'll close the issue.

**Comment by RickSeiden** [comment]
I've tested it by removing the {} from advanced and adding back two of my slashcommands, and I'm not having any problems.  Thanks!
