### ISSUE TITLE
$table in Slashcommands doesn't return table

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#288]
Hi Arnoud,

There is a fair chance that I'm using this incorrectly.

This command (/scat) is supposed to search for Catalog Items / Order Guides and open them in the portal.
Ideally, I thought the **$table** would return **sc_cat_item** for Catalog Items and **sc_cat_item_guide** for Order Guides and open it correctly.
But the URL itself returns $table rather than the table name.

**URL:** `sc_cat_item_list.do?sysparm_query=nameLIKE$0^ORDERBYDESCsys_updated_on`
**Overwrite URL**: `/sp?id=$table&sys_id=$sysid`
![image](https://user-images.githubusercontent.com/6163219/185564819-15d60093-c6bf-468d-b808-97c89fe06a97.png)

The **sys_class_name** returns the display name rather than the technical name so I wasn't able to use that.

Can you help in case I'm doing something wrong.

Thanks.

**Comment by arnoudkooi** [comment]
It seems you always want need `sc_cat_item` so just put that in instead of `$table`?

**Comment by vedang444** [comment]
Actually, for Order Guides, it needs to be sc_cat_item_guide or it won't open correctly.

**Comment by arnoudkooi** [comment]
There are a lot of classes, there are a lot of classes, so that doesn't seem to work either...

<img width="490" alt="image" src="https://user-images.githubusercontent.com/840781/185573455-1cb62229-02c7-4263-bfec-a20aaebcdee7.png">

**Comment by vedang444** [comment]
Right. So I thought $table was supposed to fetch the table name and use it in the URL.
But it just returns '$table',
eg. /sp?id=**_$table_**&sys_id=b699dfa1db220740gyc8f56dae9619a2

If not this, then what is the correct usage of $table while overwriting URL?

**Comment by arnoudkooi** [comment]
$table is not resolved in the overwrite URL field at the moment. I may look at adding that.

However, it would not solve the problem for this usecase, ie for a record producer (sc_cat_item_producer) it would not generate a working link.

The only workaround that comes to mind is creating 2 commands, 1 that excludes the Order Guidse, the other for only the order guides

**Comment by vedang444** [comment]
Ah I see! That helps then since I can stop spending more time on workarounds for it. Hope you can put that in as well.

I understand as a whole it would not have helped. But in my case, since I planned to use the command solely for Catalog Items and Order Guides, it would have still worked.

The trouble with 2 commands is that with so many Items and Guides, I don't always know off the top off my head if what I'm looking for is a Catalog Item or an Order Guide.
For now I'll use my old command which just returns the search results on the portal where I can manually select what I want (and it will open the correct class automatically).
**URL:** `sp?id=search&spa=1&t=sc&q=$0`

Thanks for clearing that out Arnoud!

**Comment by arnoudkooi** [comment]
This is what I see on first /tn trigger or with show tn on page load. Isn't this what is expected?

<img width="734" alt="image" src="https://user-images.githubusercontent.com/840781/185622369-7f28d8bf-715f-4372-bfb2-0504c80ec6d9.png">

**Comment by arnoudkooi** [comment]
Good, I'll keep it in the back of my mind, if I see a solution, will update this one.
