### ISSUE TITLE
cmd+s ignores onSubmit Client Script

### ISSUE THREAD

**Issue by TheCodingSmith** [arnoudkooi/ServiceNow-Utils#29]
I created an onSubmit Client script for validation on a field. If I click save/update on the form it runs the script fine. But if I hit cmd+s to save the form it will ignore the onSubmit. 
In the onSubmit I am using `g_form.getControl` with `.changed` and `.test()`.

**Comment by arnoudkooi** [comment]
Is your UI Action using the sysverb_update or sysverb_insert? could you share the full client script?

**Comment by arnoudkooi** [comment]
Assuming this is fixed as I got no details
