### ISSUE TITLE
/versions for flow designer

### ISSUE THREAD

**Issue by adamnewhall** [arnoudkooi/ServiceNow-Utils#295]
/versions - could be updated to work for flow designer flows as well- mine come up searching for name=null_null.  
Perhaps this applies to other areas of the platform in alternate UI's like flow designer?

**Comment by arnoudkooi** [comment]
Good idea, It will be in the next update (FireFox already published). I also added support for _view data_ via the popup for FD.
I'm gradually adding support for these functions in other UI's feel free to bring them to attention.

**Comment by adamnewhall** [comment]
awesome!  i'm curious- will my current version update automatically, or should I monitor and download- this is honestly the first extension I've cared enough about to wonder....

**Comment by arnoudkooi** [comment]
They update automatically. 
You are on Chrome? You can give it a nudge whit this trick:
https://twitter.com/sn_utils/status/1142888825011789827

I'll update this Issue when it is published. Usually takes up to 2 days.

**Comment by arnoudkooi** [comment]
The version is now available, please check if it works as expected

**Comment by adamnewhall** [comment]
awesome!  works great- thanks!
