### ISSUE TITLE
diff or monaco editor loads after second attempt

### ISSUE THREAD

**Issue by cnavr** [arnoudkooi/ServiceNow-Utils#296]
Hi, 
when I try to open diff.html or  codeeditor.html (first attempt) it opens with an empty page and an error in Chrome console - 
DevTools failed to load source map: Could not load content for chrome-extension://jgaodbdddndbaijmcljdbglhpdhnjobg/js/min-maps/vs/loader.js.map: System error: net::ERR_FILE_NOT_FOUND
(see screenshot)
![image](https://user-images.githubusercontent.com/19973589/188474652-7394d79c-c634-443d-abe2-1d5d5f5dfce6.png)
![Screenshot 2022-09-05 165212](https://user-images.githubusercontent.com/19973589/188475902-b7ec3253-adb4-42b7-84fc-fb81fa307a1e.png)
it works when I try to open diff.html or codeeditor.html second attempt.
Any idea how to make it work in the first attempt?
Ctirad

**Comment by arnoudkooi** [comment]
That is an warning not an error, and is related to how Chrome Extensions (not) handle .map files in general. 
Are you opening them direct? this should be done via slashcommand.

**Comment by cnavr** [comment]
I am opening it from compare files
![image](https://user-images.githubusercontent.com/19973589/188575666-2b86637a-61ee-4b23-86d7-e82a117db6bc.png)


When I click it first time, it doesnot work but it is OK when I click it second time.
Any suggestion, how I can troubleshoot?
Ctirad

**Comment by arnoudkooi** [comment]
I will add a bit more delay between opening the tab and passing in the data. I'll let you know once it is published.

**Comment by arnoudkooi** [comment]
Can you try in 6.1.4.0? Should now be available.

**Comment by cnavr** [comment]
Unfortunately,
it is still there
by clicking
[image: image.png]
I get an empty window
[image: image.png]
and I am using
[image: image.png]
Ctirad

**Comment by arnoudkooi** [comment]
Your images are not visible.
