### ISSUE TITLE
Favicon badge style is incorrect

### ISSUE THREAD

**Issue by johndahl-now** [arnoudkooi/ServiceNow-Utils#297]
I have setup my favicon badge with 100% width, height, and up to 100% font size, but the text is very small and offset to the left.

Browser: Chrome Version 105.0.5195.102 (Official Build) (x86_64)
Plugin: sn-utils Version 6.1.3.4
Instance Version: San Diego and Tokyo

<img width="91" alt="2022-09-06_sn-utils_icon_issue" src="https://user-images.githubusercontent.com/103326903/188641195-d1908c3d-dfc5-4941-a130-733ff35a72e6.png">

<img width="774" alt="2022-09-06_sn-utils_icon_setting" src="https://user-images.githubusercontent.com/103326903/188641408-ec868170-3bc2-4638-880f-d1bdb3bc9458.png">

**Comment by arnoudkooi** [comment]
I'm not able to reproduce, did you try decreasing the font a bit?
This uses the TinyCon library that is not being updated for long.
I'll see if I can add a "padding-left" option.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/840781/190087774-a1b562eb-282a-4046-932b-356317f4f1dc.png">

**Comment by arnoudkooi** [comment]
It now allows 4 characters, you could maybe try a trailing space or dot as a workaround.

**Comment by johndahl-now** [comment]
@arnoudkooi I apologize, I had notifications disabled. When I initially reported the issue, I had tried different settings and the alignment issue remained. As of now, I am using extension version 6.1.5.0 and Chrome version 105.0.5195.125 (Official Build) (arm64). The badges are working as expected. I believe this issue can be closed. Thank you!
