### ISSUE TITLE
Left clicking on icon in Chrome 73 opens right-click menu

### ISSUE THREAD

**Issue by wilsmi** [arnoudkooi/ServiceNow-Utils#30]
I am experiencing an issue, that started when upgrading to Chrome Version 73.0.3683.86 (Official Build) (64-bit) where when I left-click on the icon to open the utility I get the right-click menu.

Recycling the extension does not resolve the issue. I have attempted to remove and readd the utility from the Chrome store which is the only thing that fixes it temporarily.

This issue was **not** occurring in Chrome 72.

**Comment by arnoudkooi** [comment]
I believe this is a common issue, hope it will be fixed soon... https://bugs.chromium.org/p/chromium/issues/detail?id=944611&can=1&q=component%3APlatform%3EExtensions%20popup&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by arnoudkooi** [comment]
Sometimes you need to close chrome if you face this issue.
