### ISSUE TITLE
[Feature] Update set description column

### ISSUE THREAD

**Issue by wilsmi** [arnoudkooi/ServiceNow-Utils#31]
It would be very helpful to have the update set description as a column to the left of _Action_ in the update set tab of this utility.

Keep up the great work!

**Comment by arnoudkooi** [comment]
That would be inconsistent with the other tabs, what is the idea on this?

**Comment by arnoudkooi** [comment]
ah the description I now understand, will look at it

**Comment by arnoudkooi** [comment]
This is a bit harder as I'm leveraging a built in API that doesnt include description to get the updatesets
