### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by kdorking** [arnoudkooi/ServiceNow-Utils#311]
This problem just started happening.  I get the following authentication error displayed in the helper tab

{"error":{"message":"User Not Authenticated","detail":"Required to provide Auth information"},"status":"failure"}

I can select the 'Link VS Code via sn-scriptsync' link in ServiceNow and I see the scoped application files in VS Code.  When I select any of the files in VS Code I get the above error.  

If I load a script in the Studio and "Send script to VS Code via sn-scriptsync'  the script successfully syncs to VS Code and I can edit the script and successfully save and sync back to ServiceNow.

I have attached the screen shot of the error in the helper tab.
<img width="814" alt="HelperTabError" src="https://user-images.githubusercontent.com/3506637/194553438-2fec7ff9-f24a-41e0-81b4-185c322c38db.png">

I have attached a screenshot of VS Code after the initial sync for the scoped app.
<img width="740" alt="vs-code" src="https://user-images.githubusercontent.com/3506637/194553960-2cc5f80a-3bf8-4930-9a95-f95239cc7e45.png">

Any suggestions on what might be happening and how to fix would be greatly appreciated.

**Comment by arnoudkooi** [comment]
I published a fix, will let you know once available!
Good to someone uses this function :)

**Comment by kdorking** [comment]
Thanks Arnoud.

From: arnoudkooi ***@***.***>
Date: Friday, October 7, 2022 at 6:01 PM
To: arnoudkooi/ServiceNow-Utils ***@***.***>
Cc: DORKING, KEITH ***@***.***>, Author ***@***.***>
Subject: Re: [arnoudkooi/ServiceNow-Utils] Authentication Failure (Issue #311)

I published a fix, will let you know once available!
Good to someone uses this function :)

**Comment by arnoudkooi** [comment]
The approval of the new version is taking very long this time. Hope it will be available early next week.

**Comment by arnoudkooi** [comment]
Version 6.1.5.8 is finally published. Could you update and try?

**Comment by arnoudkooi** [comment]
Hope all is fixed now

**Comment by kdorking** [comment]
Yes,  it is fixed now, thanks.


Regards,
Keith


From: arnoudkooi ***@***.***>
Date: Tuesday, October 25, 2022 at 3:48 AM
To: arnoudkooi/ServiceNow-Utils ***@***.***>
Cc: DORKING, KEITH ***@***.***>, Author ***@***.***>
Subject: Re: [arnoudkooi/ServiceNow-Utils] Authentication Failure (Issue #311)

Hope all is fixed now
