### ISSUE TITLE
Unable to open settings tab

### ISSUE THREAD

**Issue by OdinGitDat** [arnoudkooi/ServiceNow-Utils#312]
I am a new user. The extension is working (including slash-commands), but I am unable to find a way to open the settings popup. It does not show up in my toolbar, nor the overflow menu and neither can I open the popup from about:addons. Is this a bug or am I missing something?

I am using v6.1.5.8 from the Mozilla add-on page.

**Comment by arnoudkooi** [comment]
The extension settings are in the popup. what are you looking for?

**Comment by OdinGitDat** [comment]
I meant the popup itself, I'm unable to find a way to open it. Sorry if I was unclear.

**Comment by arnoudkooi** [comment]
should be in the right side if the address bar in FF when on a ServiceNow instance
<img width="221" alt="image" src="https://user-images.githubusercontent.com/840781/196637502-1165d7ba-f560-4447-910b-e93ba6e5a21e.png">

**Comment by OdinGitDat** [comment]
Ah that's the one place I didn't check. Thanks.
