### ISSUE TITLE
Double clicking on filters in list views no longer allows to edit the encoded query in Tokyo version

### ISSUE THREAD

**Issue by GuillaumeVachonPom** [arnoudkooi/ServiceNow-Utils#316]
Hey! Not sure if this is an intended feature, but I liked to double click on the filter icon in a list view to quickly edit an encoded query and it doesn't seem like it works in SN Tokyo

Thanks

**Comment by arnoudkooi** [comment]
This still works when clicking the breadcrumb area, where exactly are you clicking? can you add a screenshot?

**Comment by GuillaumeVachonPom** [comment]
It used to work when clicking on this, but sorry you're right it does work with the breadcrumbs. Not sure why I didn't try that.
![image](https://user-images.githubusercontent.com/116654236/198102966-1281d7b5-ecdd-41f2-915e-5f801450b29c.png)

Thanks a lot for your answer !

**Comment by arnoudkooi** [comment]
I didn't know that :) The intended way was always the breadcrumb. Hope you can adjust the habit.
