### ISSUE TITLE
'Send Script to VS Code via sn-scriptsync' not working in Studio (Tokyo patch 1a)

### ISSUE THREAD

**Issue by PNapi90** [arnoudkooi/ServiceNow-Utils#319]
Hi there,

I currently face the issue that I cannot sync scripts with VS Code from within Studio. The "floppy disk button" does not respond, e.g., when trying to sync a script include. It is working, however, when I simply try the same thing from the standard ServiceNow UI (e.g. when opening the script include directly on the script include form).

I tried both Chrome and Firefox (current versions), but it is not working. The instance is currently on Tokyo (patch 1a).

**Comment by arnoudkooi** [comment]
I'll look into it.

In the meantime you can maybe try the Link function and open it from VS Code 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/840781/200538728-575efa78-a8e9-407e-a329-4480b610ff56.png">

**Comment by arnoudkooi** [comment]
The Firefox fix is available now, Chrome is pending approval (version 6.3.0.0).
Can you try, and did you try (and were you aware of) the other method I mentioned?

**Comment by PNapi90** [comment]
Yes, I was aware of the method you mentioned. It worked. However, it is just more convenient to simply select the script via studio. Thanks that you were able to fix the problem. I will try it in Firefox.

**Comment by arnoudkooi** [comment]
Can you confirm if it works in 6.3.0.0?

**Comment by PNapi90** [comment]
Hi, yes I can confirm that it works both on Firefox and on Chrome. Thank you very much for your help.
