### ISSUE TITLE
Add Support for Flow Designer Action Script

### ISSUE THREAD

**Issue by mak42** [arnoudkooi/ServiceNow-Utils#32]
It would be really nice if we could add support for scripts in flow designer, would be willing to help if you can help me a little bit with your codebase so I know where to start :) and great extension btw

**Comment by arnoudkooi** [comment]
The way that is setup and Flow Designer actions are saved in ServiceNow makes it a bit complicated.. will see if I can think of a solution

**Comment by arnoudkooi** [comment]
A bit to complicated...

**Comment by arnoudkooi** [comment]
Can you try version 6.0.4.3?
On top of the page of an action there now is a [scriptsync button](https://twitter.com/sn_utils/status/1528586520700981249)
