### ISSUE TITLE
Adding annotations from form layout and form design fail with snutils enabled

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#322]
the other day I was trying to add an annotation to a form from the form layout page in servicenow and when I did it seemed like nothing was being added.
I looked in my console and I was getting an error.

I tried it again but in form designer.  I didn't check for an error.

I thought maybe something isn't handled in snutils causing the error so I disabled the extension and bam, i was able to add the annotation from form layout.

I tested this on a PDI Tokyo Patch 1

**Comment by arnoudkooi** [comment]
I'm not direct able to replicate, you mean from the form designer, like below?
What is the browser you're using?


<img width="1071" alt="image" src="https://user-images.githubusercontent.com/840781/200632548-7fe0f4c8-1bbb-4975-9c37-ae2b8f4bb5c6.png">

**Comment by jacebenson** [comment]
chrome.  i'll add specific repro steps here after work

**Comment by jacebenson** [comment]
Here's a video.  https://youtu.be/RwU8iOdO5R8

**Comment by jacebenson** [comment]
Works fine in form designer.

**Comment by arnoudkooi** [comment]
Thanks for the video. 
The problem occurs when using the filter that is added by the technical names function, can you confirm?
I think the filter removes the event handler but will look into it further.

Only a while back I noticed that the filter was not visible here and added it. 
Apparently, that was for a reason :)

**Comment by jacebenson** [comment]
Confirmed.  If I don't use the filter I can add the annotation.

**Comment by arnoudkooi** [comment]
I have changed the filter and removed an old jQuery plugin.
The new feature sets the display to none for the filtered-out values so that the events and formatting don't break.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/840781/201033814-c82f9905-16a3-4ddf-904e-e3985cb5d560.png">

Will include this in the next update and let you know when available!

**Comment by jacebenson** [comment]
I just tried it again, but I'm still seeing the issue.  Let me know when a new version gets pushed and i'll make sure I check the version,

Today's version: 6.2.1.0

**Comment by arnoudkooi** [comment]
I did not publish jet, I have some other inflight changes.

I do try to keep the[ CHANGELOG.md](/arnoudkooi/ServiceNow-Utils/blob/master/CHANGELOG.md#6213-2022-11-10) up to date since a while, the version with this will be >= 6.2.1.3

Will update this Issue when the Chrome version is available.

**Comment by arnoudkooi** [comment]
Fix is now published..

**Comment by arnoudkooi** [comment]
Assuming it's fixed. Let me know if not
