### ISSUE TITLE
SNUtils onPrem runs on cloud instances

### ISSUE THREAD

**Issue by Zorakie** [arnoudkooi/ServiceNow-Utils#323]
Hello all,
I am a long-time user of standard SNUtils, but now newly I have a need to use onPrem version of SNUtils because one client, introduced custom URLs for their instances (even though they are on the cloud and not onPrem); this means, the standard SNUtils won't get activated on those custom URLs.

The issue is, that the onPrem version does not check if that is a standard URL or not, which means BOTH SNUtils plugins are being activated on STANDARD URLs <instance>.service-now.com, which leads to bad behavior, as those 2 plugins are fighting between each other - 2 examples:
- issues with autoloading of technical names
- issues with enhancing the background script
- (* issue with opening new tabs 2x as both SNUtils reacted, although I cannot remember, where and how I managed to do that in order to reproduce it and share it here)

I have checked the plugins tab in my Firefox and there it does not seem to be an option to restrict the addon only to certain URLs.

Because of that, I would have one question and potentially a request:

Q: Is it "safe" to use onPrem version to ALL instances? So far I tend to believe the features are similar and the onPrem version seems to be working fine, but still, I want to be sure, there are not any hidden issues with it, like some not-so-often-used feature not working, updates for onPrem version not released so often etc., etc.... 
If it is safe, then fine for me, and we can close this thread.

If not, then a request:
Can SNUtils onPrem automatically ignore standard SN URLs? Or maybe better yet, some checkbox, that would give the option to enable/disable onPrem version with standard URLs

Thank you very much!

**Comment by luffy3298** [comment]
I am facing similar issue

**Comment by arnoudkooi** [comment]
I believe running all on the OnPrem version should work, please give that a shot, by disabling the normal version

**Comment by Zorakie** [comment]
Ok, I will try that, and let's see. 

Thank you very much for the confirmation and your support!
