### ISSUE TITLE
Slash command not working : unimp

### ISSUE THREAD

**Issue by luffy3298** [arnoudkooi/ServiceNow-Utils#324]
case 1. I am trying to use /unimp slash command from portal as an end user : unimpersonate **does not work.**

case 2. I am trying to use /unimp slash command from portal as an itil user : unimpersonate works.

**Comment by arnoudkooi** [comment]
I had a similar issue before, but could not replicate.
https://github.com/arnoudkooi/ServiceNow-Utils/issues/79 

Can you share more details abiut the roles of the user, what portal etc.

**Comment by luffy3298** [comment]
1. it is a custom service portal built long back.

2. our end users will have zero roles. not sure why snc_internal role does not exist in our instance

3. our end users are always redirected to this portal as there is a redirection rule when logging in

**Comment by arnoudkooi** [comment]
I do not have an environment to troubleshoot this issue...
Are you able to replicate it on a PDI?

**Comment by luffy3298** [comment]
i am facing this issue in my customer instance. let me check if it happens in my PDI

**Comment by luffy3298** [comment]
closing as i cannot replicated issue on PDI
