### ISSUE TITLE
New nav issue for customer codes with numbers in them

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#326]
This is a very specific issue so I suspect its not a big deal for many customers. 
My company code for custom apps is 'a3' so when I type `x_a3_appname` to start searching for tables in the slashcommands, with the new nav in 6.3 it's bringing up the new nav instead of continuing with table search, so when I type the '3' its selecting the 3rd item in the list
![image](https://user-images.githubusercontent.com/30616047/202319480-af4d0643-af6e-4291-a2d9-2a1afa116939.png)

**Comment by arnoudkooi** [comment]
You could maybe try to disable the function in settings and activate the menu search via the /m command

**Comment by VanWeapon** [comment]
In terms of a fix, it looks like `x_` is transitioning from table/slashcommand search to navigator search, maybe ignoring `x_` pattern would be enough to fix? Don't know if that's intentional from you or not.

I would prefer to keep this on by default as i'm already finding it way better than the platform's navigator. I can work around this by using wildcard searches it's just a change in behaviour for me.

**Comment by VanWeapon** [comment]
Do you mean this setting? 
![image](https://user-images.githubusercontent.com/30616047/202322250-956f5b8b-92be-4c65-b7b7-386fc15dd041.png)

If i disable it, the menu doesn't work the `/m`
![image](https://user-images.githubusercontent.com/30616047/202322273-39500a59-95cc-41d3-8984-c7c2890f9cd4.png)



As an aside i think using the wildcard approach may actually make things faster for me. since i can just type `table_name*` and it goes straight to the table i'm looking for, then `Tab` puts it into the right mode for adding flags and encoded queries. 

![image](https://user-images.githubusercontent.com/30616047/202321987-89c94489-e8cf-48f5-92fe-61c270a77838.png)

**Comment by arnoudkooi** [comment]
Good, the /m indeed didn't work, in the next release, I'll make sure you can always explicitly do a command search with /m even when the setting is turned off. 
I'll update this issue once it is published.

**Comment by arnoudkooi** [comment]
The /m command should now still work in 6.3.0.6 with the setting disabled. Maybe you can give it a try and let me know.

**Comment by VanWeapon** [comment]
Yep that works now.

**Comment by arnoudkooi** [comment]
Good, then ill close this
