### ISSUE TITLE
The menu bar in next experience disappears

### ISSUE THREAD

**Issue by rvgr1** [arnoudkooi/ServiceNow-Utils#328]
![ServiceNow](https://user-images.githubusercontent.com/45483491/203333373-a4933570-af18-449d-983d-94825c59a4ee.png)

Hello,
Since the 6.3.1.2 version, if the menu "All" is pin, is not possible to select the others menus (Favorites, History, Workspaces), the selected menu disappear. The problem is only with "All". If an other menu is pin, that works.

Thanks in advance,
Hervé

**Comment by rvgr1** [comment]
I use Chrome and San Diego version for ServiceNow. If I disabled the plugin, that works.

**Comment by arnoudkooi** [comment]
Would you have a minute to show and troubleshoot?

**Comment by arnoudkooi** [comment]
I can reproduce in an SD instance. Will publish a fix asap

**Comment by rvgr1** [comment]
Thanks a lot :-)

**Comment by arnoudkooi** [comment]
The fix is on the way, sorry for the inconvenience!
In the meantime you could also try via the slash command by starting with favor or hist.

Will let you know when the fix is published.

**Comment by arnoudkooi** [comment]
The update for Chrome 6.3.1.5 is available. (on-prem still pending) 
Can you check its ok now?

**Comment by rvgr1** [comment]
I checked and that works fine
Thanks a lot!
