### ISSUE TITLE
Codesearch opens in wrong enviromnent/session

### ISSUE THREAD

**Issue by agijo** [arnoudkooi/ServiceNow-Utils#333]
Hey,

Thank you for your awesome work.
I use SN Utils OnPrem in combination with Firefox Multi-Account Containers (https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) 

When using Codesearch /code <string> the new windows is sadly always opened in the "default" environment/container instead of the container where it is called from. 
-> In the defailt container i do use different user credentials (non-admin) and code-search is not working then.

Expected: Code-Search window is opened in the same environment as where it is called from

This is just a small issue and does not have high priority for me.
Workaround right now: Moving the code-search tab into the fitting environment 

Greetings!

Edit: Commands like /bgc /tab /u are working as expected and opening new Tabs in the correct environment.

**Comment by arnoudkooi** [comment]
Can you try to update to 6.3.2.2. and try again? I just published a new FireFox version

**Comment by agijo** [comment]
I dont see any 6.3.2.2 for SN Utils OnPrem sadly on the Addon Store. Last OnPrem Version is 6.3.2.0 so far.

**Comment by agijo** [comment]
I saw that you published the OnPrem Version 15 Minutes ago and i can confirm that it works perfectly!
Thanks alot 👍

**Comment by arnoudkooi** [comment]
Indeed, how did you see that :) ?
The stats say it has only about 40 users.
I'm always manually uploading this one after the automated publishing of the normal one. I'm a bit afraid it gets rejected again, because of being a duplicate when auto-publishing it along with the normal version.

Anyway, glad it is fixed now!

**Comment by agijo** [comment]
I did just refresh the page randomly.  
Im sure there are not a lot of people who know about SN Utils OnPrem. At least in my company noone knew before i found out there is a OnPrem Version and shared it :D So a lot of these 40 People might be us :) And we love your work!
