### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mak42** [arnoudkooi/ServiceNow-Utils#34]
I would like to add a dark mode to this extension. I use Dark Reader in Firefox also for Service-Now and the bright Scriptsync Tab drains my eyes. What do you think about adding a dark mode to the extension?

**Comment by arnoudkooi** [comment]
You would build this? How would you implement this?

**Comment by mak42** [comment]
Yes I would build this, just need a little bit of time to get in your project. I would use some CSS Framework which supports themes and then give the user an option to select light or dark.

**Comment by arnoudkooi** [comment]
Closing this for now, please ping me if you would like to discuss
