### ISSUE TITLE
syslog error link script re-runs fully on every loop

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#340]
The set timeout function added here is re-running the full parse every time, which is slowing the page down since it hangs the page for a little bit each time it runs. 

Have done some testing in the console and found that this line: 
https://github.com/arnoudkooi/ServiceNow-Utils/blob/c4b250236840e01dbdd7fc94930a4d0b668b8110/inject.js#L1664

The `:not(snuified)` bit is not working correctly, it should actually be `:not(.snuified)`

After changing this little bit, can see that the function re-runs much quicker since the query returns 0 instead of the full page

### Before: 
![image](https://user-images.githubusercontent.com/30616047/208326878-7de832a8-69d9-4154-abf0-9b1a9e1a5619.png)
![image](https://user-images.githubusercontent.com/30616047/208326881-ae1885ae-5ebb-46fe-b3d5-fbf2e4dd179b.png)

### After: 
![image](https://user-images.githubusercontent.com/30616047/208326847-820ef716-f84d-4cd4-b0f5-ce821e119b48.png)
![image](https://user-images.githubusercontent.com/30616047/208326798-c9989a21-1a0c-40b5-a345-b8b10c184e95.png)

I tried changing the function to async as well to see if that helped, but the page still hangs when processing during the promise so it doesn't really help anything.

**Comment by arnoudkooi** [comment]
Thanks!
