### ISSUE TITLE
the "show created/update info about this record" icon (question mark) conflicts with styling of Analytics Hub search box

### ISSUE THREAD

**Issue by shayanlinux** [arnoudkooi/ServiceNow-Utils#347]
When Polaris is enabled, please go to Performance Analytics -> Analytics Hub. 
Please see the screenshot

![image](https://user-images.githubusercontent.com/2047383/212183256-70711e2a-c5b0-4c76-84b5-8012a96bc569.png)

**Comment by shayanlinux** [comment]
Awesome, thanks a lot

**Comment by arnoudkooi** [comment]
Should be fixed, let me know if you still face the issue.
