### ISSUE TITLE
UI16 - Update Set & Application Picker Not refreshing

### ISSUE THREAD

**Issue by jk1993** [arnoudkooi/ServiceNow-Utils#348]
The "Show (Next UI) or Enhance (UI16) Application and Updateset picker at page load." option is very useful and makes it a lot easier to switch between applications and update sets with the select2 style dropdown.

We are using the UI16 Developer Patch (same people who created Xplore - widens the update set and application pickers so you can actually see the full names and provides a context menu when clicking on the icons to perform common actions such as importing XML). The context menu has a "Refresh" option. This appears to no longer refresh the update set picker or application picker if these have been changed in another tab.

So to reproduce, have two tabs open on the same instance (non-polaris so UI16). Change the application scope on one of the tabs. Click the refresh button in the app picker context menu (UI16 Developer patch required - seems that refresh on either app or update set picker context menu normally refreshes both without the SNUtils option enabled). Notice that nothing is refreshed in the pickers and a page refresh is required to get the scope/update set to sync.

Happy to provide more information if required.

Documentation for UI16 Developer patch is here: https://github.com/sharelogic/UI16-Developer-Patch

**Comment by jk1993** [comment]
Just had a look at the code for the Refresh button and it seems to basically fire off a custom event.
```javascript
    /**
     * Refresh all the developer pickers (Update Set, Application, Domain).
     * This is really handy when you want to be sure you are working in the
     * correct place.
     *
     * @return {undefined}
     */
    function refreshPickers() {
      var injector = angular.element('body').injector();
      try {
        injector.get('snCustomEvent').fire('sn:refresh_update_set');
      } catch (e) {}
      try {
        injector.get('applicationService').getApplicationList();
      } catch (e) {}
      try {
        injector.get('domainService').getDomainList();
      } catch (e) {}
    }
```
I'm guessing that the normal update set picker (or whatever the UI16 developer patch adds) is listening for this event, but that will apply to the original standard <select> element and not to the select2 element initialised by snutils. Hopefully there is some way for snutils to listen to that event and update the list or if the original select box is still hanging around on the DOM maybe just reinitialising select2 against it would be enough

**Comment by arnoudkooi** [comment]
I would suggest you modify the UI Script in your instance.

I have not tested it, but think adding this to the `refreshPickers` function should work.

```javascript
if (window?.snusettings?.s2ify){ //check if sn utils is installed and s2ify setting active
  snuS2Ify(); //toggle S2 off, 
  setTimeout(snuS2Ify,2000); //reinitialize S2's after 2 seconds when functions are (hopefully) finished
}
```
