### ISSUE TITLE
Feature proposal - Form button back to list

### ISSUE THREAD

**Issue by honinoh** [arnoudkooi/ServiceNow-Utils#349]
Hello,

The proposal is to have a button on forms which when clicked brings you to the records list view. In addition:
- Decide whether to open in a new tab or not
- Retains the query if available 

Please find a working example here:
https://github.com/honinoh/ServiceNow-Utils-backtolist

I would love to see this available in your version.

![2023-01-17_16-41-19](https://user-images.githubusercontent.com/78055863/212943076-ea9f4110-fcdc-4400-b3ce-298fc7e0954b.gif)

**Comment by VanWeapon** [comment]
There is a built in slashcommand flag `-l` which does this for you 
When looking at a form, just type  `/-l` to take you to the list view of the table. 

I also made a custom slashcommand that filters to the id of the current record to make the list load faster:

Command: `list`
URL: `/$table_list.do?sysparm_query=sys_id=$sysid`
Hint: go to list view

**Comment by honinoh** [comment]
> Arent most cases covered by the browser back button? I do see some cases of this coming in Handy, but I want to limit the "UI interventions"

The "browser back button" works only if you stay in the same window. 
The proposed solution uses the table name and query in the URL to determine where to go back to.
This helps a lot in cases where
- You receive a link to a record that was opened from a list (as you can use the query again)
- You tend to open records in new tab and for some reason closed/lost the original list with a specific query

I see your point of not cluttering the UI with extra icons. How do you feel about overriding the existing back button on records with the proposed logic?
![image](https://user-images.githubusercontent.com/78055863/213122434-fb69eb09-f528-4c6e-ac65-5c8aa9abc041.png)


> There is a built in slashcommand flag `-l` which does this for you When looking at a form, just type `/-l` to take you to the list view of the table.
> 
> I also made a custom slashcommand that filters to the id of the current record to make the list load faster:
> 
> Command: `list` URL: `/$table_list.do?sysparm_query=sys_id=$sysid` Hint: go to list view

I agree that this is a start and also believe it can be improved upon still.
It started with us implementing on our instance a similar Global UI Action (form context menu, not a button) as the OOTB back button only brings you back to whatever was last opened. Even if it was in a different window.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/78055863/213126364-cc0d3520-5e79-4b8b-9cab-335dcf9b4e2d.png">

**Comment by arnoudkooi** [comment]
Overwriting existing behavior is not what I want to do, as this may introduce unexpected behavior to users.
I may look to add the $encodedquery variable in form view (recently added to list view) so that you can use this in a custom slash command.
