### ISSUE TITLE
[Feature Request] Dynamic slash commands

### ISSUE THREAD

**Issue by dg42xyz** [arnoudkooi/ServiceNow-Utils#35]
The slash command feature is pretty amazing and I've started using it heavily.  One type of command that I've tried (unsuccessfully) to implement is to open the same record that I'm on in a different instance.  For example, if I'm on a business rule in the Production instance, I have tried the below to open the same record in the Development instance:

`dev;'my_dev_instance_url' + window.location.pathname + window.location.search`

This does not work since it seems to interpret the `window.location` parts as strings.  I have also tried prefacing the link with `javascript:`, but that shows a blank screen with the (expected) URL on it.

Could the slash commands be enhanced to enable dynamic evaluation of links like this?

**Comment by arnoudkooi** [comment]
Javascript is not evaluated... 
Would for example` /env instancename` work for you?

**Comment by arnoudkooi** [comment]
It is now implemented in versie 3.4.3.0 with the /env(ironment) command
/env acmedev will open a new tab in that instance trieng to open same page

**Comment by dg42xyz** [comment]
Awesome!  Yeah, I didn't really need the Javascript to be evaluated but I wasn't sure how else this could be implemented.  I just upgraded to v3.4.3.0 and tested it and it works flawlessly.  Thanks again!

**Comment by arnoudkooi** [comment]
FYI. The original requested way is now available via "nested commands" 
ie: dev;//env instancename
https://twitter.com/sn_utils/status/1174825829018324992
