### ISSUE TITLE
"dbl click to view and update filter condition" doesn't work in Next Experience list

### ISSUE THREAD

**Issue by hayo-nl** [arnoudkooi/ServiceNow-Utils#351]
The doubleClickToSetQueryListV2() function looks at the _div.breadcrumb_container_ doubleclick, but in nextUI, the header bar is moved to _div.navbar-header_.

This makes it currently impossible to set a filter on a (V2) list.

**Comment by arnoudkooi** [comment]
Could you elaborate with some screenshots of what the problem is, not able to reproduce

**Comment by hayo-nl** [comment]
When I try to open the filter from a list in UI16, I get a nice prompt:
![image](https://user-images.githubusercontent.com/72748180/214089488-fe0652d1-5b74-484e-8344-efcd0a2e1c4d.png)

When I do the same in nextUI, it doesn't do anything:
![image](https://user-images.githubusercontent.com/72748180/214089661-e930dfc3-5ba8-4049-869f-1139641d9725.png)

It seems to be that the function looks at the class of the parent div:
![image](https://user-images.githubusercontent.com/72748180/214089748-97acdb8f-f34d-4788-9d89-bc21ce5288cd.png)

Which is the breadcrumb_container in UI16:
![image](https://user-images.githubusercontent.com/72748180/214089835-5817bd1c-fa07-4ffb-a8ff-0d147304e251.png)

But the navbar_header in nextUI:
![image](https://user-images.githubusercontent.com/72748180/214089931-128f26ff-c147-412c-96a8-778f044bb1d9.png)

Does this help?

**Comment by arnoudkooi** [comment]
The idea is to double click in the breadcrumb area, not the button...
![Google Chrome20230123 - 1805](https://user-images.githubusercontent.com/840781/214103413-509eed93-23f2-474d-847c-6fef6bb04b63.png)

**Comment by hayo-nl** [comment]
I missed that change. Sorry. Thanks!
