### ISSUE TITLE
Missing link in the View data tab

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#353]
If a referenced record has an empty display value there is no link to such record in the View data tab.

Steps to reproduce:
1. Open any Incident record
2. Fill in the Parent Incident field with some random Incident
3. Save the form
4. Open the selected Parent Incident
5. Clear the Number field
6. Save the form
7. Go back to the Incident record from the first step
8. SN Utils -> View data -> Find the Parent Incident row
9. See that there is no link to the Parent Incident
![2023-01-25_22-05](https://user-images.githubusercontent.com/26461232/214690908-f978db4a-a19a-4077-8a14-466b20c6051a.png)

**Comment by arnoudkooi** [comment]
Thank you

**Comment by arnoudkooi** [comment]
Inspired by this as well as [Maik Skoddow's post](https://www.linkedin.com/posts/maik-skoddow_servicenow-activity-7025349902310211584-lcWU?utm_source=share&utm_medium=member_desktop) I expanded this to the Technical Names function to show a field message. 

![Google Chrome20230129 - 1620](https://user-images.githubusercontent.com/840781/215583038-95822916-d6e5-47c3-8e11-f7c3e4976095.png)
