### ISSUE TITLE
Feature Request - Export List with ALL fields to CSV

### ISSUE THREAD

**Issue by bcftv** [arnoudkooi/ServiceNow-Utils#356]
When viewing a list (with or without a filter), it would be great to have a slash command to export the list to CSV with ALL fields.

This capability is documented at https://john-james-andersen.com/blog/service-now/getting-all-fields-with-csv-export-in-servicenow.html and uses crafted URLs in the format:

https://myinstance.service-now.com/incident.do?CSV&sysparm_default_export_fields=all

If you have a filtered list it's like this:

https://fortive.service-now.com/incident.do?CSV&sysparm_default_export_fields=all&sysparm_query=active=true

Hitting the URL immediately returns a CSV download with all the available columns from the table.

**Comment by arnoudkooi** [comment]
Could you try something like this as a custom slash command:
`/$table.do?CSV&sysparm_default_export_fields=all&sysparm_query=$encodedquery`

I've added better resolving of $encodedquery in the last release.
This is a bit niche, so best suited for a custom slash command.

**Comment by bcftv** [comment]
That worked perfectly - thank you so much!
