### ISSUE TITLE
/diff1 and /diff2 do not load current records

### ISSUE THREAD

**Issue by tomasz-q** [arnoudkooi/ServiceNow-Utils#359]
Steps to reproduce

1. Open any incident record, namely INC00001 in the first browser tab. Make sure left navigation panel is on. Run /diff1
2. Open any incident record, namely INC00002 in the second browser tab. Make sure left navigation panel is on. Run /diff2
3. diff.html loads presenting differences between INC00001 and INC00002
4. Close diff.html.
5. Open INC00003 in the first tab, replacing INC00001. Run /diff1
6. Open INC00004 in the second tab, replacing INC00002. Run /diff2
**Expected behavior**
diff.html loads presenting differences between INC00003 and INC00004
**Actual behavior**
diff.html loads presenting differences between INC00001 and INC00002

Workaround: Ctrl + R in the first and second tab, then /diff1 and /diff2.

SN version: Tokyo
Browsers: FF 109.0.1 / Chrome 110.0.5481.78
SN Utils version: 6.3.5.5

**Comment by arnoudkooi** [comment]
Need some time to checks, is this Next Experience?

**Comment by arnoudkooi** [comment]
Please try if this is fixed in 6.3.5.8

**Comment by tomasz-q** [comment]
The issue no longer present. Thank you!
