### ISSUE TITLE
Show Technical Names does not toggle off

### ISSUE THREAD

**Issue by dg42xyz** [arnoudkooi/ServiceNow-Utils#36]
When using the "Show Technical Names" feature, one used to be able to toggle the technical names on and off.  With the latest release that includes the "??" to the right of the UI actions when Technical Names are displayed, there is no way to toggle the Technical Names off.  Additionally, continually trying to toggle the Technical Names on/off just adds more "??" to the right of the UI actions.

Steps to reproduce:
- Using version 3.4.5 of the SN Utils extension, toggle Technical Names on
- Try to toggle Technical Names off.  Notice they remain on the screen, and UI actions get a duplicate "??" next to them.

**Comment by arnoudkooi** [comment]
There never was a toggle, reloading the page is the way to go (Via SN Utils by double-clicking the header bar). The duplicate ?? is a issue, I will address this weekend.

**Comment by arnoudkooi** [comment]
Fixed ? issue in 3.4.5.1
