### ISSUE TITLE
/m stopped working because my localStorage didnt contain a headerMenuItems entry for my id

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#361]
Okay it took some reading through the source code but I did figure out this one, it was pretty weird though. 

The `/m` feature stopped working for my user account on my work instance, but was still working on my PDI and when i impersonated people. 

After running the debugger I found that `snuGetSlashNavigatorData()` was always returning null, because there was no entry for my id for the `headerMenuItems` key. 

I inspected my localStorage manually and sure enough, there were 6 entries for other users' ids, (likely people i've impersonated in the past) but not for my own.

After deleting all 6 entries and reloading the page, the localStorage was rebuilt and now it contains an entry for my ID.

Interestingly, the platform's menus were working just find for me before and after I deleted the local storage.

I don't know if you want to do anything about this, maybe a `console.error` with a warning to clear out the localStorage entries if `prtl` ends up null? 

https://github.com/arnoudkooi/ServiceNow-Utils/blob/5a16514b62d0c36ca54b5602d6b97bca9fe29157/inject.js#L4478

For reference this happened on Tokyo patch 3

**Comment by arnoudkooi** [comment]
I have seen this as well, let me see if I can add a message
You should btw be able to clear storage with the `/cls` command as well

**Comment by arnoudkooi** [comment]
Not really sure what to do with this one, think the best guidance is to do a /cls and page reload.
Closing it for now, let me know if you have a better suggestion.
