### ISSUE TITLE
/diffenv doesn't work on 3 letter instance names

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#363]
My company's prod instance is 3 letters, so doing diffenv isn't possible to compare dev to prod (tho prod to dev is fine)

Found that `/diffenv` has a check for length of > 3 whereas `/env` has no limitation, can this be updated to `>= 3` instead?
https://github.com/arnoudkooi/ServiceNow-Utils/blob/6afaf090455fde6daf2f4c8d5c93f1bbc2a390b5/inject.js#L878

**Comment by arnoudkooi** [comment]
can you try if it works now?
