### ISSUE TITLE
CTRL-Click on report header occasionally does not work, even with Slashcommands disabled

### ISSUE THREAD

**Issue by rr199227** [arnoudkooi/ServiceNow-Utils#374]
Hi, thanks for the great plugin. Really appreciate all the additional functionality it gives.

My coworker and I have both run across the same issue: periodically a CTRL-Click on a report widget header does not work to open a report in a new tab. Even with Slashcommands disabled, the Slashcommand box will pop up with the message, "Editlink not found. CTRL-Click only works in same scope and as admin"

We've observed that this issue can happen if you try to CTRL-Click while a widget is still loading, which is understandable. However, we have also seen it happen on a fully loaded dashboard. A particular report might not respond to the CTRL-Click, but other reports might still open as expected. There doesn't appear to be any pattern to it.

The CTRL-click won't work for that report until refreshing the browser- that always seems to fix the issue. But sometimes during the same browsing session, the issue will occur again on a different report/dashboard tab. 

Attaching screenshots of the error message and my SN Utils properties. Please let me know if you need additional information.

![image](https://user-images.githubusercontent.com/128098634/225760969-aa94f44b-8802-4df3-81eb-8e03f50ffa0a.png)

![image](https://user-images.githubusercontent.com/128098634/225761071-54af4cdc-3e0b-4fe6-b2fb-ea174e512389.png)

**Comment by arnoudkooi** [comment]
The settings should not influence that. You are in the matching scope, right?

Please set a breakpoint at this line and debug if you can. ie, see what the error message is.
https://github.com/arnoudkooi/ServiceNow-Utils/blob/78bdc0987f75f6b565726cd4392d06cda840cf92/inject.js#L1834

**Comment by arnoudkooi** [comment]
Haven't heard back, please let me know if you still have issues
