### ISSUE TITLE
Node Switching not working?

### ISSUE THREAD

**Issue by kr4uzi** [arnoudkooi/ServiceNow-Utils#376]
Hi, when i use the node switch feature and i do a stats.do afterwards, it still shows the same node as before.
When I go to "Active Transactions (All Nodes)" it also shows the same node I originally had.
Changing the cookie doesn't seem to have any effect anymore...
Can anyone confirm?

**Comment by arnoudkooi** [comment]
Could you try a cache.do and relogin and try again?

**Comment by kr4uzi** [comment]
Yes, cache.do + relogin didn't help.

Switching Nodes works only one time I think. I did the following:

1. log out
2. delete the node cookie BIGipServerpool_XXXXX
3. login again
4. stats.do shows your current node
5. switch nodes using SN Utils
6. stats.do shows the changed node
7. switch nodes again
8. stats.do still shows the same node as in step 6

However this is still fine, i think there is no need to switch nodes multiple times, or at least there is a workaround if you have to.
