### ISSUE TITLE
Switching Node is not working on onPremise instance

### ISSUE THREAD

**Issue by krysbzh** [arnoudkooi/ServiceNow-Utils#377]
Hi Arnoud,
Thanks a lot for you extension 👍 
for me too. I tried on onPremise instance. I use the onPrem version of the plugin (v6.3.9.0).
I have the list of nodes.
When I click on "Set Active" :
1. First console error is related to the authentication :
Error message
`popup.js:1633          GET https://MyInstance/api/now/table/sys_cluster_node_stats?sysparm_query=node_id=2cca88f1825ed1bbfdb6727a1e38e8a2&sysparm_fields=stats 401 (Unauthorized)`

If I try to access to this URL directly, I have an authentication prompt and I put my admin credentials and the error doesn't appear anymore

2. The second console error :
`Error handling response: TypeError: Cannot read properties of undefined (reading 'name')
    at chrome-extension://lfabkiipmidkmhplochgpbaeekjjfbch/popup.js:188:51` 
It is due to the name of my Cookie. The regex is /^(BIGipServerpool_[\w\d]+)$/ but my Cookie name is "BIGipServerSML_pool_pr_ServiceNow"

Did you see this error previously ? 
Is it possible to make switching nodes work on an onPrem instance?

Thanks in advance

Christophe

**Comment by arnoudkooi** [comment]
I dont have access to an onpremise instance, maybe we can schedule some time to troubleshoot next week.

**Comment by krysbzh** [comment]
Good Idea, we can discuss in private via LinkedIn.
Christophe Sancéau

**Comment by arnoudkooi** [comment]
There has been a change in the underlying process, at least for some instances. It should now display a message when the switching can not be completed. I need to look into this further if there is a way to fix it.
