### ISSUE TITLE
Switch `/-l` for list view seems to be broken

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#379]
The command is 
`$table_list.do?sysparm_query=sys_id=$sysid`
However it appears to be doing this:
`$table_list.do?sysparm_query=$table_list.do?sysparm_query=sys_id=$sysid`
causing it to not work
e.g.
![image](https://user-images.githubusercontent.com/30616047/229644093-d0ea5a67-c454-41f1-bc4e-58dd78c277ad.png)

When I look at the source code here it looks right though? 
https://github.com/arnoudkooi/ServiceNow-Utils/blob/cb37873e1d99ef3bfe6269568839d9067e3debcc/inject.js#L340

I tried turning it into a custom switch and got the same result, and i also tried adding `/` at the beginning so it was this
`/$0_list.do?sysparm_query=sys_id=$sysid&sysparm_filter_pinned=true`
but that didn't change anything. 

If i make it into a regular slashcommand e.g. `/list`
And have it set up like below it works fine
![image](https://user-images.githubusercontent.com/30616047/229643951-ed5256b4-92d6-434f-8ade-098759fe8901.png)

Maybe it would be easier to just convert it from a switch to a slashcommand

**Comment by arnoudkooi** [comment]
Agree, I've switched to a slash command and will remove -l
(Note that you can also CTRL/CMD click the grey header to generate a link and click that)

**Comment by arnoudkooi** [comment]
Fixes is now published, hope it works
