### ISSUE TITLE
Showing Technical names, Saving Record shortcuts stopped working in 3.5.6.3

### ISSUE THREAD

**Issue by wiiaboo** [arnoudkooi/ServiceNow-Utils#38]
Browser: Firefox 71.0b8 on macOS 10.14.6
Affected Versions tested: 3.5.7.0, 3.5.6.5, 3.5.6.3
Works again in: 3.5.6.2

Tried both showing technical names using the keyboard shortcut, then thought the shortcuts might be broken, so I tested through the Action Menu (right-click on the page), but it didn't work either.

Saving the record shortcut (cmd+S) didn't work either.

**Comment by arnoudkooi** [comment]
Thanks, a RegEx expression I started using was not supported in FF, in release 3.5.7.1 it should be fixed! Please let me know if it works again!

**Comment by wiiaboo** [comment]
There's a [Bugzilla page](https://bugzil.la/1225665) for this missing regex, for future reference.

**Comment by wiiaboo** [comment]
Yep, it's working again, at least in Windows Firefox.
Thanks!
