### ISSUE TITLE
Broken context menu search

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#380]
Steps to reproduce:
1. Find a system property with a long name (e.g. `com.snc.incident.copy.rl.task_cmdb_ci_services.attributes`) in a code.
2. Select the property name.
3. Click the right mouse button -> SN Utils -> Search / GoTo -> Property.
4. See that nothing happens.

Expected behavior: redirect in the last step.

Root cause:
The max property name length is 100 characters, but the script ignores selected text longer than 50 characters:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/cb37873e1d99ef3bfe6269568839d9067e3debcc/background.js#L806-L808
![Screenshot from 2023-04-05 21-05-12](https://user-images.githubusercontent.com/26461232/230180863-35209f03-8f0b-49cf-826a-b67bc4bc7fa5.png)

**Comment by arnoudkooi** [comment]
Thanks Ivan!
