### ISSUE TITLE
'Technical Names' not working.

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/ServiceNow-Utils#385]
It seems like the 'Technical Names' feature is not working anymore. 

Version: 6.4.0.5 Firefox. 
Instance: Cloud Instance (Tokyo & Utah)

Symptoms: 
- The tecnical names is showing undefined in choice dropdowns like this: 
![state_undef](https://user-images.githubusercontent.com/6660378/231135988-9d12fee8-62bc-4dae-9e4c-9785350bd93d.png)

And for the technical names, there is nothing showing to the right of "Stage" and "State"

**Comment by arnoudkooi** [comment]
Confirmed, Sorry for the inconvenience. The Firefox version 6.4.0.6  should be available, can you update and check?

**Comment by CGraabaek** [comment]
It works again! 
No reason to apologize, I really appreciate the effort you have put into this! 

Thanks for being so fast - that's really amazing.

**Comment by arnoudkooi** [comment]
Fix should be rolled out now
