### ISSUE TITLE
Open reference table list (click) or record (ctrl+click) is not working anymore

### ISSUE THREAD

**Issue by Dnmiro21** [arnoudkooi/ServiceNow-Utils#388]
Functionality stopped working on 

<img width="144" alt="image" src="https://user-images.githubusercontent.com/14157948/231792652-d3c95b59-43c5-4b16-84e9-d9db202dcee2.png">

Version = 6.4.0.7
SN Version = San Diego

**Comment by arnoudkooi** [comment]
Should work again, can you confirm?

**Comment by Dnmiro21** [comment]
I can confirm that this functionality is now working again. Thank you!
