### ISSUE TITLE
SNCA extension corrupted

### ISSUE THREAD

**Issue by Supernorwood** [arnoudkooi/ServiceNow-Utils#389]
Is there a zip file that can be downloaded and unpacked. File was corrupted in workspace and there is restrictions on accessing chrome extension store to redownlaod. Could not repair or update. Had to remove the extension and trying to add it again.

**Comment by arnoudkooi** [comment]
You can download a zip file here, I just updated to the current version:
https://github.com/arnoudkooi/snippets/blob/master/chrome-snutils.zip

**Comment by Supernorwood** [comment]
Yes, it absolutely worked. Thank you so much!Sent from my iPhoneOn Apr 21, 2023, at 11:32 AM, arnoudkooi ***@***.***> wrote:﻿
Did that work? Anything else I can support you with?
