### ISSUE TITLE
Idea: Prepopulate slash commands as editable commands

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#39]
I'm not sure this is a helpful idea but I'll ask.  

Would it be helpful to instead of listing the commands as part of the codebase (uneditable), make them just default slash commands.

A picture might help;

![image](https://user-images.githubusercontent.com/638764/69929320-383d4700-1484-11ea-84fa-0ad60e3fd530.png)

So instead of hardcoding it, somehow use that input to set these up;
https://github.com/arnoudkooi/ServiceNow-Utils/blob/d28ed1fd76a4671fd1954274b22d0acee4329d0b/inject.js#L5

If the settings were stored in this way it could also lead into a way to export the settings in case someone wants to set up other installations of this plugin the same way.

**Comment by jacebenson** [comment]
And now I realize all the commands can be just simply overwritten.  Not sure its worth the time but I'll leave the issue as is.

**Comment by arnoudkooi** [comment]
Thanks, besides the commands that require javascript like /pop, /uh you can overwrite them indeed. I'm thinking of changing this list to datatables. May take a while... I'll leave this open to track.

**Comment by arnoudkooi** [comment]
In 3.7 I have changed this, will be tweaking this a bit, what do you think?
