### ISSUE TITLE
[Feature request] Copy filter breadcrumbs in a human-readable form

### ISSUE THREAD

**Issue by n21lv** [arnoudkooi/ServiceNow-Utils#392]
Currently it is possible to copy/modify the filter query by double-clicking it, which is very handy. However, one thing I often find myself doing is explaining to business stakeholders what are the trigger conditions on certain BRs, visibility conditions for certain UI Actions, filter conditions for ACLs and so on. You can share a screenshot, but it's often not the best way, especially if you need to describe a change.

### Suggestion
Implement a feature that would allow getting the query in a human-readable form. I know that it is achievable from server side by using `new GlideQueryBreadcrumbs().getReadableQuery(<TABLENAME>, <ENCODED_QUERY>)`, but I have no idea if the same is possible from client side.

**Comment by arnoudkooi** [comment]
Would a slashcommand that prefills a script work, something like|:

**Comment by arnoudkooi** [comment]
Would a slash command that prefills a script work? Something like:
Name: qsr
Url:
`/sys.scripts.do?content=gs.info%28GlideQueryBreadcrumbs%28%29.getReadableQuery%28%27$table%27%2C%20%27$encodedquery%27%29%29`
Hint Readable querystring script

**Comment by n21lv** [comment]
Oh, I had no idea you could prefill scripts like that. That would work, yes!

**Comment by arnoudkooi** [comment]
Good, not perfect, but easiest I could think of. Ok to close this one?
