### ISSUE TITLE
[OnPrem] Slashcommands with URL that starts with 'javascript:' do not work outside frameset

### ISSUE THREAD

**Issue by n21lv** [arnoudkooi/ServiceNow-Utils#395]
Chrome 113.0.5672.93 (Official Build) (32-bit) (cohort: Stable)
SN Utils OnPrem 7.0.0.0

I have experienced this while I was trying to create a custom Slashcommand that used a `javascript: <some code>` URL, but after trying to figure out where the issue is I noticed that I have exactly the same issue with built-in Slashcommands like `/debug` or `/um` that use the same type of URL.

This happens both with UI16 and Polaris UI, but only outside of a frameset. I have also tried reproducing this in the regular version, and it doesn't seem to be happening there.

**Steps to reproduce**
1. Verify that you're outside of a frameset
2. Execute any Slashcommand where URL starts with `javascript:` (e.g. `/debug`)

**Expected result**
The command is executed successfully

**Actual result**
New browser tab is opened, the command isn't executed at all. If one opens the browser console, they can see a ReferenceError related to an object/property used by the command's code

**Comment by n21lv** [comment]
The actual code doesn't seem to matter at all. Any Slashcommand which has URL starts with `javascript:` opens a new browser tab and the code is executed there. I have just tested this by creating a custom Slashcommand with this URL value: `javascript: console.log('TEST');`

**Comment by arnoudkooi** [comment]
Thanks, this issue was not limited to the on-prem version, the fix will be part of the next update. I'll post when the Chrome Onprem version is available.

**Comment by n21lv** [comment]
Awesome :) Waiting forward for it!

**Comment by arnoudkooi** [comment]
OnPrem 7.0.0.3 is now available (Before the normal version this time)

**Comment by n21lv** [comment]
Confirming that updating to 7.0.0.3 resolves this
