### ISSUE TITLE
The latest version of snow appears to break custom CSS

### ISSUE THREAD

**Issue by Kommynct** [arnoudkooi/ServiceNow-Utils#396]
i have a stylus theme, and it no longer works unless I untick it, and retick it, I was wondering if your extension could perhaps act as a mediatory layer that re-enables custom css in stylus themes. It would be huge for me.

edit: i thought this was an intentional change, but, it appears it might be a bug with the most recent version of stylus, https://github.com/openstyles/stylus/issues/1601

This should probably be closed but i'll make doubley sure on the next release

**Comment by arnoudkooi** [comment]
Changing the behavior of other extensions is not in the scope of what SN Utils will do.
Maybe you could look at Tampermonkey or something like that?!
