### ISSUE TITLE
Extend Global Search: Add search for sys_id

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#4]
When typing a SysID in the global search and pressing enter, the form for this sysId should open.

![image](https://user-images.githubusercontent.com/6060660/41123283-69e131cc-6a9e-11e8-80b7-3156de7ebb2e.png)

To achieve this functionality, a background script needs to be triggered server-side.
I created a GIST to achieve exactly this functionality: https://gist.github.com/meinzeugde/983aa171eecd21c9f516542eeea8cb02

In case there are more than one tables found for the sys_id:
Option 1: Show a dropdown to select the table
Option 2: Open all additional found records in extra browser tabs

**Comment by meinzeugde** [comment]
I have implemented this functionality ;)

**Comment by meinzeugde** [comment]
If it's not working at first glance, check popup blocking:
![image](https://user-images.githubusercontent.com/6060660/41128914-207d24f2-6ab0-11e8-94d3-ecbebeeb57a0.png)

**Comment by meinzeugde** [comment]
Hello @arnoudkooi,

unfortunately the global sys_id function is not working. You accidently put the code for this in the wrong place:

![image](https://user-images.githubusercontent.com/6060660/41850978-bf8a6760-7886-11e8-930c-0ea11bbe29b1.png)

It has to look somewhat like:

![image](https://user-images.githubusercontent.com/6060660/41851058-005356da-7887-11e8-890d-b0eaa2b7bc8a.png)

**Comment by arnoudkooi** [comment]
Dont tell anyone, but this is now in the left nav filter :)
