### ISSUE TITLE
ScriptSync with Firefox Containers

### ISSUE THREAD

**Issue by likehoy** [arnoudkooi/ServiceNow-Utils#40]
When using a Firefox Container, using the icon to sync a script to VS Code, the ScriptSync Helper Tab is opened in default Container rather than the current.

Able to reopen the Scriptsync helper tab in the current container, but unable to sync scripts as the sync button will revert to default container.

**Comment by arnoudkooi** [comment]
Think this is a duplicate https://github.com/arnoudkooi/sn-scriptsync/issues/21

**Comment by arnoudkooi** [comment]
Looking in to this I see there is you can pass a cookieStoreId to tabs.create
Need to check how this works.

@wiiaboo any ideas?


https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/get

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

**Comment by arnoudkooi** [comment]
In version 3.5.9.0 I added basic support, ScriptSync tab should now open in the correct container.
Im still looking how to i.e. add support for functions in the popup, to use the correct context.

@likehoy can you check?

This topic is for reference, to implement it in background.js
https://discourse.mozilla.org/t/specify-context-container-ajax-or-fetch/29697/6

**Comment by likehoy** [comment]
Hi arnoudkooi, apologies for non response.

Have checked and the ScriptSync tab is now opening in the same Container that it was triggered from.

**Comment by arnoudkooi** [comment]
Good, implementing it in other places seems a bit funcky, so closing this one.
