### ISSUE TITLE
Favicon overlay doesn't scale with resolution

### ISSUE THREAD

**Issue by aalberty** [arnoudkooi/ServiceNow-Utils#401]
Favicon overlay doesn't scale with resolution, which causes an inconsistent experience for users with multiple monitors.

Specific example: I use a laptop (1080p monitor) connected to an external monitor (1440p) - if I set the font size for the favicon on the laptop screen, when I move the tab to the external monitor and refresh the page, the font is much larger to the point of some of the letter getting clipped off of the image.

 
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/46965141/6ff8666a-3bce-47ba-862e-63311e6482dc)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/46965141/b2ce387e-1805-42ac-a6bc-f7a10ba4367e)

**Comment by arnoudkooi** [comment]
Im using the [Tinycon](https://github.com/tommoor/tinycon) library for this, which is not maintained.
Experiencing some inconsistency myself. I'll see if I can find a solution.

**Comment by aalberty** [comment]
Thanks Arnoud! If Tinycon supports it, I might suggest using view width or
view height (vw, vh) instead of px in your js > Tinycon.js file.

Tony

**Comment by arnoudkooi** [comment]
I'll keep my eyes open for a better library, for now I'm closing this
