### ISSUE TITLE
[Feature request] Shortcut to add scrum task

### ISSUE THREAD

**Issue by iuriSpinassi** [arnoudkooi/ServiceNow-Utils#402]
Hi everyone! I'm a SN Utils user. This tool helps me a lot in my day work and I'm very grateful!

I notice that it has a js function called AddScrumTask() that call a modal to create many tasks at the same time. 

Is it possible to create a shortcut key for this?

I would be glad to contribute to this project, if possible!

**Comment by arnoudkooi** [comment]
You could try adding a custom slash command with url: `javascript:AddScrumTask()`

**Comment by iuriSpinassi** [comment]
`javascript:new AddScrumTask()` worked

![sn slashcommand](https://github.com/arnoudkooi/ServiceNow-Utils/assets/49260155/42f564e0-48ae-40ed-a567-d40e1943df22)

**Comment by iuriSpinassi** [comment]
that was not exactly what I was requesting to, but a custom slashcommand do the job pretty well too. Thank you @arnoudkooi !
