### ISSUE TITLE
Favicon editing in Firefox

### ISSUE THREAD

**Issue by stealthgyro** [arnoudkooi/ServiceNow-Utils#406]
So the color picker appears to open a new window and never gets set properly on firefox. I believe in an older version you had the ability to type/paste in the hex code for colors, I would love for that to still be an option.

**Comment by arnoudkooi** [comment]
For Firefox it should indeed fall back to an input. Can you share the version of FF details you use?

**Comment by stealthgyro** [comment]
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/817649/f6176718-7f84-4588-b9af-ea6b4b4c8bec)
115.0b6 Firefox developer edition. with SN Utils OnPrem... But I did just try on standard firefox it does work.

**Comment by arnoudkooi** [comment]
I just published 7.0.3.1 (Firefox only) could you update and see if it is fixed?

**Comment by stealthgyro** [comment]
It's working great, Thank you!
