### ISSUE TITLE
Null table in the GlideRecord tab

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#407]
### Steps to reproduce
1. Open any record from the `sys_ui_list` table (or from any other table that ends with `_list`)
2. Click the extension icon
3. Open the _GlideRecord_ tab
4. See the wrongly generated _GlideRecord_ snippet

![2023-06-21_20-45](https://github.com/arnoudkooi/ServiceNow-Utils/assets/26461232/2e08e992-77fe-4e19-b23e-9e406561209b)

### Root cause
`tableName` is equal to `null` if it's value is not found:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/d230cecb28e83fc31ff1d63840703174a7bdec27/popup.js#L703-L707

**Comment by arnoudkooi** [comment]
Thank you, just missed the update slot, part of the next one!

**Comment by ovarn** [comment]
Not a problem :)
