### ISSUE TITLE
Feature: Hyperlink Generator for Journal Fields

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#41]
I've added this feature to my own desktop utility, but including it in the extension would be cool for consolidating features.
Code is more or less just the following: 
```javascript
var displayText = "Google";
var hyperlink = "https://google.com";
var journalCode = `[code]<a href='${hyperlink}' target='_blank'>${displayText}</a>[/code]`;
```

The journalCode output can be pasted into any Journal field, and once saved, will render as a hyperlink. 
Note: The ServiceNow instance requires the property: **glide.ui.security.allow_codetag** to be set to true for this to work.

**Comment by arnoudkooi** [comment]
Thanks, did you see the right click menu already does something similar?
![image](https://user-images.githubusercontent.com/840781/70772372-9fa4a200-1d74-11ea-98eb-19a91b839e72.png)

**Comment by VanWeapon** [comment]
I didn't see that one, but cool! you've thought of everything it seems

**Comment by arnoudkooi** [comment]
Good! closing it for now
