### ISSUE TITLE
Unable to unimpersonate if impersonating external user

### ISSUE THREAD

**Issue by sauso** [arnoudkooi/ServiceNow-Utils#413]
Unsure if this is a bug but if i impersonate a CSM user it works great.  But if i try and run /unimp it fails to unimpersonate.

**Comment by arnoudkooi** [comment]
I have heard of this issue a few times, see [these](https://github.com/arnoudkooi/ServiceNow-Utils/issues?q=unimp) issues.
Would you have steps to reproduce in a PDI, or instance I can access?
Maybe you can add a custom command that points to `impersonate_dialog.do` as a workaround

**Comment by arnoudkooi** [comment]
Did the workaround work?
