### ISSUE TITLE
[Feature request] Scratchpad to global in the Next UI

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#414]
Hi. 

Can I add a reference to the `g_scratchpad` object the same way as it works for the `g_form`?

https://github.com/arnoudkooi/ServiceNow-Utils/blob/108bfe0bb6225e40a270944a8f8c01366be6b97e/inject_next.js#L67-L76

Basically I miss this line in the above event listener code:
`window.g_scratchpad = frm.nowRecordFormBlob.globals.g_scratchpad;`

What do you think about this?
Thanks!

**Comment by arnoudkooi** [comment]
Not using it myself, but fine with that.

**Comment by ovarn** [comment]
The idea behind this is to give an option to modify the `g_scratchpad` from the console during some testing like it's possible in the classic UI.

But I have just realized that the `frm.nowRecordFormBlob.globals.g_scratchpad` is a string... And I was not able to find the real `g_scratchpad` object.

**Comment by arnoudkooi** [comment]
No idea either, maybe add a `debugger` statement in a client script that uses `g_scratchpad` to reverse engineer?
If you do find it, you can add, it. will close this one now.

**Comment by ovarn** [comment]
Thanks! I will try.
