### ISSUE TITLE
Technical field names missing in New York following Activity Stream on tabbed form

### ISSUE THREAD

**Issue by MJR616** [arnoudkooi/ServiceNow-Utils#42]
Noticed that on a New York instance, the plugin stops displaying technical field names following a section that includes the Activity Formatter on a form.  

E.g. Tabs 1-3 on a form.  Activity formatter on Tab 2 - field names appear on Tab 1, but not Tab 2.  Move Activity Formatter to Tab 3, field names appear on tabs 1 and 2

**Comment by arnoudkooi** [comment]
Thanks, I could replicate the issue.
This should be fixed in version 3.5.9.1, please upgrade and try.

**Comment by MJR616** [comment]
Thanks for the quick response!  Tested and all working.

**Comment by arnoudkooi** [comment]
great!
