### ISSUE TITLE
SNUtils for Firefox doesn't seem to work at all

### ISSUE THREAD

**Issue by maialithar** [arnoudkooi/ServiceNow-Utils#420]
Hi,
Firefox 115.02, SNUtils 7.0.8.0.
It just doesn't work. 

In addition to #415 , I see no improvements on the background scripts page:
![background script](https://github.com/arnoudkooi/ServiceNow-Utils/assets/211896/83a4738a-7c3f-49ef-8066-31660e8d5c99)

And the technical names are not visible on page load:

https://github.com/arnoudkooi/ServiceNow-Utils/assets/211896/8d03baf1-871a-4a1c-afaa-bfa31cfb704b

**Comment by arnoudkooi** [comment]
Would you be available for a troubleshooting session?

**Comment by maialithar** [comment]
Sure

**Comment by arnoudkooi** [comment]
https://servicenow.zoom.us/my/arnoudkooi

**Comment by maialithar** [comment]
Short update @arnoudkooi - no idea why, but it started working. Maybe it's something with the containers after all - I believe it started working after running it with no container. Strange, will update if it reappears

**Comment by arnoudkooi** [comment]
Does it keep working when login out and removing the cookies in the default container? (probably not)

**Comment by arnoudkooi** [comment]
And?

**Comment by Noodlez1232** [comment]
It works on some instances and not with others. I can't go into specifics too much because I work in SN with internal instances, but I'm running into that problem.

**Comment by maialithar** [comment]
> 

works fine with 7.0.8.3, thank you

**Comment by arnoudkooi** [comment]
> It works on some instances and not with others. I can't go into specifics too much because I work in SN with internal instances, but I'm running into that problem.

I assume you're not on the latest version. hoping it is solved when you try 7.0.8.3, if not please open a new issue
