### ISSUE TITLE
/vd omits all string content enclosed by < and >

### ISSUE THREAD

**Issue by PZifcakBC** [arnoudkooi/ServiceNow-Utils#421]
/vd omits all string content enclosed by < and >
if there is no closing bracket found, all rest of the string is omitted

![vd_ignores_string_content_enclosed_in_sharp_brackets](https://github.com/arnoudkooi/ServiceNow-Utils/assets/18570164/1de97533-d3b7-4414-8e12-cff08dc15592)

**Comment by arnoudkooi** [comment]
I could not replicate it, however, I'll escape the values in the next update.
Will update when the new release is available

**Comment by arnoudkooi** [comment]
Coul you check if it is fixed in 7.0.8.1?

**Comment by PZifcakBC** [comment]
I have checked it in sys_email.message_id and it works there, but I did additional checks on other string fields and it is failing.
you should be able to replicate it with any string field, as I did in short_description on record inherited from sc_task, see examples

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/18570164/230b71e6-18f7-4ecf-aee2-e49682340af8)

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/18570164/3cc8d435-2310-4d67-b641-fc6481c8103d)

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/18570164/c9ace84d-9920-4bcd-8253-7c96f6e6dc9a)

**Comment by arnoudkooi** [comment]
Strange, could you debug this line:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/15c3e786add531de1dc2fe72e3d02ae904eb8bcb/viewdata.js#L92
And could you test on a PDI? Your UI looks different, is it an old instance, that does not have some escape properties enabled?? (Just thinking out loud)

**Comment by PZifcakBC** [comment]
pictures were taken from Tokyo in good old UI 16, in UTAH with Polaris enabled it looks ok

**Comment by arnoudkooi** [comment]
Are you able to troubleshoot further? I could not replicate the issue.
