### ISSUE TITLE
/uh doesn't unhide all hidden fields

### ISSUE THREAD

**Issue by CritchCode** [arnoudkooi/ServiceNow-Utils#422]
/uh will show all fields that have been hidden using UI policy or g_form.setDisplay(fieldname, false) but it will not show fields which have been hidden using g_form.setVisible(fieldname, false).

Difference:
- UI policy or setDisplay(): hides the field and collapses the space that the field was taking up
- setVisible(): hides the field but does not collapse the space that the field was taking up

The div with id 'element.tablename.fieldname' gets given the following style attributes:
- setDisplay(fieldname, false) - style="display: none;"
- setVisible(fieldname, false) - style="visibility: hidden;"

This on:
- Google Chrome (115.0.5790.114 (Official Build) (x86_64)) on MacOS (13.4.1 (c) (22F770820d)) running SNUtils 7.0.8.6
- Safari (Version 16.5.2 (18615.2.9.11.10)) on MacOS (13.4.1 (c) (22F770820d)) running SNUtils (latest available - but showing as version 0.0.0.0??)

**Comment by arnoudkooi** [comment]
Assume its works now, let me know if not.

**Comment by CritchCode** [comment]
The unhide bit is definitely working now for both types of hide - thanks!

Just a heads up; not sure if it was your intention, but if a field has been hidden by both a UI policy (which does setDisplay) and a client script using setVisible? (See middle field), the icon shows up twice. At first I thought it was an error, but then I thought it's actually quite useful. It's a bit of an edge case as well.

<img width="519" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/55980966/24c97981-effb-4530-8099-f296a0a245bb">

<img width="782" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/55980966/a101868a-0e58-40dc-b20c-ff5bf62e92b0">

Thanks again for fixing this up!

**Comment by arnoudkooi** [comment]
Haha, no It was not intentional, but the distinct tooltip of the 2 should give some context. I'll just leave it like this, as it gives some extra insight.
