### ISSUE TITLE
Code search functionality doesn't work on Safari or Orion

### ISSUE THREAD

**Issue by PickMeNow** [arnoudkooi/ServiceNow-Utils#427]
Hi,

Noticed that SN Utils Code Search functionality is not working on these browsers: Safari and Orion.
Once I do /code something the dropdown doesn't show any Search Group, trying on Firefox or Chrome I am able to get search results.

BTW Highly appreciate your work in this addon/plugin!!

**Comment by arnoudkooi** [comment]
You must probably disable "Prevent cross-site tracking" in Privacy settings (I'm not tracking you ;))
![Safari20230818 - 1615](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/2ad39b99-9312-472d-aa72-015b13e88ce7)

**Comment by PickMeNow** [comment]
Thanks!!

Issue solved for Safari :+1:

**Comment by arnoudkooi** [comment]
Good, and Orion? If not,  look for a similar setting...

**Comment by arnoudkooi** [comment]
Maybe add in the description that the Extension Page does not add the cookie to an external website.

For example a call from the page:
chrome-extension://iimpebfldpbfipbodemijjbfblmkhoeh/codesearch.html

Does not add the cookie header to requests to:
https://instance.service-now.com/api_endpoint

Even with all cross site and cookie restrictions disabled.

**Comment by arnoudkooi** [comment]
I don't think I can influence the Orion issue, tending to close this issue. Let me know if you think otherwise (happy to help)
