### ISSUE TITLE
Feature request: onPrem version for Microsoft Edge

### ISSUE THREAD

**Issue by lunkki** [arnoudkooi/ServiceNow-Utils#431]
Hello, I came across a case where Chrome Web Store add-ons were disabled by company policy. Could an on-premises version also be made available on the Microsoft Edge Add-ons store?

**Comment by arnoudkooi** [comment]
Let's hope it gets accepted. The normal version usually takes a week to get approved.

![Microsoft Edge20230824 - 0720](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/d8873871-8dea-47fd-9978-518771c583a2)

**Comment by arnoudkooi** [comment]
I see it was accepted.
https://microsoftedge.microsoft.com/addons/detail/sn-utils-onprem/lpephllkfajfgmnfepkdcappnopogjbe

**Comment by lunkki** [comment]
Thanks!
