### ISSUE TITLE
Link added to updates in update set incorrect

### ISSUE THREAD

**Issue by RickSeiden** [arnoudkooi/ServiceNow-Utils#435]
Hello,

The links that have been added to the updates in an update set are very helpful, but they aren't displaying correctly, which makes them difficult to use.

I'm attaching a screenshot of the links that I'm seeing.
<img width="630" alt="updates" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/2730583/59784313-babe-4582-8e87-06b7c0214425">

**Comment by arnoudkooi** [comment]
Thanks, I noticed.

This happens when the name field is the first column, thus already a link to the sys_update_xml record.
I'll fix this in the next update. A temporary fix is to customize the list layout to add another column as the first column.

Sorry for the inconvenience...

**Comment by RickSeiden** [comment]
I changed the update time to the first column and now it's gone.  This is not an inconvenience at all!  No need to apologize at all.  Thank you for the super quick reply!

**Comment by arnoudkooi** [comment]
Good :) 
I'll also add a suffix to these links: ➚
This way it's (hopefully) more clear it's not a reference link

**Comment by arnoudkooi** [comment]
ok now?

**Comment by RickSeiden** [comment]
I'm sorry I didn't respond earlier.  The formatting issue is gone, but the arrow (which I LOVE) is missing and the link just leads to the update record.  But if it's not in the first column, it works great.

**Comment by arnoudkooi** [comment]
Yes, was considering to only add the arrow, in case it is the first column. Idea is not to have it as the first column if that's ok :)

**Comment by RickSeiden** [comment]
That's fine with me.  It's a limitation of the system since ServiceNow puts a link there, right? ;)
