### ISSUE TITLE
Slash commands get converted to all lowercase when there is a space

### ISSUE THREAD

**Issue by dg42xyz** [arnoudkooi/ServiceNow-Utils#44]
**Description**
The slash command feature can open the results in a new tab instead of the current page if at least one of the slash command characters is uppercase.  However, if you enter a slash command with a capital letter, then enter a space (e.g. to enter additional arguments to apply to the command) then the entire slash command is changed to all lowercase characters.

**Steps to reproduce**
- Type "/Acl sys_script" (without quotes) to invoke a slash command filtering on ACLs on the sys_script table.  The expected behavior is that this opens in a new tab.
- Observe that in the slash command popup, it is converted to "/acl sys_script"
- Press enter, observe that you are redirected on the current window instead of opening a new tab
- Also note that if you enter just "/Acl" (without quotes) to invoke the same slash command without any additional arguments/spaces, then it does open in a new tab as expected.

**Root cause**
I looked through the code a bit and it looks like this is happening in the `addSlashCommandListener` function in the `inject.js` file on line 106, and the `if` condition that is defined on line 314.  The current logic appears to check if there is a space, and if so then line 106 converts the entire input to lowercase.

**Potential solution**
In the `addSlashCommandListener` function, it could capture a variable to determine if any of the slash command characters entered are capital:
```javascript
// add around lines 106/107
var hasCapital = snufilter.slice(0, idx).toLowerCase() != snufilter.slice(0, idx);

// update line 314
if ((e.ctrlKey || e.metaKey) && (e.shiftKey || hasCapital) ){
```

**Comment by arnoudkooi** [comment]
Thanks I appreciate the investigation! 

As announced on twitter I changed the way to force in a new tab to holding cmd or ctrl while hitting enter. Would this work for you?
https://twitter.com/sn_utils/status/1206695412414988290

**Comment by dg42xyz** [comment]
Ahhh, I missed that announcement.  I just tried it out and it will work perfectly for me.  Thanks for the quick response!
