### ISSUE TITLE
New slashcommand: /aemc

### ISSUE THREAD

**Issue by dalestubblefield** [arnoudkooi/ServiceNow-Utils#443]
I'd like to discuss adding a new slashcommand 'aemc' that would open App Engine Management Center. 

Example URL: https://instanceName.service-now.com/now/aemc/admin

**Comment by arnoudkooi** [comment]
I am considering adding a way to add solution-specific commands, as this would result in a 404 error for instances not having App Engine. 
I'm not too keen on adding core commands that may not work in all circumstances.

We can check in to brainstorm about how to support "conditional commands", for now, I'll close this one.

Note a custom command is created in a few simple steps. (The prefill link helps with that)
![Google Chrome20231016 - 2130](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/7c299cec-b052-4afa-b72e-1815afd9f01d)
