### ISSUE TITLE
SN Utils OnPrem /pop issue

### ISSUE THREAD

**Issue by lewismacnow** [arnoudkooi/ServiceNow-Utils#444]
Hello, when I use /pop in the **on-prem version** (which I use for a custom URL instance), I have an issue.

**Problem:**
Page Not Found/404 error when using /pop

**How to reproduce:**
When using /pop and going from the non-Next Experience (table.do?sys_id=) page, to the next experience UI.

**Reason:**
"**%2F**" is added to the end of URL, so I end up with:

now/nav/ui/classic/params/target/**%2F**table.do?sys_id=

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/93997957/a599bca2-ed9d-4f06-a3d8-0e77770e090d)

**Comment by arnoudkooi** [comment]
I tried to reproduce it but was not able to.
This is Firefox on Windows?

It does not happen on a PDI?
Do you have exact steps to reproduce?

**Comment by lewismacnow** [comment]
Hi there, I am using a PDI yes.

I am using OS X on **Firefox** and _does not happen_ when using the default instance URL.
Only with a custom URL.

Please feel free to reproduce yourself if you can:

**Custom URL, error occurs:**

login page: https://servicenow.lewismac.com/login.do
u: arnoudkooi
pw: ReproduceError1@

1. Go to any list view with next experience in use
2. use /pop
3. successfully enter page with only list view, no navigator UI.
4. use /pop again
5. Page Not Found error

**No Error with default URL:**

login page: https://dev166161.service-now.com/login.do
u: arnoudkooi
pw: ReproduceError1@

1. Go to any list view with next experience UI.
2. use /pop
3. successfully enter page with only list view, no navigator UI.
4. use /pop again
5. successfully enter next experience navigator UI.

**Comment by arnoudkooi** [comment]
Can you upgrade to 7.1.5.2 and test? Be sure to do a full page refresh after the update.

**Comment by lewismacnow** [comment]
It works perfectly now @arnoudkooi 
Incredible efficiency, thanks!

**Comment by arnoudkooi** [comment]
Great!  (Any guide on how you mapped your PDI URL?)

**Comment by lewismacnow** [comment]
Ah yes, I don't think one exists but would be happy to make one. I'll make a step by step guide/ article and share it with you in the next 24 hours with some example config files.

But in short, I am using an apache web server with [proxypass](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html)
Using proxypass and proxypass reverse to my PDI.

And using a .htaccess file to replace/append and forward the URI from my servicenow.lewismac.com subdomain to servicenow.

**Comment by arnoudkooi** [comment]
Interesting. I'm not planning on doing the same, just curious, so no need to put in a lot of work :)
