### ISSUE TITLE
Errors in plugin

### ISSUE THREAD

**Issue by lordyj2001** [arnoudkooi/ServiceNow-Utils#445]
I started getting a ton of errors on the plugin this morning. I can provide details of each error if need be.

Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
Service worker registration failed. Status code: 15
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Uncaught TypeError: jQuery(...).select2 is not a function
Uncaught TypeError: jQuery(...).select2 is not a function
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
Uncaught ReferenceError: DOMPurify is not defined
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
Timer 'option loop' already exists
Timer 'option loop' already exists
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
Timer 'option loop' already exists
Timer 'option loop' already exists
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
Timer 'option loop' already exists
Timer 'option loop' already exists
Timer 'option loop' already exists
Timer 'option loop' already exists
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
Uncaught SyntaxError: Unexpected end of input
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Unexpected end of input
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught ReferenceError: jQuery is not defined
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: missing ) after argument list
Uncaught SyntaxError: Unexpected end of input
Uncaught SyntaxError: Invalid or unexpected token
Uncaught SyntaxError: Invalid or unexpected token

**Comment by arnoudkooi** [comment]
Yes, please add more details, as well as console screenshots, that reference files and line numbers.

**Comment by lordyj2001** [comment]
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/caf18652-49ea-4bbe-b18a-421ce6fecde8)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/ab7fa774-9c5a-4eaa-a746-fbb03bf27b94)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/c4ca06bf-4b04-4dc9-9af8-52452178cc49)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/d7853192-019a-4dcd-abcb-fff141d45db4)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/27c44969-33d3-4e56-b53f-5bf55bd94b92)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/6ca26813-22ac-4c38-b2b5-fddecbd2d1e2)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/8cf2c9b0-29e3-4eb3-91f3-a36913349b14)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/37bbccfa-036a-4e31-aabd-fe885b64266f)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/93d176b3-8e53-48dd-8d60-7bd14226618e)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/4ef1370b-0fb3-4671-bc66-2570538646c0)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/297f2fb4-906e-4538-84be-94d883c3ea37)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/892f10d7-6db7-4e01-a3cb-8650904635f5)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/245f64d7-484e-48be-9525-f3a48fed7e08)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/6a881211-6e56-43dd-883a-aef258db9adf)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/e31dd747-3467-46ce-a677-7adff0f6e095)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/d2e6ab94-813c-4fe8-aa95-e30a55ec6108)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/f7cd3866-1112-4738-a96c-c45933005739)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/5401403/bc803cb4-4388-4239-bf11-d8954558a87d)


I hope these help

**Comment by arnoudkooi** [comment]
What is the browser and OS? do you have time for a quick checkin?

**Comment by arnoudkooi** [comment]
What is the browser and OS and Chrome version? 
Googling the problem seems to be a Ubuntu issue.
Maybe unpacking this version will work:
https://github.com/arnoudkooi/snippets/blob/master/chrome-snutils.zip

Or do you have time for a quick checkin?

**Comment by lordyj2001** [comment]
Sadly in the middle of meetings for the next few hours at work but after that I could do for a checkin.
See below for info.

Vivaldi	6.2.3105.58 (Stable channel) (64-bit) built from Chromium
Revision	160afb130e98d47754ca92d477dfe950a5c0b4c1
OS	Windows 10 Version 22H2 (Build 19045.3448)
JavaScript	V8 11.6.189.22
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by arnoudkooi** [comment]
I could not replicate so far, maybe we can check in next week.
It feels like scripts are not loaded timely.

**Comment by lordyj2001** [comment]
Ya something happens after a few days or a week of being reinstalled. I get these errors. I would be more than happy to do all I can to help.

**Comment by arnoudkooi** [comment]
I have a feeling this is a Vivaldi issue, maybe you can file a report there.
If you do, It is important to be complete in your information like it only happens after a week.
Also, don't focus on SN Utils but the problem that scripts added by an extension don't seem to load.

**Comment by lordyj2001** [comment]
I will do that. I see 2 icons in my browser. So it could be tied to that.
Where are the pieces of the extension stored in the PC? Maybe I can remove it fully manually and try to reinstall it from a clean slate

**Comment by arnoudkooi** [comment]
What do you mean 2 icons? If you have both SN Utils and the OnPrem version, I would disable 1 of them

**Comment by lordyj2001** [comment]
My org doesn't have an OnPrem instance. I had tried to manually remove it at one point in troubleshooting and now I have 2 icons that "work" when they work and don't "work" when it's broken. I am sure it's my fault for that. I will check with Vivaldi because it doesn't have issues on other PC's now after the last update.

**Comment by arnoudkooi** [comment]
Of there is something I can do let me know. Closing this one.
