### ISSUE TITLE
Project Workspace Freezes when SNUtils is enabled for < Week views

### ISSUE THREAD

**Issue by Ritzo90** [arnoudkooi/ServiceNow-Utils#448]
When we enable SN Utils extension and use the new "Project Workspace"; when we adjust a project task from a week level or below it will lock up the browser but not the session.

I've tested this in Chromium Edge which we have to use at our organisation, and when we use an InPrivate browser it works fine. 

Eg in our DEV:

<img width="655" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/19607270/0f979405-6d71-4c14-b2a3-bca588836834">

Example on a fresh PDI:

<img width="542" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/19607270/897b2c89-551b-40ad-9a59-4dad9696adbc">

**Comment by arnoudkooi** [comment]
Is below the screen causing the issues?
Could you add steps to reproduce, I'm not familiar with Project Workspace...
![Microsoft Edge20231031 - 1509](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/9b9308b4-2794-49a6-b619-f53dbb11ff59)

**Comment by Ritzo90** [comment]
No worries, the issue can be reproduced with the plugin enbaled. Set the view to week or day:
<img width="557" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/19607270/8a435892-9716-46ee-84d8-76f94ce0bc23">

In this view you can adjust the task time by the hour and after adjusting it, it locks up the window:
<img width="393" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/19607270/c05c6166-02f0-43a3-9c71-528dbb5a488c">

**Comment by arnoudkooi** [comment]
I'm not able to reproduce it so far, what patch level are you on? (I'm on Vancouver patch2-hotfix1)
And do you see console errors?

**Comment by arnoudkooi** [comment]
Any update?

**Comment by Ritzo90** [comment]
Hi we are on Vancouver Patch 2 hotfix 1. 

There is nothing obvious in the console other than some complaints related to our regional date formats and momentjs:
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/19607270/2414e9f2-3c91-491d-87f5-fc9d7184e96e)

It is entirely possible this only in our environment and there is something I'm missing like Edge for Business or SOE issues. I was not able to reproduce the issue with SN Utils disabled again. However, when it was enabled it took more multiple attempts before it freeze the screen today.

Happy to close if you can't reproduce it.
