### ISSUE TITLE
Some OOB slashcommands interferring with history

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#449]
Some out of the box commands like /diff1 and /diff2 are interferring with the history.
Once you type out /diff, the drop-down from the history opens up. So now, if you type 1 or 2, instead of executing the command, it opens up the respective entry from history. 

<img width="265" alt="snutils diff error" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/6163219/b1b8833f-ce95-4687-b470-924bc745cf90">

I've attached the screenshot for reference.
This is possibly happening because the 2 entries from history contain a filter condition with the word '**diff**erent in it'.
Is there any way to avoid this?

<img width="509" alt="snutils diff error" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/6163219/697b191f-bca9-4e12-9d73-fcf8d069f726">

**Comment by arnoudkooi** [comment]
It's a feature, not a bug I would say :)
You should be able to avoid it by unchecking the below checkbox (Be sure to reload the window after the setting change)

![Google Chrome20231102 - 0913](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/85eedce6-dfa6-4c2f-b9e2-dbfa2b159a92)

**Comment by vedang444** [comment]
Ok, Just an unlucky coincidence then :)
I think the navigator search is more useful in this case since I often use it.
I guess can't do much other than renaming the command. Probably will just wait for the history to die out or overwrite it then.
Thanks :)

**Comment by arnoudkooi** [comment]
Oh, sorry I now understand the problem. Hitting the 1 now opens the history. 
I will look into that. Will follow up in this issue!

**Comment by arnoudkooi** [comment]
In the next update, I'll disable keyboard navigation to navigator hits, in case there is a slash command containing that number. I'll update when the fix is published.

![Google Chrome20231103 - 2139](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/1f3f38bf-9765-40f5-b610-3785cedf4571)

**Comment by vedang444** [comment]
I can see the fix in the latest update.
Thanks Arnoud and keep up the great work! 🙂
