### ISSUE TITLE
sn-kit/Service Portal developer tools

### ISSUE THREAD

**Issue by t1mb0b** [arnoudkooi/ServiceNow-Utils#45]
I am curious if it might be possible to implement similar functionality to the [sn-kit](https://github.com/jtandy13/SNKit) plugin/extension into sn-utils. I find this tool quite useful for Service Portal development, and it does not appear to be under active development from what I can tell.

**Comment by arnoudkooi** [comment]
I like it, but dont want to rip code, and seems a bit to niche..

**Comment by t1mb0b** [comment]
> I like it, but dont want to rip code, and seems a bit to niche..

I get that, thanks for considering!
