### ISSUE TITLE
Active and Random switches do not work together

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#450]
Hi Arnoud,

A very common instance (for me) of using slash commands and switches is to open a random ticket.
However -r opens a random **record** from all available records on that table, and -a opens a **list** view of all active records on the table.
If you use both together, only the switch of the random record is executed (which means it can also return an inactive record, which is the more common case since we always have many more inactive tickets than active).

I don't know if these were designed to be used together (which may not be the case since I looked into the function you designed "snuGetRandomRecord"), in which case this could be an enhancement.

Let me know what you think.

**Comment by arnoudkooi** [comment]
Fair point :)
I'm looking into this, a bit more complex then I thought, due to the current way the -r switch works...

**Comment by VanWeapon** [comment]
+1 from me, especially if `-r` could combine with the other slashcommands that apply encoded queries, would make testing just that bit nicer. E.g. `-r -a -m` to open a random active record I've created before. I also have a few extra slashcommand switches I've added for myself that would combine with this really well e.g.
`-mc` : my company 
`-md` : my domain 
`-am` : assigned to me

**Comment by arnoudkooi** [comment]
This should work in 7.1.7.0, please check. Should also work with custom switches.

**Comment by arnoudkooi** [comment]
And? ok to close?

**Comment by VanWeapon** [comment]
This worked for me

**Comment by vedang444** [comment]
Sorry, read this just now. Works great Arnoud. Thanks! :)
