### ISSUE TITLE
Don't work in linux

### ISSUE THREAD

**Issue by filhocf** [arnoudkooi/ServiceNow-Utils#457]
I'm a new user of Service Now and I tried your extension in Vivaldi, a Chromium based browser, and also tried in Ffox and Chrome, all browsers in my Linux env.

Do you tried it in a Linux machine?

**Comment by arnoudkooi** [comment]
What distribution do you use? I can try and setup a VM

**Comment by arnoudkooi** [comment]
I tried Vivaldo in a Parallels Ubuntu ARM VM, and it works. Please share more regarding your setup, what do and don't you see work.
Is it a service-now.com instance

**Comment by filhocf** [comment]
Hi @arnoudkooi 

After some months I discovered the problem. My SN's instance have some problem that don't recognise your extension. 

I created a personal instance and your extension works fine that.

Thank you by your work and sorry by my mistake.
