### ISSUE TITLE
direct open reference record function on document_id field results in missing ".do" after the table name in the URL

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#459]
When using the direct open reference record function by double-clicking on reference icon the resultant URL is missing the ".do" on the end of the table name which means the URL does not work on some instances. This is on a table/document_id reference field combination (eg target_table and instance fields on sys_email table). I have a UI15 Tokyo instance where the missing ".do" causes the URL to fail to open the target record. On my Vancouver UI16 instance the URL with the missing ".do" works ok.
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/23983fc2-3456-4ed9-88c2-c00430b47adc)

**Comment by arnoudkooi** [comment]
Thanks for flagging, fixed in 7.2.1.3
