### ISSUE TITLE
Encoded Query string ignoring all text after first whitespace

### ISSUE THREAD

**Issue by monk098** [arnoudkooi/ServiceNow-Utils#460]
When running a /table_name command with an encoded query string and text in the query after the first space is ignored. 

i.e. /sc_cat_item nameLIKEIncident Form opens the sc_cat_item table with a query of Name Contains Incident.

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/157543314/6975ffaa-dee3-43fb-a7ad-581c294fe0a3)

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/157543314/30041c6d-b56f-463f-bfc7-df276cf992b2)

**Comment by arnoudkooi** [comment]
Should work in 7.2.2.2 
Note that it may not work as expected when the encoded query has a - in it, as it will interpret that as a switch

**Comment by monk098** [comment]
Just tested and can confirm it's working.
