### ISSUE TITLE
Cheat sheet v1.0 "CTRL [" and "CTRL ]" wrong way around

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#461]
Not sure where else to raise this, as it is not SN Utils code related, but on the v1.0 of the cheat sheet "CTRL [" and "CTRL ]" are documented the wrong way around. When I test it, next record is "CTRL ]". On the cheat sheet this is documented as "Previous record".

**Comment by arnoudkooi** [comment]
Good catch, I updated it!
