### ISSUE TITLE
Option to enable/disable the double click to show Technical Names

### ISSUE THREAD

**Issue by hellomp** [arnoudkooi/ServiceNow-Utils#463]
I like the option to double-click to show the fields' technical names but unfortunately, in the Service Operations Workspace, I also need to double-click to edit a field in a list, which makes me show and hide the technical names every time I want to do that. I guess a toggle in the SNUtils Settings page to disable the technical names on double-click would be perfect for everyone in the same situation as me.

**Comment by arnoudkooi** [comment]
I'm not a fan of adding lots of options.
I will exclude a double-click in a Next Experience list to toggle Technical Names.
Alternatively you can disable add UI elements this will also disable the double-click function

**Comment by arnoudkooi** [comment]
did you check?
