### ISSUE TITLE
Issue with running SN Utils on ServiceNowServices instances

### ISSUE THREAD

**Issue by jdogg2k** [arnoudkooi/ServiceNow-Utils#47]
SN Utils doesn't seem to run at all on the new instances in the Government Cloud that have a URL of *.servicenowservices.com  Any way to have the tool detect that URL as well?  Thanks

**Comment by arnoudkooi** [comment]
The OnPrem version works with that, if I add this all users will get a popup witch Im trying to avoid. Is that ok?

https://chrome.google.com/webstore/detail/sn-utils-onprem/lfabkiipmidkmhplochgpbaeekjjfbch

**Comment by jdogg2k** [comment]
Yes, OnPrem is the solution I needed for this.  Thanks!
