### ISSUE TITLE
Use number field as short cut in to navigate to a record.

### ISSUE THREAD

**Issue by ewatch** [arnoudkooi/ServiceNow-Utils#470]
Not sure about a 100% solution yet but I thought it would be nice to fastly navigate to a record with the following approach:

<img width="1504" alt="Bildschirmfoto 2024-02-08 um 14 12 48" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/2991341/1a29dc59-0232-42a4-9572-b62155750643">

One thought was here to also query the table to verify if this is a valid number (at least the starting chars like INC, CHG, etc.):
sys_number

What do you think about this topic ?

I know its also possible to go there via the searchfield but I would like it to just go there through slashcommands.
Other possibility would be to do the following:
- Query sys_number field and build up map in Browser Extension
- when a number is pasted in the slash commands check against this map and get the table
- convert the pasted number into a table slash command like /incident number=<pastedvalue>

Best regards,
Jan

**Comment by TWalkerVeracity** [comment]
This is already a feature with the /tsk slash command.

**Comment by ewatch** [comment]
My example was now only in relation to task.
Yes /tsk would work for task tables that inherit the "Task" table.

But it should be working for every table that uses the "Prefix" configuration.

Example:
On the PDIs there is for example a table "ast_contract" which doesn't inherit from task.
"/CNTR0009001" should also work in this case.

Best regards,
Jan

**Comment by avotom** [comment]
You can just use "/search CNTR0009001"

**Comment by ewatch** [comment]
Hey @avotom, that's a good idea. 
Thank you. Then I will close this issue.

**Comment by arnoudkooi** [comment]
Based on this discussion I added this 
>   - Slash command now triggers a global search when no match is found, ie: /INC3940740 opens that incident. This is a shortcut for the /search command. If the command contains a _ it tries to open a table list like it used to.

More in CHANGELOG.md / latest commit
