### ISSUE TITLE
Keyboard shorts showing everytime I click ctrl+/

### ISSUE THREAD

**Issue by RahmanM** [arnoudkooi/ServiceNow-Utils#471]
Hi there,

I am getting this Keyboard Shortcuts popup everytime I press Control+/. I checked the settings to see if there is a tick to untick it. I closed the popup, refreshed the browser and still same issue.

My instance is an upgraded to Washington DC and I am using it in Chrome Incognito mode.

<img width="893" alt="image" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/5056215/8399a036-0a87-4083-bd33-e21056568269">

**Comment by CritchCode** [comment]
Looks like the new keyboard shortcuts feature of Washington DC uses the same keyboard combination as SNUtils. It would be a massive shame to lose CTRL+/ as an SNUtils shortcut because I find it to be more reliable than just / on its own (due to cursor being in text fields etc). Also, it’s muscle memory now!

Perhaps, SNUtils could override the existing Washington DC shortcut but then it would effectively remove access to that baseline dialog.

Perhaps an option to override the baseline keyboard shortcut? Or if not, maybe add an extra modifier like the shift key?

Ctrl+Shift+/ instead?
Cmd+Shift+/ for Mac version

**Comment by arnoudkooi** [comment]
Thanks Critch, this is indeed an OOTB feature that uses the shortcut I had :(
https://twitter.com/sn_utils/status/1753558008662049231

On Windows I now recommend ALT-/ 
Could you check you are on the >= 7.2.3.0 and update if needed?
I'll also update the Safari version later this week :)

**Comment by CritchCode** [comment]
Awesome, yeah good choice. Alt+/ is an easy two Key combo to learn. I’ll get that safari update the moment it comes out and start retraining my muscle memory before most of my customers hit Washington! Thanks as ever Arnoud 👍

**Comment by RahmanM** [comment]
Is it possible to default it to Alt+/ but make it configureable so users can set their own key if needed e.g. Ctrl+s etc?
Many thanks for looking into this issue!

**Comment by arnoudkooi** [comment]
There is a shortcut you can define in the extension shortcut settings.
Seems it is not working, I'll check it and update here.

![Google Chrome20240215 - 0932](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/da398a13-919b-40c7-8969-fb61fba91dc6)

**Comment by arnoudkooi** [comment]
There is a shortcut you can define in the extension shortcut settings.
Could you test if that works?

![Google Chrome20240215 - 0932](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/da398a13-919b-40c7-8969-fb61fba91dc6)

**Comment by RahmanM** [comment]
Hi,

Thank you so much. This worked perfectly fine for me in Chrome + Windows.
It doesn't accept Ctrl+/ unfortunately but I set it to Ctrl+S and it worked.

Much appreciated.

Regards,


Rahman

**Comment by RahmanM** [comment]
This resolves my issue.

**Comment by arnoudkooi** [comment]
> I'll also update the Safari version later this week :)

 @CritchCode  Updated :)

**Comment by CritchCode** [comment]
Superb customer service there as ever Mr Kooi! Thank you :)

Sent from my iPhone ***@***.***)

On 21 Feb 2024, at 08:27, arnoudkooi ***@***.***> wrote:

﻿

I'll also update the Safari version later this week :)

@CritchCode<https://github.com/CritchCode> Updated :)
