### ISSUE TITLE
Ctrl+C no longer copies text by default

### ISSUE THREAD

**Issue by LDCK** [arnoudkooi/ServiceNow-Utils#474]
When trying to copy anything within a SNOW ticket using either Ctrl + C or Right-Click + Copy I receive a notification "Nothing copied, consider the CopyTables extension for more control. Redacted screenshot below.

I'm a non-admin user of SNOW who was previously able to copy basic info like the ticket number or details from the ticket without this notification popping up each time I attempt to copy anything from a SNOW ticket.

I'm using:
WIndows 10 Enterprise 22H2
Firefox 122.0.1
SN Utils 7.3.0.0.

This has only started happening today, I assume this is due to a recent update?

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/26562008/d4acb31d-d6c0-482b-96a5-c0fec8521c23)

**Comment by LDCK** [comment]
I see now that this was introduced in 7.3.0.0
"/copycells can now be triggered via the OS copy shortcut (ctrl-c or cmd-c), when no other selection is made"

**Comment by VanWeapon** [comment]
This popup also triggers when hitting ctrl+c with nothing selected while in a text editor. Normally this results in the whole line copied, which is something I do frequently, so this is pretty disruptive to that.

**Comment by arnoudkooi** [comment]
Apologies I have reverted it, will update when published. I linked it to the Paste clipboard image setting. A workaround is to temporarily disable that. (see screenshot)


![Google Chrome20240219 - 0715](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/dfb348b4-2046-4da5-961f-ca4fba69fb51)

**Comment by arnoudkooi** [comment]
The fix is published, except for the Chrome OnPrem one (still pending).
Can you try if 7.3.0.1 fixes it?

**Comment by VanWeapon** [comment]
Appears to be fixed for me

**Comment by LDCK** [comment]
Fixed now thanks for the quick turn around @arnoudkooi

**Comment by arnoudkooi** [comment]
Good, closing this. I may reopen when I do some work on this.
I'll at least add it as an explicit option when I reintroduce this.
