### ISSUE TITLE
SlashCommand doesnot work on UI16 Chrome

### ISSUE THREAD

**Issue by cnavr** [arnoudkooi/ServiceNow-Utils#476]
Hi Arnoud,
on version 7.3.1.0 SlashCommand functionality stopped working on UI16 Chrome
When I enter "/"  I get 
"VM59 inject.js:3076 Uncaught TypeError: Cannot read properties of undefined (reading 'querySelectorDeep')
    at HTMLDocument.<anonymous> (VM59 inject.js:3076:74)" in chrome developer tools (attachment
![Screenshot 2024-02-21 102924](https://github.com/arnoudkooi/ServiceNow-Utils/assets/19973589/65c0cedf-85af-42ad-b7fc-bbe21df64585)
)
Our instance is on Vancouver_p3hf4
When I use some "PolarisBased" page (for example /now/clone/ui/home), the "/" does work.

Please help (I am not able to work without SlashCommands ;-) )
Thanks
Ctirad

**Comment by Anduh** [comment]
The "slashcommands not working on UI16" also affects Firefox.

Setup:
Windows
Firefox (121.0.1)
SN Utils(onPrem) 7.3.1.0

**Comment by arnoudkooi** [comment]
This is fixed in 7.3.1.1
Besides Chrome OnPrem this version should be available to upgrade to.

**Comment by Anduh** [comment]
Wow, amazingly fast action on the fix. 😁

Will report back later when the update propagated to me. (Can't seem to get Firefox to update the plugin, and on Chrome a fresh install of either extension gave 7.3.1.0; so can't confirm yet)

**Comment by arnoudkooi** [comment]
Try this (usualy a browser restart works as well)
![Firefox20240221 - 1148](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/8b6549cb-fba5-40ce-9b72-bb32287301e4)

**Comment by arnoudkooi** [comment]
Note that Chrome is still pending. Will update when available

**Comment by cnavr** [comment]
I have workaround in the meantime (using key-shortcut)
![Screenshot 2024-02-21 122949](https://github.com/arnoudkooi/ServiceNow-Utils/assets/19973589/e879a45c-c288-4c4c-864c-8ad26680d08d)
Ctirad

**Comment by arnoudkooi** [comment]
Great tip, the regular Chrome one just got approved!

**Comment by Zorakie** [comment]
Just stopping by to confirm that Firefox onPrem 7.3.1.1 fixed the issue :)

**Comment by Anduh** [comment]
Got onPrem 7.3.1.1 on Chrome and Firefox, fixed issue on both.

**Comment by arnoudkooi** [comment]
Glad it's fixed! And that's so kind Anduh! Thanks a lot!

**Comment by arnoudkooi** [comment]
Closing, think the update is rollout by now
