### ISSUE TITLE
Node switching no longer working on ADCv2 instance

### ISSUE THREAD

**Issue by GuillaumeVachonPom** [arnoudkooi/ServiceNow-Utils#477]
We used to see a warning saying to try a few times and eventually it would work. Now it switches instantly (in sn-utils) but in /stats.do it still is the previous instance.

**Comment by arnoudkooi** [comment]
And if you close and reopen the popup?

**Comment by GuillaumeVachonPom** [comment]
Still showing the node I selected is 011, same thing if I refresh the window. But in /stats.do I'm still on node 012

**Comment by GuillaumeVachonPom** [comment]
Let me know if you need more info but it would be great if you can find a fix. It's a great tool and we use this a lot to be able to see node transaction logs and we haven't found any other way to do it.

**Comment by arnoudkooi** [comment]
Could you share the stats.do files?

**Comment by GuillaumeVachonPom** [comment]
Sorry for keeping you waiting, I sent the files to you on linkedin.

**Comment by arnoudkooi** [comment]
Based on our discussion, I made an adjustment, that will land in version 7.3.2.2

**Comment by arnoudkooi** [comment]
Is it manageable now?

**Comment by arnoudkooi** [comment]
If you have issues I can help with, let me know

**Comment by GuillaumeVachonPom** [comment]
As long as I manually delete the "BIGipServerpool" cookie, it works everytime. If there's no way to differentiate my instance from others and delete this cookie automatically after updating the "glide_user_route", I can work with that. Thanks for your help!
