### ISSUE TITLE
Window size flicker on firefox

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#483]
Not sure is this affects all firefox users or just me. But when I search for slash commands the SN Utils window flickers between 2 different sizes at the  bottom of the SN Utils window. Works fine on chrome.

https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/b4f5eb8c-49fd-47c1-8a62-8b2ca99965fc

**Comment by Anduh** [comment]
Was able to replicate this as a Firefox(121.0.1)/Windows user.

To me it seems the flickering occurs when list of search results are so few that the scrollbar for command section doesn't show.

Haven't used the slashcommand search earlier so hadn't noticed.

**Comment by arnoudkooi** [comment]
I couldn't really figure out the root cause, but bumped the height of the container from 500 to 550px
Could you monitor if that fixes it?

**Comment by codaroma** [comment]
looks fixed so far
