### ISSUE TITLE
/vd command not always working

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#484]
Is there some condition that mean /vd does not always work?
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/a584fb12-8d31-4586-8ad4-56e282e323dd)

**Comment by arnoudkooi** [comment]
Please share full browser screenshot, this does not give me a clue...

**Comment by codaroma** [comment]
Let me know if you need more
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/720f7cc7-8653-4fe2-a79f-8803cda5d616)

**Comment by arnoudkooi** [comment]
Could you execute
` snuResolveVariables("")`
in console and post results here?

**Comment by codaroma** [comment]
Object { variableString: "", tableName: "x_qual5_vmdr_vuln_task_item", sysId: "3e4e0eeb1b9cbd90999062ca234bcbcc", encodedQuery: "active=true^ORDERBYnumber" }

**Comment by arnoudkooi** [comment]
We could maybe check in to troubleshoot..

**Comment by codaroma** [comment]
Sorry for the delay. Just saw this now. Yes, no problem.

**Comment by codaroma** [comment]
This is what I get for snuResolveVariables("") now
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/5e507a2e-23d2-4cdc-b248-b41ccdb81d50)

**Comment by codaroma** [comment]
btw not sure if it is related but I get this when I use the red button to close the slash commands window
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/4a1edd02-1063-4140-8e42-031daf723c8d)

**Comment by codaroma** [comment]
Is rtrn meant to be a global rather than a local variable?
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/e698b0c9-85e9-4324-8c6a-bdfc05c6bdf8)

**Comment by codaroma** [comment]
snuResolveVariables does not seem to be able to calculate the tableName if the window URL is of the form.
<instance>/<tableName>.do?sys_id=<sys_id>
It calculates the sys_id just fine.

**Comment by codaroma** [comment]
We are in a "classic form" but g_form is not available.

**Comment by codaroma** [comment]
snuResolveVariables() code jumps from line 1484 to 1493 because typeof doc.g_form is undefined
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/9e70a453-c3f0-4cc0-9e0f-e61d78cb5590)

**Comment by arnoudkooi** [comment]
I think it's easier to check in, this comment flood is making me dizzy.
I believe you're on Discord? you can ping me there.

**Comment by arnoudkooi** [comment]
Thanks for checking in. We found an issue where a variable was set to an tinymce iframe.
