### ISSUE TITLE
Scripts Background Syncing to VS Code

### ISSUE THREAD

**Issue by xSaltyDalty** [arnoudkooi/ServiceNow-Utils#486]
On the Scripts - Background Page, the Open in VS-Code link no longer works. I receive the following error message :  

Uncaught ReferenceError: snuEditor is not defined
    at snuPostToScriptSync (inject.js:3973:73)
    at <anonymous>:1:1
    
  I am not sure if this is an issue due to the latest update on March 24th, 2024, but I thought I would raise awareness.

**Comment by xSaltyDalty** [comment]
<img width="1916" alt="Screenshot 2024-03-26 at 2 01 04 PM" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/141754546/ce6533d4-e6bc-4617-a137-d15d65ecf679">
<img width="1530" alt="Screenshot 2024-03-26 at 2 00 07 PM" src="https://github.com/arnoudkooi/ServiceNow-Utils/assets/141754546/0fa25b2e-94b9-4423-9818-09c3b4c569bc">

**Comment by xSaltyDalty** [comment]
Sorry for the Re-open I miss clicked and closed by mistake.

**Comment by arnoudkooi** [comment]
Are you still seeing this issue?
What is the browser and version of SN Utils you use?

**Comment by arnoudkooi** [comment]
I found the issue and will fix it in the next update. As a workaround, you can type something in the editor i.e. `//` before clicking the link

**Comment by arnoudkooi** [comment]
The fix is published in 7.4.2.0 let me know if that fixes it after you upgrade.

**Comment by xSaltyDalty** [comment]
Hi,

Sorry for the late reply. Our customer recently updated their instance
version to the Next Experience; however, I am no longer seeing the issue I
was before. So this seem to be fixed now.

Thank you!
