### ISSUE TITLE
New Slash commands are not being saved

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#488]
Hi Arnoud,

I don't know if this is related to my Company laptop or a recent update of Chrome (Version 123.0.6312.105 (Official Build) (64-bit)), but I cannot seem to save new slash commands anymore.

When I add it, it does get saved on the tab, and I'm able to use it, but once I refresh the tab, it's gone.
I also tried directly adding it from the Advanced SN Utils settings but it still is not saving.

Is anyone else facing this issue?

Thanks in advance!

EDIT:
Actually just noticing that this is not restricted to slash commands. I cannot seem to change and save any settings from the extension. Whenever I change any setting, and refresh the page, it changes back.

EDIT 2:
I checked on my other laptop which does not have the updated Chrome installed yet and it seems to be working fine there.
This may be a Chrome Version issue but I'm hesitant to be sure as no one else seems to be reporting it.

**Comment by arnoudkooi** [comment]
Do you see an error in the console? You must open the console from the popup, not the instance.

**Comment by vedang444** [comment]
Here you go. Hope this helps.
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/6163219/6b7f2366-373c-4be0-a129-ec287bb89d64)

**Comment by arnoudkooi** [comment]
Do you have a lot of slash commands? Looks like a data exceed, although I thought it was fixed here #204
Could you try back up and remove, to see if that is the issue?

**Comment by vedang444** [comment]
It semi-worked, or probably we know that's where the issue is.

I backed up the slash commands (I had around 30) and refreshed the tab and everything started working. I then quickly increased the limit from the default 50 to 200, and imported the backup.

Now all the slash commands work. However, now, if I go to add a new command or modify an existing one, all get deleted, and I once need to import the backup each time.

Not sure what is happening here.

**Comment by arnoudkooi** [comment]
That setting is unrelated, that is only the ones last used you can scroll through with the arrow up key, not the commands itself. Ill change the text to clarify.
Are you able to do some troubleshooting, check for errors when hitting the save button?

**Comment by vedang444** [comment]
Hey,
I don't know what fixed it but it started working overnight, had not restarted the system or anything.
As of now it is working fine again. But will report back if I see anything within the week.
