### ISSUE TITLE
Add support for custom URLs and URL Masking

### ISSUE THREAD

**Issue by garrett-griffin** [arnoudkooi/ServiceNow-Utils#49]

**Comment by arnoudkooi** [comment]
I think your looking for the "OnPrem" version, available for Chrome and FireFox
https://chrome.google.com/webstore/detail/sn-utils-onprem/lfabkiipmidkmhplochgpbaeekjjfbch

**Comment by arnoudkooi** [comment]
Assuming this works for you...

**Comment by garrett-griffin** [comment]
It helped -- I was able to get most features working. But I can't get any keyboard shortcut to open slash commands dialog.

**Comment by arnoudkooi** [comment]
When using this version you must use CTRL-/  (Mac CMD-/) did you try that?
Otherwiese check the settings https://twitter.com/sn_utils/status/1192913388906713088

**Comment by garrett-griffin** [comment]
Thanks a ton for following up with me. It was probably just the setting and
I'm a moron. But at any rate after uninstalling the regular plugin and
having just the onprem one, and flipping the setting to off and back to
Cntrl+/ again, it's working now.

Thanks!
