### ISSUE TITLE
Issue with double-clicking on list query filter in firefox

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#491]
The sn utils feature to copy/paste/edit the list query filter by double-clicking on the query breadcrumb links does not work correctly in firefox. If the list is in its own tab (popped out of the iframe) and you double-click on the query you get the query edit prompt briefly but the page refresh is not interrupted so it disappears as soon as the page refreshes before you have had a chance to interact with the window.prompt() dialog box.

**Comment by arnoudkooi** [comment]
I could not replicate. Do you have more info on versions, os and a screenshot?

**Comment by arnoudkooi** [comment]
Looks like you're clicking on the link itself, you should double-click on whitespace around the link

**Comment by codaroma** [comment]
Ah, yes, that is where I have gone wrong. Although in chrome you can do both. Double-clicking on the link in chrome (not whitespace) will pop-up the dialog, allow you to edit the query, and then it will refresh the list with the new query.
