### ISSUE TITLE
Table search not working on firefox

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#493]
Entering command /*meta works on chrome but I get an error on firefox

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/87c78829-8e99-484f-b385-5ba5c8042696)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/e2ac46bf-5c99-4aa8-b1d1-52ef4435d7a3)

I can see in the firefox developer console the REST call response status code is "HTTP/1.1 401 Unauthorized"

I can also see in the REST call request headers on firefox that the X-UserToken header has a value of "undefined" instead of g_ck.
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/a4e00731-832f-44fb-9c8d-d3a4aec15fad)

**Comment by arnoudkooi** [comment]
I could not replicate, maybe because you are on blank.do where no g_ck variable is present?

**Comment by codaroma** [comment]
I was on /now/nav/ui/classic/params/target/blank.do in chrome too. 
But now I cannot replicate the issue in firefox anymore for /now/nav/ui/classic/params/target/blank.do
Sorry for the waste of your time.
