### ISSUE TITLE
Issue #483 appears to be back

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#494]
https://github.com/arnoudkooi/ServiceNow-Utils/issues/483

This is on firefox
https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/a6a26d14-014e-4673-974a-747ee8ee9745

**Comment by arnoudkooi** [comment]
Bummer. I'll declare this a won't fix as I spend quite some time on it, and it’s a "visual annoyance". If I do find time, ill re-open and update the original issue.
