### ISSUE TITLE
Ctrl + S keyboard shortcut - serious bug

### ISSUE THREAD

**Issue by AdKiller** [arnoudkooi/ServiceNow-Utils#495]
I was happy to find the useful Ctrl + S keyboard shortcut and it worked great for saving single entries.

but when I used it in a batch selection, it seriously messed things up. 

I selected 3 requests: 
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/13304436/9f78dca0-6838-4149-919f-704de5790f67)

I modified only the entries with red arrow.
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/13304436/5e66e84e-f6a5-47d6-83a1-c7e6bd23f2e5)

I saved with keyboard shortcut Ctrl +S

It saved 2 of the requests as expected, but the 3rd request got wiped off blank! EVERYTHING was removed: Description, Short description, Configuration Item, tipologia, etc... and replaced "Requested for" & "Opened by" with my name!!!

This does not happen when I click the UPDATE button at the top.

WTF happened?!

**Comment by arnoudkooi** [comment]
This view uses action `sysverb_post_update` The next update adds a check that aborts saving via CTRL-S and shows a warning when this action is present on the form.

![Google Chrome20240419 - 1735](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/de8a4a1f-f9c0-4bdb-bd4a-47ca55c6699d)

**Comment by AdKiller** [comment]
@arnoudkooi I should add that even on a single entry using the keyboard shortcut Ctrl + S seems to be doing some extra things in the background. I received new notifications about new things being created that I had never received after saving an entry. 
I had to remove the addon since it seems to make some dangerous changes.

**Comment by arnoudkooi** [comment]
Steps to reproduce? This is not information I can troubleshoot.

**Comment by AdKiller** [comment]
Every time I used the keyboard shortcut (single entry or multiple selection), I received new chat notifications like this:
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/13304436/782b0c2f-f180-49dc-a83b-578d31a17bae)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/13304436/059008fd-2be4-4cc6-8dc0-949da503c20f)

I reiterate, when I click save these notifications are not created.
So the extension does something extra other than simply activating the save button.

**Comment by arnoudkooi** [comment]
It only calls the gsftSubmit function.

I see that's connect chat, I don't have an instance with it, as it's deprecated some releases ago.
If you have a PDI where the issue is present I can log in to, I can have a look.
Otherwise, I can do a quick call if needed.
