### ISSUE TITLE
/vd is not working for me (firefox) in certain tables. 

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#499]
This looks similar to #484 but it is different. Both sysid and table name are being calculated correctly for the extension popup tab.

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/ef91e570-4537-4f46-af52-88df1e803351)
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/274ff00e-7358-48e1-8ce1-64a0dfc1f2b6)

I have this issue on certain tables whether the form is popped in or out.

**Comment by arnoudkooi** [comment]
Problem is syslog does not have the sys_updated_on field. Fix will be part of next release. Will post here when published.

**Comment by arnoudkooi** [comment]
Did an FF only release 8.0.1.1 that should now be available to update to.

**Comment by codaroma** [comment]
Yep 8.0.1.1 has fixed it. Many thanks
