### ISSUE TITLE
Background script results pane height cannot decrease

### ISSUE THREAD

**Issue by TWalkerVeracity** [arnoudkooi/ServiceNow-Utils#502]
Within the enhanced background script editor with the side by side code script and results panes, the scroll hight only every grows since the resizer element height is set by:

https://github.com/arnoudkooi/ServiceNow-Utils/blob/865b60118f178b2eeb3487a6cdca2e26022b67a8/js/monaco/bgscript.js#L136

This causes the body's height to never decrease since the height of the resizer preserves the body scroll height, even if the left and right pane have decreased in height. The below snippet will instead size itself to the total height of the left and right panes, fixing the issue. 

`resizer.style.height = Math.max(leftSide.scrollHeight, rightSide.scrollHeight) + 'px';`

**Comment by arnoudkooi** [comment]
Thanks, good enhancement!

**Comment by arnoudkooi** [comment]
This is implemented in 8.0.2.0 along with another enhancement 
https://twitter.com/sn_utils/status/1791044817838854593
