### ISSUE TITLE
"javascript:" slash commands on popped out pages (not in gsft_main iframe) are being mangled by DOMPurify.sanitize()

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#503]
Can you try this custom slash command? (it is a simplified example) in a popped out page (not in gsft_main iframe).

**Command:** test
**URL:** `javascript:alert("<test")`

When saved it appears in the slash command list as
`test         javascript:alert("`

And when you execute it nothing happens and you get errors in the developer tools console.
Seems to be the same in both chrome and firefox.

**Comment by codaroma** [comment]
Looks like it is the call to DOMPurify.sanitize(targeturl) that is mangling the code.
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/ebd5cd7a-0695-4bf4-9d7a-bc1a4ffb5f37)

**Comment by codaroma** [comment]
For example
URL: `javascript:alert("<>&")`
is converted to
`javascript:alert("&lt;&gt;&amp;")`

**Comment by codaroma** [comment]
I am trying to create a javascript: slash command that contains a regular expression and DOMPurify.sanitize() is completely mangling it.

**Comment by codaroma** [comment]
The code path for executing custom "javascript:" slash commands for pages inside the gsft_main iframe and pages that are outside the gsft_main iframe are different. The code that executes "javascript:" slash commands when the page is inside the gsft_main iframe is as follows...
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/82f4bb05-5add-4c39-aa38-5a49b4f1f401)
but when the page is not inside the gsft_main iframe the code that executes "javascript:" slash commands is this...
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/2d8c83b5-ab9e-4337-b08f-9cb53280cbe7)
One does a DOMPurify.sanitize() on the targeturl variable and the other does not, which leads to different behaviours.
The code path that uses DOMPurify.sanitize() breaks the code in the custom command.

**Comment by arnoudkooi** [comment]
As there is no external way to manipulate this value, I'll remove the sanitize

**Comment by arnoudkooi** [comment]
Is it ok now?

**Comment by codaroma** [comment]
Yes, many thanks
