### ISSUE TITLE
The crn command doesn't respect the sysparm_view value

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#506]
1. Go to: Self-Service -> Incidents
2. Open random record (see that was opened in the Self Service view)
3. Call the `crn` command
4. See that it was opened in the Default view

**Comment by arnoudkooi** [comment]
Someone mentioned that encoding script fields hoes wrong, have you seen that? Havent looked in to it myself so far

**Comment by ovarn** [comment]
I haven't used it on forms with script fields. However, I am aware of the issue with the condition fields. I wanted to create an issue and PR later this week. The caret character in the field values must be escaped the same way as it's done here:
https://github.com/arnoudkooi/ServiceNow-Utils/blob/d11cb369ddc1a2225e07a1604524058f17dec2aa/inject.js#L2268-L2269
