### ISSUE TITLE
CTRL + S to save a record stopped working

### ISSUE THREAD

**Issue by peace2000** [arnoudkooi/ServiceNow-Utils#508]
Suddenly, CTRL + S stopped working for me. Instead of saving a record, the browser wants to save a html file to my PC. Restarting browser or re-installing the addon doesn't help...

I'm using Firefox 115.11.0esr and SNUtils Onprem 8.1.2.2.

**Comment by arnoudkooi** [comment]
Did you check a different browser / instance / table, any other extensions active, do you see a console error?

**Comment by peace2000** [comment]
I disabled other addons, didn't help. Works on Chrome.

I managed to get it to work now. I don't understand how to. Clearing the cache for my Service Now page didn't work. But when I once opened

```
Show created/updated info about this record 
 (Who the heck edited this?)
Doubleclick to view data in new tab
```

Button, it now started to work.

**Comment by peace2000** [comment]
Thanks anyway :)

**Comment by peace2000** [comment]
This happened again.

In order to get this to work, I had to clear the cache of the SN-instance I was using and re-install the addon.

It seems that when this issue is ongoing **Show created/updated info about this record** button also disappears.

**Comment by arnoudkooi** [comment]
Please provide clear steps to reproduce.
