### ISSUE TITLE
Add special handling in /docs to search docs in current instance's version

### ISSUE THREAD

**Issue by wiiaboo** [arnoudkooi/ServiceNow-Utils#51]
As best practice the latest docs are always best, but in most cases, a customer's instance will not be on the latest version, so it'd be useful, when working in an older version instance, to search docs specifically for the instance's version.

I'm not exactly sure how the current instance version can be retrieved other than parsing stats.do, but there's probably a better way.

I can't implement this during the week, but if you don't do it by the weekend, I can try it myself.

**Comment by arnoudkooi** [comment]
Hmm, I see the benefit, not sure if this one is worth the added complexity and server calls 
- It's easy to overwrite the default /docs one via the popup
- we could add a few for the current releases like /docsm /docsn /docso

**Comment by RiCONfru** [comment]
```javascript
fetch('https://instancename.service-now.com/stats.do')
  .then(response => response.text())
  .then(str => (new window.DOMParser()).parseFromString(str, 'text/html'))
  .then(data => console.log(data.documentElement.innerHTML.match(/Build name: (\w+)/)[1]));
```

seems to do it, but seems hackish to me. And yeah, it's probably easier to just add new commands for at least the last two releases.

**Comment by wiiaboo** [comment]
```javascript
fetch('https://instancename.service-now.com/stats.do')
  .then(response => response.text())
  .then(str => (new window.DOMParser()).parseFromString(str, 'text/html'))
  .then(data => console.log(data.documentElement.innerHTML.match(/Build name: (\w+)/)[1]));
```

seems to do it, but seems hackish to me. And yeah, it's probably easier to just add new commands for at least the last two releases.

**Comment by jacebenson** [comment]
You could just make the link use a preference in extension where you pick a version.

**Comment by arnoudkooi** [comment]
Like the idea, but I have no clue how much people actually use the /docs command, and then how many would take the effort to modify. My guess is that the ones who do, are savvy enough to modify or add a command.

(Would love to know the adoption of features, based on the views of my YT videos and Tweets there is a quite a lack of knowledge. @wiiaboo did your knowledge session already take place, what is your experience?)

**Comment by wiiaboo** [comment]
> (Would love to know the adoption of features, based on the views of my YT videos and Tweets there I think there is a quite a lack of knowledge. @wiiaboo did your knowledge session already take place, what is your experience?)

It's only today at the end of the day. I didn't get a change to completely prepare something very comprehensive as it's been a hectic week so far, but I'm hoping to at least get more people to  know about and use the slashcommands.

> Like the idea, but I have no clue how much people actually use the /docs command, and then how many would take the effort to modify. My guess is that the ones who do, are savvy enough to modify or add a command.

You could add opt-out telemetry to the addon, probably. Just to keep track of how many times a user uses a certain feature with the least amount of identifying information (there's possibly some API you could use for web-extensions to uniquely identify an installation of sn-utils and nothing else). And if people opt-out of it, maybe suggest answering a Google Form with the features they use most and maybe some suggestion of a new one?

**Comment by arnoudkooi** [comment]
How did it go?

The webstore does offer stats on installs, The FF ones are public. I think I'll keep it to that...

**Comment by wiiaboo** [comment]
Went well, afaict.
I did record it, but since I didn't take care to setup a clean instance, and I basically improvised along the way with a semi-production instance I might not want to place it somewhere public, so I'll send it to you by email.
Or I can send just the suggestions people gave during it in the weekend.

**Comment by arnoudkooi** [comment]
Sounds good, apps@arnoudkooi.com should work!
