### ISSUE TITLE
feature request: open URL in a different environment/instance

### ISSUE THREAD

**Issue by aquarilis** [arnoudkooi/ServiceNow-Utils#515]
one thing developers often do is to compare a given URL in another instance. 
most of the time, we would copy the URL and then paste it in the browser, then edit the instance name at the beginning of the URL to open that same page in another instance 

would be nice to have a feature to do that more efficiently :)

**Comment by arnoudkooi** [comment]
There are the following slash commands:
`/env instancename`
and
`/diffenv instancename`

The first will open the same page in the given instance,
the second compares the XML of the record from the original and target instance in a Monaco editor.
Is this what you are looking for?

Note you can create a nested command with a double slash notation like
`//diffenv acmetest` in the url of your custom command

**Comment by aquarilis** [comment]
wow man, that's exactly what I was after
sorry I didn't realise that already existed. 
but of course it would :) 

cheers then!

**Comment by arnoudkooi** [comment]
Cool, fyi there is also `/diff1` and `/diff2` to compare any 2 records.
`/diffenv` is actually using those 2
