### ISSUE TITLE
Copy/change filter on data sources for data visualizations

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/ServiceNow-Utils#516]
I would like the same option as on lists where you can double click to copy the value of a filter. 
This would be really awesome if it was also doable in the data sources for data visualizations.

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/6660378/869b792d-e3bf-4f41-994d-376f295701cf)

**Comment by arnoudkooi** [comment]
what is the exact page where you see this?

**Comment by arnoudkooi** [comment]
If you first activate Technical Names (i.e. via /tn or a double click in some whitespace).
You will see a funnel icon, clicking that shows you what you need, I think?

![Google Chrome20240612 - 1433](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/61a3fb40-5817-4d06-baaa-83178b2dea5a)

**Comment by CGraabaek** [comment]
That's pretty embarrassing - i totally overlooked the funnel, but saw the list icon there.. 
Thanks again!

**Comment by arnoudkooi** [comment]
No problem (if it's your thing, there is also a helpful community of me and others on the SN Devs Slack #sn-utils channel helping with adhoc questions)
