### ISSUE TITLE
MFA Login Issue

### ISSUE THREAD

**Issue by arnoudkooi** [arnoudkooi/ServiceNow-Utils#519]
An issue was mentioned that page `validate_multifactor_auth_code.do` redirected to the login page, instead of logging in.

Conditions on instance where this was seen
- Vancouver Instance
- Next Experience (Polaris) Disabled
-  SN Utils version 8.1.5.0

Was not able to replicate the issue, however made a chance in version 8.1.5.2 that resolves the problem

**Workaround** 
- Disable SN Utils (during login)

**Fix**
- Upgrade to version 8.1.5.2
As of now, 8.1.5.2 is already published, except for SN Utils OnPrem 

**Update SN Utils**
The browser usually automatically updates daily or restart. 
You can force an update by 

1. enabling developer mode
2. then click the update button.

![Google Chrome20240625 - 1504](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/e5f929c4-2bb6-4012-9d48-84c16dff43c1)

**Comment by Anduh** [comment]
## General observations:
- The MFA login issue was replicated with SNU v.8.1.5.0 on Chrome, Firefox & Edge(using chromestore v.8.1.5.0) .
  - Edge's native version of SNU was still on v.8.1.2.6, which didn't have the issue.
- `/validate_multifactor_auth_code` is a page referenced OOB in at least **Login** widget, but didn't find SN documentation on page
- issue seems to have started acting up sometime during 2024-06-23 (Monday), between morning and ~12:00 (UTC+3)

## Instances where issue was observed
For the other SN Instance (Bob) with these same issue, heard from 1 person now login works with v.8.1.5.2 active, + 1 unclear confirm on login working from a second person. *(For the sake of clarity, I'll nickname the two unrelated SN instances in the description as I try summarize details on the two instances.)*

### SN Instance "Alice"
- Version: Vancouver
- `glide.ui.polaris.experience` = `false`
- (the instance first brought up having the issue)
- Alice test & Alice dev instances didn't have this login issue, and so far only certain difference between them and Alice was they had Polaris enabled. (But observations from Bob indicates Polaris might be unrelated)
  - didn't find any difference in MFA-related settings/config between Alice & Alice test.
- Login issue first notice on Monday 2024-06-23 around 12:15 Finnish time(UTC+3) 
- login affected for both custom url & `service-now.com` login tries
- some initial speculations on cause was new version of Chrome having updated to 126.XX.XX, but later abandoned after also observed issue on Firefox.

### SN Instance "Bob":
- Version: Washingtondc
- `glide.ui.polaris.experience` = `true`
- some type of test/demo instance
- completely unrelated to Alice, this info is gathered second-hand
- Login still worked sometime in  the morning of Monday 2024-06-23, and login issues first notice around 15:30 Finnish time(UTC+3)

**Comment by arnoudkooi** [comment]
Should be rolled out, by now
