### ISSUE TITLE
[Feature Request] Add Import/Export Slashcommands

### ISSUE THREAD

**Issue by jioleight** [arnoudkooi/ServiceNow-Utils#52]
Requesting this feature as this will help save time setting up the slashcommands from one browser to another.

**Comment by arnoudkooi** [comment]
You can doubleclick the advanced field in the settings tab, this will remove the readonly state, so you can copy / paste. Be sure that it is valid JSON. Let me know if this works. I'll try to make this easier in an upcoming release :)

**Comment by arnoudkooi** [comment]
I'm keeping this as an poweruser option for now, as described in my previous comment
