### ISSUE TITLE
Message to change Application is not correct in Washington instances

### ISSUE THREAD

**Issue by francoluis** [arnoudkooi/ServiceNow-Utils#522]
Hi, Arnoud.
As you can see in the image, in washington instances the SNUtils message points to the current application and not the desired application:

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/7529127/0403617e-94d8-495f-bf64-1b9277d7df22)

**Comment by francoluis** [comment]
If possible to check, thank you. Love your extension. Is immensely useful!!!

Best regards,
Luis Franco

**Comment by arnoudkooi** [comment]
This is a sys_app record? I'll exclude the switch from this table, as it is provided OOB here

**Comment by arnoudkooi** [comment]
Can you update to 5.1.5.6 and check if the issue is solved?

**Comment by francoluis** [comment]
Thank you! I'll check on he next upgrade of the extension! Best
