### ISSUE TITLE
SN Utils suggests a command that does not exist

### ISSUE THREAD

**Issue by codaroma** [arnoudkooi/ServiceNow-Utils#524]
If I bring up the slash command popup and paste in a sys_id value then SN Utils will suggest 2 commands /sys_id and /search
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/690253/72cd919b-4e09-474c-8c78-285d03865d75)
If I select the first command suggestion (/sys_id) it replaces the sys_id I pasted in with the command /sys_id. But the command "/sys_id" does not exist. The correct command is /sysid. So if I try to use this command it tries to open a table called sys_id_list. I have to remember to remove the underscore each time.

**Comment by arnoudkooi** [comment]
It should work with just hitting enter after pasting, but I'll have a look

**Comment by arnoudkooi** [comment]
The next update will include improvements, when clicking the sysid or search command it woill trigger the search for the current value.
![Google Chrome20240706 - 2131](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/22ae3fce-ce3d-472c-a6d2-cd3d2be2aaba)

**Comment by arnoudkooi** [comment]
Please let me know if this works better
