### ISSUE TITLE
Settings does not scroll in Safari

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#525]
Hi Arnoud,

I just switched over to a Mac and while copying my SNUtils slashcommands and switchesP to the Safari browser, I noticed that I cannot scroll down in the SNUtils settings page like I can on Chrome (no scroll bar either). Could you please look into it or let me know in case I'm doing it wrong.

<img width="806" alt="image" src="https://github.com/user-attachments/assets/dd5deeac-9f90-4d7d-b78e-03968f648425">

BR,
Vedang Vaidya

**Comment by arnoudkooi** [comment]
Does the scrollwheel or arrow keys work?
