### ISSUE TITLE
Editing knowledge articles with sn-scriptsync bypasses checkout/approvals

### ISSUE THREAD

**Issue by qbiecom** [arnoudkooi/ServiceNow-Utils#526]
Hi @arnoudkooi,

In our instance we use article versioning and approvals for KB articles. I've found that if you use sn-scriptsync to sync the HTML of an article into VS code, you can then make a change directly to the article without checking it out for editing, or needing to be approved.

Steps:
- On any KB article, select edit.
- On the first edit page, don't click check-out. Instead, use SN-Scriptsync to send the article body to VS code.
- Edit the HTML and save the file
- See the updated content in the instance, without any approval or checking out required.

I can provide a video or happy to have a teams call to demonstrate.

Thanks!
Matt

**Comment by arnoudkooi** [comment]
Can you check if you can reproduce on a PDI? When I try I do get an ACL error.

In general, I think this should be solved with an ACL

**Comment by qbiecom** [comment]
You're correct, I did some more investigation and it looks like it's the 'Enable minor edits' knowledge property.

Thanks for the speedy response!
