### ISSUE TITLE
make /code search also check item_option_new table

### ISSUE THREAD

**Issue by IE404** [arnoudkooi/ServiceNow-Utils#529]
if you have a script include, which is only used in a catalog item as a reference qualifier, the snutils /code search dont show that its used on the platform

so the /code search should also look into the item_option_new.reference_qual field

**Comment by arnoudkooi** [comment]
This should be configured in the instance itself.
Check [this article](https://www.servicenow.com/community/developer-articles/expand-code-search-tables/ta-p/2592282) for details!
(On the bottom of the code search page, there are also a set of prefill links)

**Comment by IE404** [comment]
thank you, didnt know that.
