### ISSUE TITLE
[BUG?]  Workflow timestamps updated when viewing workflow properties

### ISSUE THREAD

**Issue by SuzukiStumpy** [arnoudkooi/ServiceNow-Utils#53]
Just noticed this in a customer instance (luckily their Dev instance, but still, not good!):

With SNUtils enabled in Chrome - go to the workflow editor and view properties for a published workflow (without checking it out).  Click the back arrow on the form top bar to go back to the WF editor, and the update date/time and updated by fields in the workflow are modified to show the current timestamp and user _even though no actual edit has taken place_.  Confirmed also that nothing is added to the current update set.

Switch off the extension and nothing is updated (as one would expect).

**Comment by arnoudkooi** [comment]
In my testing this does not seem to be related to SN Utils.

My findings are as follows:
Scenario **1**
- Open a workflow updated **a while back** 
- Open the properties page
- Hit the back button in the properties page
- Close the workflow
Outcome: **Update and updated by change to current dt and user**

Scenario **2**
- Open a workflow updated  **today** 
- Open the properties page
- Hit the back button in the properties page
- Close the workflow
Outcome: **Nothing changed on the workflow record**

This behaviour is the same with or without SN Utils enabled, even in Safari where SN Utils is not available.

Maybe you can test in a PDI, to confirm?
Anyway, thanks for being alert!

**Comment by SuzukiStumpy** [comment]
You're absolutely right.  Just tested in my PDI with the SN Utils plugin disabled in the browser and replicate the same behaviour.

I feel a HI ticket coming on.  :)

**Comment by arnoudkooi** [comment]
Seems like the best route, and actually... I'm relieved! :)
