### ISSUE TITLE
Builtin commands like `br` can be edited but custom behaviour don't save beyond a page reload

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#530]
Steps to reproduce: 
Open slashcommand editor
type 'br' and click builtin command to open for edit
Change the url in some way, e.g. change to:
`sys_script_list.do?sysparm_query=collection=$0^ORnameLIKE$0^ORDERBYDESCsys_updated_on`
Click "Save" on the slashcommand
Observe that before reloading the page, the slashcommand can be used with the new behaviour
Reload the browser page
Type `/br` and observe that the functionality has reverted back to it's builtin form
Also observe that in the 'Settings' page, the slash commands json does not contain any entry for 'br'.

This appears to happen for other builtin commands like `cs` and `ua` as well.
Currently using Opera browser in case that makes a difference

**Comment by arnoudkooi** [comment]
I tested in Opera and it worked. Can you check if the JSON of your custom commands is valid? Is it stored there? Does adding a new command work?

**Comment by VanWeapon** [comment]
This is also happening for new commands it seems. 
When i click the save button on a new command, it exists and is usable until i reload the page, then it's gone. 
If i close and reopen the extension window, It also doesn't show up in the slashcommand tab nor in the settings JSON. 
If i export the json to vscode and run a formatter on it there are no errors i can see

**Comment by VanWeapon** [comment]
I can manually edit the JSON to add a new command, update the settings json inside the extension and reload the page, and that does save properly. Only edits through the slashcommand tab of the extension window arent saving it seems

**Comment by arnoudkooi** [comment]
Do you see an error when saving when inspecting the popup?

**Comment by VanWeapon** [comment]
Yes but doesn't look very helpful
![image](https://github.com/user-attachments/assets/17b17cc2-5fb3-4a6f-938b-091726500389)

Can confirm if i clear out the json, then reload the page, i can add and edit slashcommands normally again, so maybe it is something in there

**Comment by arnoudkooi** [comment]
This is similar to #204
It should overflow from sync to local storage maybe you could test if it works when you decrease [this value](https://vscode.dev/github/arnoudkooi/ServiceNow-Utils/blob/master/popup.js#L616-L617) to 5000

**Comment by VanWeapon** [comment]
interesting, that seems like it could be it, if i bloat out the size to above 6000 it fixes it

**Comment by VanWeapon** [comment]
and reducing it to around 4k also fixed it

**Comment by arnoudkooi** [comment]
I'll set it to 5000 for the next update!

**Comment by VanWeapon** [comment]
All looking good now, cheers
