### ISSUE TITLE
Enhanced Background Script editor does not work since Washington upgrade

### ISSUE THREAD

**Issue by tytanowyJohnny** [arnoudkooi/ServiceNow-Utils#531]
Looks like just standard one but it changed in Washington release as it was "enhanced" by ServiceNow itself, url is now "/sys.scripts.modern.do" but even changing back to "/sys.scripts.do" does not make it work.

![image](https://github.com/user-attachments/assets/5edccf57-9d10-4ac1-8f83-accba18a0fc4)

**Comment by arnoudkooi** [comment]
Most likely this is a problem in the instance, please disable SN Utils and see if there is a console error containing minHeigth in console. If so lig a support case.

If you're on SN Devs Slack, check [this thread](https://sndevs.slack.com/archives/CKB5Q8DNK/p1719253773502659)

**Comment by arnoudkooi** [comment]
Did you make progress?
