### ISSUE TITLE
Saving HTML template from VS Code gets changed in platform.

### ISSUE THREAD

**Issue by jon-merchant** [arnoudkooi/ServiceNow-Utils#532]
(ignore bad coding practices)
If you have <script>...</script> in the HTML template code in a widget, and save from VS Code, then check the widget in platform editor, you'll see that it's been converted to &lt;script&gt; ... &lt;/script&gt;
If you edit the template in the platform editor, it does not change and stays <script>...</script>

**Comment by arnoudkooi** [comment]
Looks like you running into issue [sn-scriptsync#24](https://github.com/arnoudkooi/sn-scriptsync/issues/24)
Also mentioned in the [FAQ](https://marketplace.visualstudio.com/items?itemName=arnoudkooicom.sn-scriptsync#faqs)

Setting system property `glide.rest.sanitize_request_input` to `false` should fix this. 
Please let me know!
