### ISSUE TITLE
Weird slashcommand priority

### ISSUE THREAD

**Issue by Kolymorph** [arnoudkooi/ServiceNow-Utils#535]
Not sure if directly bug but a kind of an annoyance - when using slashcommand the "exact" term doesn't always take priority, which can cause weird behavior when you expect it to just call the command you exactly spell out.
Examples:
- writing /cmdb_ci and Enter seems to open cmdb_categories table for me almost always
- I have a custom /prod command that will open the same URL in PROD instance. Sometimes it tried to search for table instead, so I've lowered the priority to 50 but now /p uses the command instead of opening the priorities - I understand that the low priority makes it be prioritized more, but I would expect the exact term to be "stronger" for matching

**Comment by Anduh** [comment]
Some more info could help out with troubleshooting & trying to replicating this behavior.

**Setup:**
1. **Browser**: Using Edge, Chrome or Firefox? Version?
2. **Extension & Version:** Are you using SN Utils(green icon), or SN Utils OnPrem(lila icon)? What version is shown on About-tab?
3. Operating System: Using  Win/Mac/Linux? *(rarely related but just in case)*
4. Using any other browser extensions interacting with SerciveNow? *(unlikely to conflict, but who knows)*

**Context:**
5. When did you first notice this? If it's always been a thing, when did you start using the extension?
6. How consistent is it, does it occure?
7. Have you only seen this behavior on the mentioned prod instance, or also seen it on related test/demo instances? Have you replicated this in a PDI or other unrelated instance?
8. Has this persisted if you tired with a different browser, or different computer?
9. have your colleagues/peers also experienced it? *(you could export your slashcommand as .json & share with a colleague to have them try the same)*

**Comment by arnoudkooi** [comment]
As "Anduh" suggested, please add more context.

**Comment by Anduh** [comment]
**Update**: I experienced this just yesterday for the first time when typing /inc, which changed selection to /sysidn.

I have a command /i (didnt use) at order 5 that was shortcut for /sysid. Changed it's order to 150 so it's after all my used commands, which resolved the issue.

Have a bunch of cmds starting with "/inc" I use dozens of times daily, so 100% sure this behavior hasn't happened until after I saw this github issue. The /i command had been left collecting dust as it wasn't in the way, but it had been in my commands for a good time.

I Run firefox,  SNUtils On Prem, will update with more details. Havent tested on other browsers or instances yet.

**Comment by arnoudkooi** [comment]
I have not fully worked out the order field. It is more meant for less savvy users to have the most common ones for them in sight.

**Comment by Kolymorph** [comment]
Hi,

sorry I went for holiday after submitting 🤦 
I am using chrome, will test other browsers later on.
The most consistent way for me to replicate it is by typing /cmdb_ci quickly, it seems to not register the i on time and opens cmdb_categories instead. It seems as if there was a window of time where the tables are being loaded after I press the underscore, and if I type "i" quicker than they load, the load overrides the first result.
I have managed to get a screenshot as well:
![image](https://github.com/user-attachments/assets/546078df-0c25-46d8-8148-0ac734c65c58)

**Comment by Kolymorph** [comment]
As for the order, I am not really sure how that works, but I would I would assume full command name would be prioritized always, otherwise having a command that is shorter but higher prio would not allow it to be used ever.

Forgot to add that I am using windows and the "green" utils (not on PREM)

**Comment by arnoudkooi** [comment]
You are not using the order field? Does the list update after hitting right arrow?

**Comment by Kolymorph** [comment]
For the ones in the image? No order there. The list gets updated after any action. It seems that the tables are being re-loaded after every key press, but u finish writing "ci" before the refresh for "c" happens.
I think this would happen elsewhere too, but it seems that here it is specifically because it is only two letters so it is easy to enter quickly and the load time is long as there is a lot of cmdb tables

**Comment by arnoudkooi** [comment]
Behavior is that max 100 tables are loaded, until the number of returned table is <100
Maybe easiest to check in sometime to understand and troubleshoot the exact issue.

**Comment by arnoudkooi** [comment]
Please let me know if someone want to check in on this. For now closing it
