### ISSUE TITLE
Feature request: keyboard shortcut to assign or remove myself

### ISSUE THREAD

**Issue by AdKiller** [arnoudkooi/ServiceNow-Utils#538]
First off, I really appreciate all the hard work you’ve put into this Firefox addon! It’s been incredibly helpful.

I use a privately hosted instance of SN. 
When selecting multiple items and going to "Update Selected," I can assign tickets to a user/operator, but there’s no way to remove an already assigned user/operator, or make it empty. This creates some inconvenience when managing multiple tickets.

See screenshots:
![SN1](https://github.com/user-attachments/assets/6269949d-487e-4f6c-87bf-f9c57ca06194)
![SN2](https://github.com/user-attachments/assets/9cdeb61b-4884-4856-8add-8c4ff28c4aff)

Could you please consider adding the following feature:

**A keyboard shortcut to assign or remove myself from the ticket I’m currently viewing. (Like Ctrl+Alt+A)**

Mimicking the action of Assegna a me (Assign to me):
![SN4](https://github.com/user-attachments/assets/7426c9a4-ed82-4734-bd44-3b493c75c857)

We have no button for "remove me"
![SN3](https://github.com/user-attachments/assets/f6a6b6d6-f858-4c00-9de0-01706025b9ec)

Thanks again for all your great work! Please let me know if you need more details or clarification.

**Comment by arnoudkooi** [comment]
You can check in on SN Devs slack #sn-utils channel for support creating the slash command, closing this one.
