### ISSUE TITLE
Microsoft Edge Version behind Chrome

### ISSUE THREAD

**Issue by rverrips** [arnoudkooi/ServiceNow-Utils#54]
Firstly, thank you SO much for this wonderful plugin - It's amazing how much I use it everyday. 

I was also excited to see it in the Microsoft Edge Plugin Store as my company has moved to Edge as a the required browser.  However I noticed that the Edge store version is still version 3.5.1.5 while the Chrome store version is 4.0.3.0

Should I switch back to using the Chrome store version in Edge or will these version "sync" up sometime in the future. 

Thank you again, and do let me know if there's anymore information or assistance I can provide with this.

**Comment by arnoudkooi** [comment]
Yes, please change to the Chrome store one, there are no diffrences besides the older version. I'll pull the Edge version from the store.

(Cool to hear your a happy user :)  )
