### ISSUE TITLE
/elev doesn't demotes the security_admin in Xanadu

### ISSUE THREAD

**Issue by ImJaineel** [arnoudkooi/ServiceNow-Utils#540]
In Xanadu, using /elev, I can turn on security_admin, but not able to turn off security_admin with it.

**Comment by arnoudkooi** [comment]
It looks like it no lionger toggles, you can do `/elev -` to remove the elevated role. Does that work?

**Comment by ImJaineel** [comment]
No, for me with /elev, I'm able to elevate the role but not able to remove it.

**Comment by arnoudkooi** [comment]
My suggestion was to try /elev with a argument such as a dash
'/elev -'

**Comment by ImJaineel** [comment]
Yes, "/elev -" worked, it's removed the elevated role. 🤗

**Comment by ImJaineel** [comment]
I guess suspect, in this case, will need to update the documentation now accordingly, so that others user will also know.

**Comment by arnoudkooi** [comment]
Will do, also see [this post](https://www.linkedin.com/posts/sn-utils_%F0%9D%97%A4%F0%9D%98%82%F0%9D%97%B6%F0%9D%97%B0%F0%9D%97%B8%F0%9D%97%B9%F0%9D%98%86-%F0%9D%97%94%F0%9D%97%BD%F0%9D%97%BD%F0%9D%97%B9%F0%9D%98%86-%F0%9D%97%BC%F0%9D%97%BF-%F0%9D%97%A5%F0%9D%97%B2%F0%9D%97%BA%F0%9D%97%BC%F0%9D%98%83-activity-7249015847871016960-R-fW?utm_source=share&utm_medium=member_desktop)
