### ISSUE TITLE
sys_hub_flow in Local Update set form Customer Updates related list doesn't open workflow studio properly

### ISSUE THREAD

**Issue by markdangio** [arnoudkooi/ServiceNow-Utils#542]
If you click on a sys_hub_flow entry in the Customer Update related list on the Local update set form, it opens workflow studio. However, the flow doesn't open and you receive an error message as attached.
![error](https://github.com/user-attachments/assets/35dda618-3417-4c58-9146-b2b143458f41)
![link](https://github.com/user-attachments/assets/e4d3e059-7af1-4fc7-9a43-72828965bab3)

**Comment by arnoudkooi** [comment]
On a Xanadu P1 (glide-xanadu-07-02-2024__patch1-08-24-2024) instance it seems to work, what version are you testing this on?

**Comment by markdangio** [comment]
Washdc patch4 hotfix1bOn Oct 4, 2024, at 10:59 AM, arnoudkooi ***@***.***> wrote:﻿
On a Xanadu P1 (glide-xanadu-07-02-2024__patch1-08-24-2024) instance it seems to work, what version are you testing this on?

**Comment by arnoudkooi** [comment]
Think thats the problem, please try on a W instance, and / or thest the OOB `Show Related Record` UI action

**Comment by markdangio** [comment]
Whats a “W” instance? Confirmed ootb show related record ui action produces the same result:“Asset not found: check the sys id etc”On Oct 4, 2024, at 11:18 AM, arnoudkooi ***@***.***> wrote:﻿
Think thats the problem, please try on a W instance, and / or thest the OOB Show Related Record UI action

**Comment by arnoudkooi** [comment]
So this is not a SN Utils issue. I meant an X (Xanadu) instance, as it seems to be fixed there.

**Comment by arnoudkooi** [comment]
Closing this, as this is platform behavior, fixed in Xanadu
