### ISSUE TITLE
/diffenv link is duplicated

### ISSUE THREAD

**Issue by johndahl-now** [arnoudkooi/ServiceNow-Utils#546]
Background: When using the `/diffenv remote_instance` command, the new tab containing the side-by-side copies of the active file also has links to the files in the header. See the screenshot below for the `goto tab` links.

![image](https://github.com/user-attachments/assets/b4afdd59-7392-4923-874a-175da2fea265)

Issue: Both links open the local file rather than the respective file on each side.

Version: SN Utils 8.2.0.3

Browser: Brave Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit)

**Comment by arnoudkooi** [comment]
The goto tab switches focus to the opening tab, with the /diffenv command you may not have the "remote" record open and at least have not used the slash command from it.

In the next update, the goto link will be hidden for the "remote" record. Instead, an additional link is added to open the record in a new tab.

![Google Chrome20241010 - 2318](https://github.com/user-attachments/assets/6da5b58e-7107-4a37-81a6-f2ceba50e4c9)
