### ISSUE TITLE
CTRL + S to save a record doesn't work if a dropdown list box is open

### ISSUE THREAD

**Issue by peace2000** [arnoudkooi/ServiceNow-Utils#547]
Using OnPrem version, 8.1.7.3. Issue appears on Chrome and Firefox.

Saving record stops working everytime if I have some dropdown list box open. In these cases, it reverts to original browser function to save a html file.

**Comment by arnoudkooi** [comment]
Choice list? Feels like it shouldn't save when you have that open.

**Comment by peace2000** [comment]
Yes, something like this:

![image](https://github.com/user-attachments/assets/3c6ec475-0e37-4562-9e9a-6f7ca7ef1a5d)

**Comment by arnoudkooi** [comment]
This seems to be browser behavior I can not change. The used keydown event is not captured when a select is open.

If you click an option (or outside the element), it confirms that as the new value and will work again.

**Comment by arnoudkooi** [comment]
Not sure what to do about it, and sort of think it is ok not to save when the select is open.
