### ISSUE TITLE
Global search selection does not work with SN Utils for administrators

### ISSUE THREAD

**Issue by Kolymorph** [arnoudkooi/ServiceNow-Utils#548]
When using the dropdown to select a search in backend (whether global or one of the workspaces) the selection doesn't work and the whole search bar collapses:
Before clicking:
![image](https://github.com/user-attachments/assets/59f006e3-07f1-4b82-bd0e-2f6942c0c28a)
After clicking:
![image](https://github.com/user-attachments/assets/8f6a0989-6660-43a8-ab79-d5ab908014c2)
With SN utils deactivated after clicking:
![image](https://github.com/user-attachments/assets/7b0d83c1-07ac-4b75-a6d9-a08fe65f29f7)

It seems that the Update set and scope selectors that have been added are interfering with this.
Tested in Chrome and Edge

**Comment by arnoudkooi** [comment]
Confirmed, I'll check.

In the meantime, you could
- Disable the setting: _Show (Application and Updateset) Pickers in Next UI Header_
- Or first type a letter in the searchbox then select the context

**Comment by Kolymorph** [comment]
Although now looking at it it seems that the update set/application picker do not work after using the search

**Comment by arnoudkooi** [comment]
Do you have more details?
As long as the search is not empty, it will stay visible. If you remove text, it should hide after loosing focus
