### ISSUE TITLE
Show technical names removes label hyperlinks

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#55]
When you load a form which has a field label where that label has a hyperlink.
Enable Technical Names from the `/tn` slashcommand or by ticking "Show technical names on load"
The field which should have a link now doesnt. 
Issue observed in Firefox and Chrome

**Comment by arnoudkooi** [comment]
Good point, in 4.0.5 the link is now prefixed to the label
![image](https://user-images.githubusercontent.com/840781/85510583-da2aa980-b5f7-11ea-83e6-5fac101b84e9.png)

Please let me know if it works.

**Comment by VanWeapon** [comment]
Yep that works no issue
