### ISSUE TITLE
Unable to Save Slash Commands on `/settingeditor.html?setting=slashcommands`

### ISSUE THREAD

**Issue by ImJaineel** [arnoudkooi/ServiceNow-Utils#550]
I am unable to save any modifications or additions to slash commands on `/settingeditor.html?setting=slashcommands`. After making changes, the save operation fails, and I encounter an error.

**Error in Console**:
In the browser's Inspect tool, the following error is shown:

```
Error handling response: TypeError: Cannot set properties of undefined (setting 'slashcommands')
    at chrome-extension://cpppnajnconeddhhoadibooafkhhalfd/js/monaco/settingeditor.js:139:34
    at chrome-extension://cpppnajnconeddhhoadibooafkhhalfd/js/monaco/settingeditor.js:104:13
```

**Steps to Reproduce**:
1. I recently reinstalled `sn-util`.
2. Now, I am attempting to add my custom slash commands back, which I had previously backed up in JSON format.

**Expected Behavior**:
I should be able to add or modify my slash commands and save the changes successfully.

**Actual Behavior**:
The save operation fails with the error mentioned above, preventing me from updating the slash commands.

**Additional Information**:
- The issue occurs specifically when modifying or adding slash commands via the `/settingeditor.html?setting=slashcommands` page.

**Comment by arnoudkooi** [comment]
This should be fixed in the next couple of days. 
A workaround is to change any setting in the popup first, before opening the slashcommand editor. 
Also see this [Reddit thread](https://www.reddit.com/r/servicenow/comments/1ggsua3/comment/luvbw5d/?context=3)
I will update when the fix is published.

**Comment by arnoudkooi** [comment]
Can you try if v8.2.5.1 fixes it?

**Comment by arnoudkooi** [comment]
Any update?
