### ISSUE TITLE
[Feature] Display scratchpad utility

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/ServiceNow-Utils#56]
I write this as a UI Action for instances i use, but i presume it would work as an injection as well.

My UI Action Code: 
```javascript
function showScratchpad(){
	//ensure \n is converted to html break, add 'em space' which is 4 spaces of indent on objects
	g_form.addInfoMessage("Scratchpad: <br/>" + JSON.stringify(g_scratchpad,null,'&emsp;').replace(/\n/g,'<br/>'));
}
```

**Comment by arnoudkooi** [comment]
Good idea, in 4.0.5 Show Technical names adds the link, that will show when clicked

![image](https://user-images.githubusercontent.com/840781/85510804-2fff5180-b5f8-11ea-9180-19e381a77880.png)

**Comment by VanWeapon** [comment]
Yep that does work, however I noticed something interesting, the nav bar has different HTML elements when you are looking at a record and a View Rule is applied, in that case the link doesnt appear. To replicate, create a blank View Rule on incident like below: (Would force use of Default view and not allow you to change it)
![image](https://user-images.githubusercontent.com/30616047/85517875-0ae40080-b643-11ea-9a37-0e1dc78a9e59.png)

Then load a ticket and see that the technical name and link dont get shown. 
![image](https://user-images.githubusercontent.com/30616047/85517944-1a634980-b643-11ea-880e-e1ddb3920b9f.png)

Another thing is if you click on the link on a table where there are multiple views, then the view selector drop down will show up which is a bit annoying:
![image](https://user-images.githubusercontent.com/30616047/85518413-8d6cc000-b643-11ea-93e9-32a161e4c8e6.png)

**Comment by arnoudkooi** [comment]
Thanks, Will have a look, probably take a bit longer..

**Comment by arnoudkooi** [comment]
Please check 4.0.5.1 and let me know

**Comment by VanWeapon** [comment]
Nice, looking good now
