### ISSUE TITLE
[Request] Port utility to Tampermonkey

### ISSUE THREAD

**Issue by shivaramumapathy** [arnoudkooi/ServiceNow-Utils#57]
Hi Arnoud

Thank you for this awesome Chrome extension.

Can this be ported to Tampermonkey please so we can use this on Safari too? I would be happy to contribute to port it to Tampermonkey if you can help me.

Thanks, shiva.

**Comment by wiiaboo** [comment]
Apple has just announced in WWDC that they'll be supporting WebExtensions
in Safari eventually.
So no point in porting it to TamperMonkey (wouldn't even be possible
without losing a ton of functionality, afaik).

**Comment by arnoudkooi** [comment]
Agree, please have a few months patience, I plan to release it for safari asap when submissions open

**Comment by shivaramumapathy** [comment]
Great, thanks. Will surely wait for the safari extension.
