### ISSUE TITLE
Firefox SNUtilsOnPrem: OOTB-Filter Navigator in Studio hided by default setting

### ISSUE THREAD

**Issue by RegapDD** [arnoudkooi/ServiceNow-Utils#58]
First of all: Really great Plugin. Really like it! :)

The issue: 
When the setting "Dont add UI elements to browser" is check (true), then also the OOTB-Filter-Navigator in the Studio is hidden.
Not sure if this is expected, but maybe it could be excluced? This causes some irritations by other developers.

![image](https://user-images.githubusercontent.com/62462512/86094842-5702cb00-bab1-11ea-8c12-eea8d352d684.png)
![image](https://user-images.githubusercontent.com/62462512/86094858-5c601580-bab1-11ea-8698-22dac8ddd5a0.png)

**Comment by arnoudkooi** [comment]
LOL, This is not a OOTB Filter, this filter is added by SN Utils!

**Comment by arnoudkooi** [comment]
I do want to keep the behaviour of the setting consistent, so dont want to make a exception for this field.. Hope that makes sense.
