### ISSUE TITLE
Adding a few QoL features

### ISSUE THREAD

**Issue by wiiaboo** [arnoudkooi/ServiceNow-Utils#59]
Hey @arnoudkooi,
Last week I was quite bored and implemented a couple features as user scripts.
I wanted to know if you'd be interested in any or both of them (or maybe they're out-of-scope for SN-Utils) before I (or you) actually started work on porting them to SN-Utils.

## Adding a collapser in Comments for top-reply emails
![Screenshot 2020-06-30 at 09 48 52](https://user-images.githubusercontent.com/111605/86105299-1017d400-bab7-11ea-8e30-bb0ac77da2fb.png)
![Screenshot 2020-06-30 at 09 48 59](https://user-images.githubusercontent.com/111605/86105311-14dc8800-bab7-11ea-952c-48c5fb297882.png)
[User Script](https://greasyfork.org/en/scripts/406293-hide-crap-from-emails/code)

## Adding a toggleable Markdown Preview for certain/all textarea fields
![Screenshot 2020-06-30 at 09 50 44](https://user-images.githubusercontent.com/111605/86105415-3473b080-bab7-11ea-9264-40ab718614bf.png)
![Screenshot 2020-06-30 at 09 50 39](https://user-images.githubusercontent.com/111605/86105397-32115680-bab7-11ea-88ab-39a8c2959707.png)
[User Script](https://greasyfork.org/en/scripts/406039-servicenow-markdown-preview/code)

**Comment by arnoudkooi** [comment]
Appreciate the input tough I think it's a bit to niche. As I want to be conscious with the amount of js to inject...

**Comment by wiiaboo** [comment]
Yeah, understandable.
