### ISSUE TITLE
Bug: pop-in no longer works

### ISSUE THREAD

**Issue by therealbitkid** [arnoudkooi/ServiceNow-Utils#60]
In the ServiceNow Utils context menu of a ServiceNow page, there is a feature to pop-in or pop-out a page to the ServiceNow frameset.
The feature to pop-in a page no longer works.
Pop-out works fine.

Version: 4.0.5.1
Extension engine: Chrome

**Comment by arnoudkooi** [comment]
Plea

**Comment by arnoudkooi** [comment]
Please review this in v 4.0.5.3

**Comment by therealbitkid** [comment]
It works now.
Thanks
