### ISSUE TITLE
Feature Request: turn on "Show Technical names on page load" per instance

### ISSUE THREAD

**Issue by rverrips** [arnoudkooi/ServiceNow-Utils#61]
Hi 

Thanks again for a great plugin - I would only be half the ServiceNow developer I am without it :)

One feature request if possible (could just be me with this issue).  I love the "Show Technical names on page load" flag and have that on all the time as we have a number of customer tables with field names all over the place.    

The feature works perfectly, except when I'm taking screenshots or working with other non development users and they keep saying things like "My ServiceNow column headings look different" or "what are all those extra labels you have - I don't have those".  

With this in mind, would it be possible to enable that flag on per instance basis?  I really only need it in our DEV environment.  I hardly ever used it in our TEST and PROD ?  

Just a request, nothing urgent or required if it's too much work as it's not too much of an inconvenience to turn on/off manually as I switch instances. 

Again, thanks for a great plugin!

**Comment by arnoudkooi** [comment]
I'm a bit hesitant to add complexity to the settings menu.
Would playing around with the way you grant SN Utils access on an instance basis be an option?

![image](https://user-images.githubusercontent.com/840781/87180051-13456800-c2e0-11ea-8042-d1deb3023f5a.png)

**Comment by rverrips** [comment]
I understand not wanting to add complexity to the settings menu. 

Changing the setting you suggest would solve the issue for my PROD instance, but then other features of the plugin, like the slash / commands aren't available in PROD anymore.  I will probably just turn the feature off and turn it on when needed and off again afterward.  

A bit cumbersome as a refresh of the page is needed with the changing of the setting, but I do understand not wanting to complicate things.    

Thank you again for a great plugin - It saves me a bunch of time in other area's so I can certain live with this little nuance.

**Comment by rverrips** [comment]
Last Update: I tried turning Technical Names off for a week on all instances and just doing a /tn when I needed it - Workes great!
Thanks again for a great plugin!

**Comment by arnoudkooi** [comment]
Great, note that you can even assign a single key shortcut to this command via the extension shortcut settings
![image](https://user-images.githubusercontent.com/840781/87828215-c41dab00-c87c-11ea-8ffe-ebb22ed1c514.png)
chrome://extensions/shortcuts

Also can be benefitial to repress that shortkey when a popup apears ie in this case
https://twitter.com/sn_utils/status/1149434190892621824
