### ISSUE TITLE
[Feature Request] Create custom slashcommands for different portals

### ISSUE THREAD

**Issue by suhail-now** [arnoudkooi/ServiceNow-Utils#62]
Currently I can't seem to create a slashcommand for a custom Service Portal. [/<portal_name>] seems to assume it as a table and tries to navigate to [<portal_name>_list.do]

**Comment by arnoudkooi** [comment]
Can you share screenshots or more details.

**Comment by arnoudkooi** [comment]
Note you must define it in the popup 
![image](https://user-images.githubusercontent.com/840781/88143834-31706980-cbf8-11ea-9d79-d01eb2173304.png)

**Comment by arnoudkooi** [comment]
Assuming this worked based on the thumbs up...
