### ISSUE TITLE
Extension doesn't recognize servicenowservices domain or any custom SN domains.

### ISSUE THREAD

**Issue by trott4425** [arnoudkooi/ServiceNow-Utils#63]
The extension only pops up when the domain in the address bar is service-now.com. ServiceNow uses servicenowservices.com domain for their FedRAMP instances. I love this tool but cannot use it for some instances that I am in due to this.

**Comment by arnoudkooi** [comment]
As you closed this, I guess you found the onprem version.
https://chrome.google.com/webstore/detail/sn-utils-onprem/lfabkiipmidkmhplochgpbaeekjjfbch
