### ISSUE TITLE
Keyboard shortcuts on Firefox for MacOS

### ISSUE THREAD

**Issue by KennyV** [arnoudkooi/ServiceNow-Utils#64]
I've searched but couldn't find a solution.
I recently switched from Chrome to Firefox. I used to rely on the CMD +1 ... keyboard shortcuts a lot.
On Firefox it doesn't perform the designated SN-utils shortcut but switches to the corresponding numbered tab instead.
I've tried changing the keyboard shortcuts in the settings for sn-utils but they keep reverting back to the default.

Any help would be appreciated. Possibly this is not an issue but rather my stupidity but I can't get it to work.
I tried living with the slashcommand /pop instead but when doing so while editing a form it asks me to stay/leave (indicating my entries will be gone when I leave)

**Comment by arnoudkooi** [comment]
Have you tried setting them in the setting menu?

![image](https://user-images.githubusercontent.com/840781/89546830-4eff1f00-d805-11ea-9b52-bf131719ccb2.png)

**Comment by KennyV** [comment]
Hoi Arnoud,

Bedankt om al zo snel bij me terug te komen.
De extensie pagina ziet er voor mij anders uit. Het is daar dus dat het me
niet lukt om de toetsencombinatie aan te passen.
Ik heb ook getracht om de “Command” te overschrijven met bijv. “Option”
maar ook dat wordt niet vastgehouden.

Ik zit op MacOS 10.15., Firefox 79.0 en sn-utils 4.0.5.5






On 6 August 2020 at 16:53:57, arnoudkooi (notifications@github.com) wrote:

Have you tried setting them in the setting menu?

[image: image]
<https://user-images.githubusercontent.com/840781/89546830-4eff1f00-d805-11ea-9b52-bf131719ccb2.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arnoudkooi/ServiceNow-Utils/issues/64#issuecomment-669978090>,
or unsubscribe

**Comment by arnoudkooi** [comment]
make sure to go via about:addons in the adres bar

![image](https://user-images.githubusercontent.com/840781/89548353-36900400-d807-11ea-9cc9-352b9003fb2d.png)

**Comment by KennyV** [comment]
My bad…
I went into the extension and tried changing the shortcuts there.
Instead I should have gone through the cog-wheel on the extensions
“homepage”.
Got it, thanks a lot !!

On 6 August 2020 at 17:07:44, arnoudkooi (notifications@github.com) wrote:

make sure to go via about:addons in the adres bar

[image: image]
<https://user-images.githubusercontent.com/840781/89548353-36900400-d807-11ea-9cc9-352b9003fb2d.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arnoudkooi/ServiceNow-Utils/issues/64#issuecomment-669986542>,
or unsubscribe

**Comment by arnoudkooi** [comment]
Glad it works now!
