### ISSUE TITLE
Feature request - Slashcommand for querying any table

### ISSUE THREAD

**Issue by tdeniston** [arnoudkooi/ServiceNow-Utils#65]
I have a slashcommand that I always add as soon as I load the plugin. It allows me to enter a table name and an encoded query and jump straight to the filtered list. An example is "/q sys_user name=joe%20employee"

Command: q
URL: $1_list.do?sysparm_query=$2
Hint: Filter list with encoded query

I think this would be a great addition to base set of slashcommands.

**Comment by arnoudkooi** [comment]
Thanks I like the idea.
I think i'll add it a to the built in right arrow tablesearch explained in the linked video

`/sys_script -q:active=true
`
https://youtu.be/CqZ2xXLeeks?t=317

**Comment by arnoudkooi** [comment]
This is now implemented (#73), see my tweet for a demo
https://twitter.com/sn_utils/status/1317239357712072704

Hope this works, please let me know!

**Comment by arnoudkooi** [comment]
Closing this, please let me know if it works.
