### ISSUE TITLE
Mozilla Review comments

### ISSUE THREAD

**Issue by arnoudkooi** [arnoudkooi/ServiceNow-Utils#66]
After a review the FireFox version was disabled from the add-n gallery, with below remarks.
Posting this for full disclosure. I look into it asap.

> Details:
> This add-on didn't pass review because of the following problems:
> 
> 1) We don't allow add-ons to use remote scripts because they can create serious security vulnerabilities. We also need to review all add-on code, and this makes it much more difficult. Please insert those scripts locally from your add-on code.
> - inject.js line 1183
> 
> 2) This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page . Here are some examples that were discovered:
> - codesearch.js line 51
> - inject.js line 1058
> and others
> 
> 3) This add-on is collecting personal data: the full tab url with parameters. Please limit the information you send to your server and if possible only send the hostname. Even though this information is mandatory for the add-on to function, it still requires affirmative user consent (i.e., explicit opt-in from the user). It must be clear to the user that they give consent to the collection of personal data. Please see https://blog.mozilla.org/addons/2016/07/15/writing-an-opt-in-ui-for-an-extension/ for an example of how to present the opt-in. Also, a summary of the data collection must be added to the add-on description and in the text accompanying the opt-in. For more information, refer to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews#Data_Disclosure_Collection_and_Management

**Comment by arnoudkooi** [comment]
Point 1 and 3 are not clear to me, 1 I dont load external script here, 3 I'm not collecting any personal data. maybe this refers to cached data. Will check with reviewer for clarification.

**Comment by arnoudkooi** [comment]
Point 1 is removed
Point 2 fixed by adding sanitizing via DOMPurify library when setting innerHTML
Point 3 I dont collect data, would need clarification
(Version only pushed to Mozilla Add Ons)

**Comment by arnoudkooi** [comment]
@wiiaboo Version 4.0.5.7 is now available for FF, could you upgrade and see if you experience issues?

**Comment by wiiaboo** [comment]
Hey @arnoudkooi,

Everything seems OK to me.

**Comment by arnoudkooi** [comment]
Thanks, I see a few javascript eventhanders are stripped from slashcommands, will look at it

**Comment by wiiaboo** [comment]
Only noticed now that this shows up in the console:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c85bc2c1-eb8d-bc4a-8141-964ed7b0f4cf/js/purify.min.js
Source Map URL: purify.min.js.map
```

**Comment by dg42xyz** [comment]
I notice that same warning in the console using version 4.0.5.7 in FF.  I also get this console error: 
```
Uncaught ReferenceError: DOMPurify is not defined
    <anonymous> moz-extension://77dd9842-3211-4589-9db2-92931027a975/inject_parent.js:6
inject_parent.js:6:5
    <anonymous> moz-extension://77dd9842-3211-4589-9db2-92931027a975/inject_parent.js:6
```

Also there is a `debugger` statement in there somewhere, but it looks like that was reported via Twitter and you responded to that already.

Also, just wanted to say that I appreciate the transparency of posting the Mozilla review finding here!

**Comment by arnoudkooi** [comment]
Thanks, could you share the url path where you got this error?

**Comment by dg42xyz** [comment]
I just tested it out and it seems like I get the error every time I load a page in a new tab or refresh a page (F5), as long as the left-navigation frame is visible (e.g. nav_to.do is in the URI).  I don't get the error if I navigate to a new list/form using the left-nav, nor if I load the page for the first time without nav_to.do in the URI.

Hope this helps, let me know if you need any more info.

**Comment by arnoudkooi** [comment]
The mentioned issues should be fixed in  4.0.5.7, I will update when this one is published in the Add on store. Expect this can take a few days.
(note that the FF OnPrem version is taken offline, as it was marked duplicate)

**Comment by arnoudkooi** [comment]
The mentioned issues should be fixed in 4.0.5.7,  this one is now published in the Add on store. 
(note that the FF OnPrem version is taken offline, as it was marked duplicate)
@wiiaboo @dg42xyz Could you do some testing and update if there are findings?

**Comment by wiiaboo** [comment]
Been using it as normal without any problems so far.

**Comment by arnoudkooi** [comment]
Good, please raise an issue if you do come across something.
