### ISSUE TITLE
Chromium DOMPurify Failure to Load

### ISSUE THREAD

**Issue by sanluyene** [arnoudkooi/ServiceNow-Utils#67]
This may be related to #66 , as of this morning the DOMPurify issue is affecting both **Edge** (Version 84.0.522.63 (Official build) (64-bit)) and **Chrome** (Version 85.0.4183.83 (Official Build) (64-bit)). The below error occurs in the console at every page load, with or without the nav pane open.

As a result, VS Sync, slashcommands, and technical name displays do not work. The extension tabs (Update Set, Updates, View Data, etc.) appear to function without issue.

```
Denying load of chrome-extension://lfabkiipmidkmhplochgpbaeekjjfbch/js/purify.min.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
GET chrome-extension://invalid/ net::ERR_FAILED content_script_all_frames.js:37
Uncaught ReferenceError: DOMPurify is not defined inject.js:1555
    at setShortCuts (inject.js:1555)
    at snuSettingsAdded (inject.js:877)
    at <anonymous>:1:200 
Uncaught ReferenceError: DOMPurify is not defined at inject_parent.js:6
```

Love this extension, by the way. It's essential for my and my dev team's work!

**Comment by arnoudkooi** [comment]
Thanks I suppose this is about the onprem version? I just uploaded a fix (4.0.6.3) that should be available by tomorrow.

**Comment by sanluyene** [comment]
Excellent, thank you!

**Comment by arnoudkooi** [comment]
The new version should be available now, please let me know if this fixes the issue...

**Comment by sanluyene** [comment]
Everything appears to be in working order. Thank you so much!

**Comment by arnoudkooi** [comment]
Great, thanks for bringing this to attention!
