### ISSUE TITLE
Angle bracket's character Encoding issue

### ISSUE THREAD

**Issue by Decoder-Paul** [arnoudkooi/ServiceNow-Utils#68]
Simply open 'Attachment' UI Page in VS Code and save it. 
The angle brackets are getting converted to the respective escape characters.

![Snutil issue](https://user-images.githubusercontent.com/10209345/92113817-831e2d80-ee0d-11ea-8ed3-22c338a85b36.PNG)

**Comment by arnoudkooi** [comment]
Per [the FAQ section of sn scriptsync](https://marketplace.visualstudio.com/items?itemName=arnoudkooicom.sn-scriptsync) you must add / update a system property in your instance:
`glide.rest.sanitize_request_input = false`

Hope this helps!

**Comment by Decoder-Paul** [comment]
Great, It worked thanks @arnoudkooi
