### ISSUE TITLE
requestRecord and requestRecords aren't getting the websocket passed to them?

### ISSUE THREAD

**Issue by schwin97** [arnoudkooi/ServiceNow-Utils#69]
I am working on a fork of the vs code extension to add an index file to store the pulled files metadata and noticed that these two functions are making calls to ws without it being passed to them (and I am pretty sure it isn't a global either).  Not sure if my problem was the websocket or the token that may not have been getting updated correctly?

**Comment by arnoudkooi** [comment]
Looks I forgot to declare `ws` making it global when its instantiated in inside connect() . It should be declared as a global variable. I've committed a fix, so it will be in the next update, functional it doesn't matter so not publishing it immediately.

**Comment by arnoudkooi** [comment]
This commit is published a few weeks back.
