### ISSUE TITLE
Hotkeys for Context menu > ServiceNow Utils > Tools

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#7]
With the new menu structure 2 of my most used features have become somekind of not-so-good-accessible: "Pop In/out" and "Show technical names". One option would be to change the menu structure again, but i kind of can understand why you did this. So as an alternative and for easy accesibility some hotkeys should be defined.

![image](https://user-images.githubusercontent.com/6060660/41204914-2d247fe2-6ceb-11e8-98b7-a328a414fb87.png)

It can be discussed whether Alt is the right key here or if the list should include [Alt+3] to [Alt+6]. In any way i would not include the "Cancel Transaction", as this could cause unintended stopping of scripts.

**Comment by arnoudkooi** [comment]
Thanks for your work so far,  the most used can be set in chrome://extensions/shortcuts already :)
Lets discuss later.

**Comment by meinzeugde** [comment]
Hey thanks for the tip!

![image](https://user-images.githubusercontent.com/6060660/41205147-2368c6ea-6cee-11e8-9296-83e44e712ed9.png)

I guess you may close this one. Maybe add it somewhere to the docs.

**Comment by arnoudkooi** [comment]
Added an extra tab: shortcuts to inform users how to change this
