### ISSUE TITLE
Slashcommand for table search open in new tab/window

### ISSUE THREAD

**Issue by t1mb0b** [arnoudkooi/ServiceNow-Utils#70]
Not sure if this is an already existing feature, however I cannot find a setting for this. Is it possible to configure so when I search for a record in a table (example /si TaskUtil) it would open the search result in a new tab/window? Is it possible for that to be an option per slashcommand in the comfiguration?

Thanks!

**Comment by arnoudkooi** [comment]
Hitting ctrl or cmd enter should open a new tab.
Holding ctrl shift enter forces to load in current tab. Hope that works.

**Comment by t1mb0b** [comment]
Yes, that works, thank you!

**Comment by arnoudkooi** [comment]
Good, be sure to check [this article](https://www.linkedin.com/pulse/10-overlooked-features-sn-utils-servicenow-arnoud-kooi/) if you haven't done so. Tip 1 and 5 are about slashcommands.
