### ISSUE TITLE
[Feature Request] Show XML

### ISSUE THREAD

**Issue by ovarn** [arnoudkooi/ServiceNow-Utils#71]
1) 'Show XML' in the list context menu (for all users, not only for admins)
2) 'Show XML' in the chrome.contextMenus because the OOTB link is available only for admins

Thank you!

**Comment by arnoudkooi** [comment]
Non admins can use the slashcommand `/xml` or `/xmlsrc` as well as the view data tab in the popup, hope this is sufficient.

**Comment by ovarn** [comment]
Ok, this solves the second request. But what about the first one?

**Comment by arnoudkooi** [comment]
What is the use case? i'm hesitant to add ways to offload data.

**Comment by ovarn** [comment]
There is no way to export XML of the specific record from the list. As an admin, I should set up the filter to have only one record, and only after that do export XML. If I am a non-admin user I should open the record, open slash commands, and only after that export XML. The use case is to save clicks.

**Comment by arnoudkooi** [comment]
I dont see a obvious way to implement, and I want to prevent I enable prevent enabling downloading x MB of data...
If a org is ok with this, they maybe able to look at the ACL's for the contextmenu.
