### ISSUE TITLE
Show technical names fails on list view column headers when sorting on a field

### ISSUE THREAD

**Issue by shivaramumapathy** [arnoudkooi/ServiceNow-Utils#72]
Steps to reproduce:

1. Enable "Show Technical Names" in settings
2. Open any list view and notice the technical names displayed for each column header
3. Sort ascending or descending on any column header
4. List reloads with new order but technical names are missing

**Comment by arnoudkooi** [comment]
Confirmed.
I'll see if there is an easy and elegant fix ( i dont want to retrigger the function every x second via setInterval).
For now the recommendation would be to re trigger technical names via shortcut (default ctrl-3) or slashcommand (/tn)

**Comment by wiiaboo** [comment]
Hey @arnoudkooi,

In [this user script](https://greasyfork.org/en/scripts/411666-servicenow-update-versions-highlight-different-sources/code), I'm using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to reapply color changes to the list when resorting. You might want to use the same thing.

**Comment by arnoudkooi** [comment]
The setting is called `Show Technical names on page load` and that is what it does, I appreciate the idea @wiiaboo but I think it's to much of an edge case to justify adding observers, also because you can retrigger the function with a single keystroke...
