### ISSUE TITLE
New option -query for /[table] slashcommand

### ISSUE THREAD

**Issue by gmmeng** [arnoudkooi/ServiceNow-Utils#73]
Requesting new option to allow for directly querying a table through slashcommand. For example:

As a ServiceNow itil user, I want to enter "/alm_hardware -query asset_tagSTARTSWITHabc" as a slashcommand, so that the table alm_hardware will open with the filter asset_tagSTARTSWITHabc applied.

**Comment by wiiaboo** [comment]
Seems duplicate of https://github.com/arnoudkooi/ServiceNow-Utils/issues/65

**Comment by gmmeng** [comment]
> Seems duplicate of #65

Yeap, you're right. That can be used just fine. Thanks a lot!
