### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by CoyoteRay** [arnoudkooi/ServiceNow-Utils#74]
Good day.  What are the license terms for ServiceNow-Utils?  I have reviewed the readme file.  My legal department is looking for the Open Source License and Version Number, MIT, Apache 2.0, ... 

Forgive me if I missed it somewhere. 

Thank you.

**Comment by arnoudkooi** [comment]
Please checkin via apps@arnoudkooi.com

**Comment by arnoudkooi** [comment]
Checked in.
