### ISSUE TITLE
[Feature Request] Update set “Quick release”

### ISSUE THREAD

**Issue by rverrips** [arnoudkooi/ServiceNow-Utils#75]
LOVE the recent update for browser badge icons - thank you for such a great plugin!

Not sure if this is a best way todo things, but often we'll have a small/trivial update we want in all instances (members of a critical group as an example that we add to an update set in Dev instance).   Due to low risk and desire to impact all systems, we then "run" the update set pipeline with our regular steps of:

1 - complete update set in Dev instance
2 - switch to UAT instance
3 - retrieve update sets from Dev to UAT
4 - preview retrieved update set in UAT
5 - Run ATF tests if applicable (often is not due to trivial nature of change)
6 - commit update set to UAT
7 - switch to PROD instance
8 - retrieve update sets from UAT to PROD (similar step 3) 
9 - preview retrieved update set in PROD (similar to step 4)
10 - Run ATF if needed in Prod, often not needed, similar to step 5
11 - commit update set in PROD instance

This is the deployment pipeline we use regularly and 95% of the time it's not an issue as there are other users involved and time gaps (sometimes days) between the steps.

Assumption 1:  This is best practice and done my many other ServiceNow developers 
Assumption 2:  There are a small number of times (the 5% I list above) when it's tedious, time consuming and could be automate as all steps are done in succession. 
Assumption 3:  A browser plug-in is the best place for this.  I've been thinking of perhaps doing this as a script in DEV using API's to push and apply into the instances. 

Feature Request (if assumptions are correct): have a slash command or other menu option in the browser plug-in that will allow user to select a completed update set in Dev that then "posts" or update that into UAT and PROD, previews and commits. 

Would obviously need:  
1 - instances to be "linked" in the config of the plug-in, I.e. identify which instance is UAT/Prod for which DEV
2 - If done purely by the browser plug-in, will need the developer to correctly be logged in (ie not impersonating if not needed) and have an active session in each instance.  
3 - would need to have a way to stop / roll back if any issues in the "Quick deploy" occurred. 

As mentioned in the assumptions, this may not be something to tackle in the plug-in and there many be some other best practice for these type of updates I'm not aware of - please let me know if either of those are the case and feel free to drop this request if not helpful/feasible. 

Arnoud, thank you again for a great plug-in!

**Comment by arnoudkooi** [comment]
Appreciate the idea Roy, but this is a stretch :). Have you seen what ServiceNow self is doing to support CICD pipelines?

**Comment by rverrips** [comment]
Fully understood - thank you SO much for taking the time to evaluate.

I'll check out the CI/CD pipeline options, thanks for the pointer :)
