### ISSUE TITLE
Extend "Show technical names": Show values for select

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#8]
Besides having a quick look on technical field names it would be also quite time saving to instantly see the real values behind selection fields.

e.g. the States for an Incident:
![image](https://user-images.githubusercontent.com/6060660/41215697-d8b5664e-6d51-11e8-87af-6a1bae7d2810.png)

This is quite easy to implement, since all the values are available on the options fields:

![image](https://user-images.githubusercontent.com/6060660/41215713-ee4c6318-6d51-11e8-85bb-3a823f46fe96.png)

**Edit:**

1. Some other live-saving could be done on the Relationship Editor for CMDB. When you want to add a Relation, but the Lables are identical and you don't know exactly what to choose from:

![image](https://user-images.githubusercontent.com/6060660/41216121-47ee1488-6d53-11e8-9b44-1d719dc43b1a.png)

2. Other usecase: Condition Builder - Show Technical field names additionally to labels

3. The tree picker (this historical and awkward design choice still existing on UI Policies):

![image](https://user-images.githubusercontent.com/6060660/41216358-4676b67c-6d54-11e8-9897-d650e07cfedc.png)

In this Case i know, it's not a Selection field, but it should really be included.

**Comment by meinzeugde** [comment]
After several editing i hope i got every must-have use-case for this ;)

**Comment by meinzeugde** [comment]
Implemented.

**Comment by arnoudkooi** [comment]
Sorry, but can you re-implement on the refactored code. Maybe you can reach out to me, so we can align.

**Comment by meinzeugde** [comment]
I closed the issue, because the implementation is done and tested. As for the merging, please continue the discussion in #2, since from my perspective this is the only thing blocking a release, is it?
