### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by eughcus** [arnoudkooi/ServiceNow-Utils#82]
Hey,

SN Utils has stopped working for me raising the following exception: 
![image](https://user-images.githubusercontent.com/41437849/99411466-ae8cc080-2904-11eb-81e6-432b52b7c438.png)

Extension view containing Update Set, Node, user, etc. lists is still working, but slashcommands, technical names and other embedded features just don't. 

I assume this is caused by the recent addition (I see the file got updated 8 days ago) to content_script_all_frames.js:
```javascript
let doc = document?.querySelector('#gsft_main')?.contentWindow?.document;
```
Apparently, [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is an experimental js feature in Chrome before v80
I'm on Fedora 31 which has Chrome 79 as the currently supported browser version, I had to turn experimental JS features on in chrome://flags in order to get SN Utils back working :) 

![image](https://user-images.githubusercontent.com/41437849/99411356-9157f200-2904-11eb-971d-76f0f6d78674.png)

Just wanted to share the fix with anyone facing this issue.

Thanks!
Yevgeny

**Comment by wiiaboo** [comment]
That's kinda sad.
