### ISSUE TITLE
Can't copy the technical name of a field on the alert

### ISSUE THREAD

**Issue by dgcst** [arnoudkooi/ServiceNow-Utils#84]
For a while now, on Chrome/Edge, whenever I double-click the label of a field, the resulting alert does not allow to copy the field's technical name.

I understand that this is a limitation of the browser so, if there's no direct solution for this, may I suggest adding an option so that I can disable the hyperlinks when using the SN Utils functionality of showing the technical themes? With this, I can use that functionality and, then, simply double-click any technical name and copy it.

**Comment by arnoudkooi** [comment]
Strange, seems that behaviour changed indeed. 
Would a mousedown => select text work as well?
Don't want a overload of setting toggles

![select](https://user-images.githubusercontent.com/840781/99714526-f8f97300-2aa5-11eb-9c8e-2ba8886a4559.gif)

**Comment by arnoudkooi** [comment]
@wiiaboo Not sure what you mean with your comment, can you add a screenshot of the result of your PR
Would this work with a label that has a help hyperlink? 
Im currently moving that link, so that dubbelclick to edit works.

![image](https://user-images.githubusercontent.com/840781/99721185-1979fb00-2aaf-11eb-9452-99595a7d8931.png)

tbh Im not a big fan of adding this, as I think the solution in my first response is fine.

**Comment by jacebenson** [comment]
Im in favor of just 
> Would a mousedown => select text work 
as @arnoudkooi suggested.

**Comment by wiiaboo** [comment]
> Would this work with a label that has a help hyperlink?

Would look like this
![image](https://c.tsu.re/E2.png)

> 
> 
> Im in favor of just
> 
> > Would a mousedown => select text work
> 
> as @arnoudkooi suggested.

That's not really a fix though, just a compromise/workaround.

I don't really care that much either as text selection in alerts in Firefox still works just fine, and I already always used technical names for this usecase.

**Comment by dgcst** [comment]
> Would a mousedown => select text work as well?
It does but, from an efficiency perspective, being able to select the entire technical name with a double-click saves a lot of effort.

**Comment by arnoudkooi** [comment]
Commited @wiiaboo  code,  including it in the next release :)

**Comment by arnoudkooi** [comment]
This causes it to span 3 lines i many cases,  i already decreased the font size.
Im happy with the result.

![image](https://user-images.githubusercontent.com/840781/99846696-1ea27d00-2b77-11eb-9248-2abe96fed79c.png)

**Comment by wiiaboo** [comment]
Yeah, it starts getting cluttered.
How would you feel about something like this? Too hidden?
![video](https://c.tsu.re/Et.webp)

**Comment by arnoudkooi** [comment]
No, the ideas is that you have all insight in a blink of an eye...

**Comment by arnoudkooi** [comment]
The ctrl - cmd down is broken as well now, ctrl-click should open the record direct, rather then the list

**Comment by wiiaboo** [comment]
Yeah, I noticed (I wasn't aware of the ctrl+click feature even). But it's broken right now, not due to my rework, right?

**Comment by arnoudkooi** [comment]
ill look at it... please no PR now, i have some things in flight and not a merge wizard..

**Comment by wiiaboo** [comment]
It's just missing the `".do"` after `refTable`

**Comment by arnoudkooi** [comment]
Like this for now...

![2020-11-20 23 04 23](https://user-images.githubusercontent.com/840781/99854329-e4d87300-2b84-11eb-901d-b676015d6a2a.gif)

**Comment by arnoudkooi** [comment]
hope it works :)
