### ISSUE TITLE
Suggestion: Add a way to copy selected cells from List View

### ISSUE THREAD

**Issue by dorsy99** [arnoudkooi/ServiceNow-Utils#88]
Hi Arnoud,

A member of my team gave me a "Bookmarklet" which when used presents a way to copy selected information from a list view. It's super handy when exporting data.
I was wondering if you could include something similar in SNUtils?

here's the code:
`javascript:(function alertSelectedCellValues($) { /*Check directly in the body.*/ var selCellsBody = $(document).find('.list_edit_selected_cell'); /* Check in each iframe.*/ var selCellsIframesArr = []; $('iframe').each(function(index, elem) { var selCells = jQuery(elem).contents().find('.list_edit_selected_cell'); if (selCells.length > 0) { selCellsIframesArr.push(selCells); } }); var finalSelectedCells = null; if (selCellsBody.length > 0) { finalSelectedCells = selCellsBody; } else if (selCellsIframesArr.length > 0) { finalSelectedCells = selCellsIframesArr[0]; } if (finalSelectedCells) { var str = ''; finalSelectedCells.each(function(cIdx, cElem) { str += jQuery(cElem).text() + '\n'; }); prompt('Copy this:', str); } else { alert('No selected cells found'); } })(jQuery)`

**Comment by arnoudkooi** [comment]
Thanks Andrew, I did consider this before, but for me the [CopyTables](https://chrome.google.com/webstore/detail/copytables/ekdpkppgmlalfkphpibadldikjimijon) extension did a good job at this.

**Comment by arnoudkooi** [comment]
I'll have a look though :)

**Comment by arnoudkooi** [comment]
Added this via slashcommand `/copycells` or right click context menu `Copy Selected Cell Values from List` When using context menu, be sure to hold ctrl when right clicking, to prevent the ServiceNow context menu.
Please check if it works.
