### ISSUE TITLE
Filter on dropdown/choice fields

### ISSUE THREAD

**Issue by gmmeng** [arnoudkooi/ServiceNow-Utils#89]
There used to be a text area on top of every choice field to allow for filtering the options. I can't find a way to enable it anymore.

Now it only shows on the Actions list at the bottom of a list.

![image](https://user-images.githubusercontent.com/11929526/101376529-b34af180-387e-11eb-944e-a88ba259e2bf.png)

**Comment by arnoudkooi** [comment]
It only adds this when there are 25 items or more in the list.
My guess is that other one has less than 25 items?

**Comment by arnoudkooi** [comment]
Hope this makes sense :) 
I have changed the setting to 15...

**Comment by gmmeng** [comment]
> Hope this makes sense :)
> I have changed the setting to 15...

Thanks @arnoudkooi 
I was actually able to use this feature on the Update set picker, and it it's not there anymore. Could you confirm if it was supposed to be there?
Also, I've been noticing that some choice fields have the filter available and some don't. I'm not sure what's the difference there:
![image](https://user-images.githubusercontent.com/11929526/101815684-e5ae5600-3aed-11eb-9743-163a0c742653.png)

![image](https://user-images.githubusercontent.com/11929526/101815701-ec3ccd80-3aed-11eb-808c-b9e93fd4a988.png)

**Comment by gmmeng** [comment]
Sorry, I might have misunderstood your explanation from before about changing the threshold from 25 to 15 item, which should explain why one of the fields don't have the filter available. However, the update set picker definitely has more than 25 items but the filter isn't there.

Thank you!!

**Comment by arnoudkooi** [comment]
Good you figured out the first part.
For the US picker you need to enable the setting:
`Enhance Application and Updateset picker at page load.
`in the settings tab of the popup

**Comment by gmmeng** [comment]
> Good you figured out the first part.
> For the US picker you need to enable the setting:
> `Enhance Application and Updateset picker at page load. `in the settings tab of the popup

Thank you so much! @arnoudkooi
That's definitely my issue. I had to reinstall the extension and forgot to reset it the way it was.
