### ISSUE TITLE
ServiceNow Utils > Tools > Set all mandatory fields to false

### ISSUE THREAD

**Issue by meinzeugde** [arnoudkooi/ServiceNow-Utils#9]
Simple but really helpful when testing certain things on forms where an endless amount of mandatory fields hinders you from beeing fast:

![image](https://user-images.githubusercontent.com/6060660/41717014-9f3990ca-7558-11e8-9b5a-a0bde90ac749.png)

Sure it will work only on UI Policy/Client Script level, but most of the time this is the only validation anyway.

In **Backend** it's super easy to implement.: `g_form.setMandatory('field', false)` 

On **Service Portal** it will be a bit harder.
What i quickly tested is to go through all forms and fields and check for the mandatory attribute:

`angular.element('form').eq(0).scope().mandatory[1].mandatory = false`

**Comment by arnoudkooi** [comment]
Can you implement an isAdmin function / check? I want this type of function only available if the user has admin role, to prevent misuse by normal users in prod instances.

**Comment by meinzeugde** [comment]
Sure. Good point!

**Comment by arnoudkooi** [comment]
Can we get on the same track again?

**Comment by arnoudkooi** [comment]
closing for now, please reach out if needed
