### ISSUE TITLE
Check if user is searching below tables, if not, let them know how to add them

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#91]
This started from a twitter thread: https://twitter.com/jacebenson/status/1346186440066150401

Here's the list I've maintained, but it might be useful here.

Table | Search Fields | Additional Filter
-- | -- | --
bsm_action | name, script | active=true^EQ
cmn_map_page | name, script |  
content_block_programmatic | name, programmitc_content | active=true^EQ
ecc_agent_script_include | name, script | active=true^EQ
kb_navons | name, script | active=true^EQ
metric_definition | name, script | active=true^EQ
process_step_approval | name, approver_script |  
sc_cat_item_producer | delivery_plan_script,   entitlement_script, post_insert_script, script | active=true^EQ
sp_angular_provider | script |  
sp_search_source | data_fetch_script,   facet_generation_script, search_page_template, typeahead_template |  
sp_widget | template, script, client_script,   link |  
sysauto_script | name, script, condition | active=true^EQ
sysevent_email_action | name, advanced_condition, message,   sms_alternate | active=true^EQ
sysevent_email_template | name,message,message_html,sms_alternate,subject |  
sysevent_in_email_action | name,script,filter_conditions,condition_script | active=true^EQ
sysevent_script_action | name,script,condition_script,event_name | active=true^EQ
sys_app_quota | query |  
sys_dictionary | dynamic_ref_qual,reference_qual,attributes,default_value,calculation | active=true^use_dynamic_default=false^EQ
sys_dictionary_override | reference_qual,attributes,default_value,calculation |  
sys_filter_option_dynamic | script_reference_id, script | active=true^EQ
sys_installation_exit | name, script | active=true^EQ
sys_processor | name,script,description,path,class_name | active=true^EQ
sys_properties | name,choices,value |  
sys_relationship | name,apply_to,query_from,query_with |  
sys_script | name,script,condition,filter_condition | active=true^EQ
sys_script_ajax | name, script | active=true^EQ
sys_script_client | name, script | active=true^EQ
sys_script_email | script |  
sys_script_fix | name, script | active=true^EQ
sys_script_include | name, script | active=true^EQ
sys_script_validator | validator | validatorLIKE^EQ
sys_security_acl | name, script, condition | active=true^EQ
sys_transform_entry | source_script |  
sys_transform_map | name, script | active=true^EQ
sys_transform_script | script | active=true^EQ
sys_trigger | name, script, job_context |  
sys_ui_action | name,script,condition,onclick | active=true^EQ
sys_ui_context_menu | action_script,condition,on_show_script | active=true^EQ
sys_ui_list_control | columns_condition,edit_condition,empty_condition,filter_condition,link_condition,new_condition |  
sys_ui_macro | name, xml | active=true^EQ
sys_ui_page | name,client_script,html,processing_script |  
sys_ui_policy | short_description,script_false,script_true,conditions | active=true^EQ
sys_ui_script | name, script | active=true^EQ
sys_variable_value | value |  
sys_web_service | script | active=true^EQ
sys_widgets | name, script | active=true^EQ
sys_ws_operation | operation_script | active=true^EQ
wf_activity_definition | name, script |

**Comment by arnoudkooi** [comment]
I published the following implementation:

![image](https://user-images.githubusercontent.com/840781/104138212-f24ef400-53a2-11eb-8ce7-04842bb548ed.png)

The link prefills a new record, that the user needs to submit:
![image](https://user-images.githubusercontent.com/840781/104138235-1dd1de80-53a3-11eb-8df3-2af0af746696.png)

What do you think?

**Comment by jacebenson** [comment]
You did all the hardwork, credit not needed but appreciated.  Thansk man!

**Comment by jacebenson** [comment]
Do the suggested tables fall off once the record exists?

**Comment by arnoudkooi** [comment]
Yes, after a page refresh..
