### ISSUE TITLE
Strange button artifact on WYSIWYG editor

### ISSUE THREAD

**Issue by iar42** [arnoudkooi/ServiceNow-Utils#92]
With "Enhance Application and Updateset picker at page load." enabled I sometimes see the following strange button artifact on the WYSIWYG editor when for example viewing a Story in a modal window on a Visual Task board:

![image](https://user-images.githubusercontent.com/5203702/103889323-22b23c00-50de-11eb-9d62-6b0efa49ca2a.png)

(The screenshot is taken on a Paris PDI using Chrome 87.0.4280.88 (Official Build) (64-bit) with SN Utils 4.2.6.0)

**Comment by arnoudkooi** [comment]
I have seen this once while trying to replicate. Ill disable this function in a upcoming update.

**Comment by arnoudkooi** [comment]
Disabled in 4.2.6.5
