### ISSUE TITLE
Feature request: Open a random record in a given table

### ISSUE THREAD

**Issue by EricMedina024** [arnoudkooi/ServiceNow-Utils#93]
I am suggesting a feature that will open a random record in a given table, perhaps as a slash command or via the sidebar by typing something such as `incident.random` similar to how you can type `incident.list` in OOB snow. Additionally, it may be useful to be able to get a random active record. If this is an interesting feature to anyone, I may be interested in opening a PR.

**Comment by arnoudkooi** [comment]
Seems like a bit a niche demand that would require some logic.
What is the use case?

**Comment by EricMedina024** [comment]
It would be mostly useful for easily pulling up test records. e.g. if I just created a client script that applied to incident and I want to test that client script with a couple random examples of real data, I could use this to easily pull up random records to test on.

**Comment by arnoudkooi** [comment]
Conceptually you would first do the following steps

- Aggregate API call  tp get the no. of records (N)
- Generate  a random number between 0 and N
- Call the table API with parameter sysparm_offset=N+1 and limit=1
- Return the sys_id of the result

Any demand for this from others?

**Comment by arnoudkooi** [comment]
As I dont see a update or more demand I'm closing this one

**Comment by Pikachu920** [comment]
@arnoudkooi  open to a PR?

**Comment by EricMedina024** [comment]
@arnoudkooi would you be open to a PR or are you not interested in this feature at all?

**Comment by arnoudkooi** [comment]
This is realised now, please check tweet:
https://twitter.com/sn_utils/status/1378277594546769923
also used in feature
https://twitter.com/sn_utils/status/1378276551675027456
