### ISSUE TITLE
Vivaldi - tools menu no longer appears after left clicking the button

### ISSUE THREAD

**Issue by heroje** [arnoudkooi/ServiceNow-Utils#95]
![image](https://user-images.githubusercontent.com/45423203/106137763-765af700-616b-11eb-89df-46331dc13ce7.png)
Vivaldi browser version 3.5.2115.87
I have tried removing and re-adding the extension from the Chrome webstore, changing the browser settings having to do with ad/tracker blocking and opening new windows as tabs, using another browser profile, creating a fresh profile.
It seems to have started occurring for me today, is there a way to install an older version of the addon? And what other information may I provide to make troubleshooting this easier?

**Comment by arnoudkooi** [comment]
I onlypushed a very minor unrelated update, could this be an Vivaldi bug? Looks it had a major update?

**Comment by arnoudkooi** [comment]
Assume it works again...
