### ISSUE TITLE
Feature Request: /v or /versions to open Versions of current record

### ISSUE THREAD

**Issue by dorsy99** [arnoudkooi/ServiceNow-Utils#96]
Hey Arnoud,

My team has been doing some Paris upgrade reverts and a lot of our changes to forms are adding the "Versions" related list. Do you reckon there's a way you could include a similar functionality in snutils for /versions, which could show all versions of a record, or (maybe even better) pick a version to compare using the diff editor?

Thanks a lot!

-Andrew

**Comment by VanWeapon** [comment]
This is already available in the context menu, Tools > Update Versions

![image](https://user-images.githubusercontent.com/30616047/106526839-6449d180-653a-11eb-837a-062c0d7185e4.png)

**Comment by dorsy99** [comment]
@VanWeapon Thanks for that! I'll leave the request open for a slash command and possibility of the comparison as well.

**Comment by VanWeapon** [comment]
I just tried replicating it with a custom slashcommand, the issue is you need to know the name of the table as well as the sys_id, as far as i can see, you cant substitute the current record sys_class_name in the slashcommand URL, or any field other than sys_id for that matter.

This could also be an opportunitity for aribitrary variable substitution in slashcommand urls following some naming convention, e.g. `$sys_class_name` or something. 

The resulting URL template for /v would be something like. 
`/sys_update_version_list.do?sysparm_query=name=$sys_class_name_$sysid^ORDERBYDESCsys_recorded_at`

**Comment by wiiaboo** [comment]
> The resulting URL template for /v would be something like.
> `/sys_update_version_list.do?sysparm_query=name=$sys_class_name_$sysid^ORDERBYDESCsys_recorded_at`

`/sys_update_version_list.do?sysparm_query=name=$table_$sysid^ORDERBYDESCsys_recorded_at` works right now.

**Comment by VanWeapon** [comment]
> `/sys_update_version_list.do?sysparm_query=name=$table_$sysid^ORDERBYDESCsys_recorded_at` works right now.

I swear I tried that as well before and it didnt work 🤷 probs a typo on my part. 
That makes life easier then

**Comment by arnoudkooi** [comment]
Thanks for chiming in guys!

When using overwrite target url like:
`/merge_form_current_version.do?sysparm_version_id=$sysid
`
And setting fields to ` sys_recorded_at,sys_created_by`
You can use the inline search to open the diff editor

![image](https://user-images.githubusercontent.com/840781/106571755-d53bba00-6537-11eb-8c3d-fff1844b1303.png)

Demo of slashcommand
![image](https://user-images.githubusercontent.com/840781/106571214-2bf4c400-6537-11eb-8126-591ad0789fac.png)

**Comment by dorsy99** [comment]
That's awesome, exactly what we were after. Would you consider adding it to the extension by default? Seems like a valuable addition.

Thanks heaps!
-Andrew

**Comment by wiiaboo** [comment]
> When using overwrite target url like:
> `/merge_form_current_version.do?sysparm_version_id=$sysid `
> And setting fields to ` sys_recorded_at,sys_created_by`
> You can use the inline search to open the diff editor

Cool, didn't realize that's how you'd use the "Overwrite target URL".
Is there a way to select one of the results in the inline search with just the keyboard? Maybe with 1-9 keys?

**Comment by arnoudkooi** [comment]
> Is there a way to select one of the results in the inline search with just the keyboard? Maybe with 1-9 keys?

Nope...

**Comment by arnoudkooi** [comment]
> Would you consider adding it to the extension by default? Seems like a valuable addition.

Sure, if you can give it some MVP love :)

**Comment by dorsy99** [comment]
Will do!

**Comment by arnoudkooi** [comment]
I added this as a built in slashcommand, as well as a minor bugfix.

**Comment by dorsy99** [comment]
Thanks heaps!
