### ISSUE TITLE
Feature Request: Instance specific settings

### ISSUE THREAD

**Issue by shivaramumapathy** [arnoudkooi/ServiceNow-Utils#97]
Could we have settings saved and restored for each ServiceNow instance we visit? Say, I would like to use some settings on instance A and another combination of settings on instance B. When I switch instances, the setting would load and apply appropriately.

PS: just checking in, if you are still working on a Safari extension? Thanks.

**Comment by arnoudkooi** [comment]
I think it may overcomplicates things a bit....

The safari version is available: https://apps.apple.com/nl/app/sn-utils/id1542209967?l=en&mt=12
Note that safari does not support all features.

**Comment by arnoudkooi** [comment]
As stated before, I think this overcomplicates things. You could spread your browser usage (ie FF/Edge) as well as leverage the OnPrem version to have different options
